# bert-architecture-inspection-huggingface

In [1]:
import base64
import gzip
import inspect
import os
import warnings

warnings.filterwarnings("ignore", message="IProgress not found.*")

import pandas as pd
import torch
import transformers
from transformers import BertConfig, BertModel, BertTokenizer

torch.set_num_threads(1)
torch.manual_seed(0)

model_name = "bert-base-uncased"
local_dir = "./bert-base-uncased-local"
os.makedirs(local_dir, exist_ok=True)

embedded_assets = {
    "config.json": "H4sIAL0Nq2kC/3WRwU7DMBBE7/2KKmeI0pS2qEcOnOgXIGRt7G1iJbEte11REP/Oxk5LEeISKTNvdjObz8VyWYCXnSaUFD2GYr98ZZHlJ/T0bP0BQo/q5VCw+naXeCI0pK0RztsmCOWts5HSG8ercpWw1oPSDArZoeyd1ZwxLQNHGAImpNNKoREgieWixSEWt/o/g2c36A9kdbd9TKo2mjQMLHrhwbSYElU9m4R+RKWB8BJcV7tsDnDmjLF+FOimA6zwfpWtEd6Fs0Gntjg2qBR3mJjNhbAKB0FnN40sGr5ZrmDiKH4O1SGoNLm+mnOLtPzGcqAE2Z4draYGWfzzCdeN0AQ7RMK8lbh5OHITnilO/ODQRD2U27IqFZ6qmeO0OFkJzeUaeXsMKCTwD2OFfMx/6Re3rjZ1vfhafAPtDLzyOgIAAA==",
    "vocab.txt": "H4sIAL0Nq2kC/1S9WbMc15kt9r7/hQ3PQ/vUXOX5hn2fru24ER1+al/bWVVZVXlOVmYps/IcFDwEAXAAJ42USIqiKE4QKVHgCBKcI6DuG0EqgiLDwQbZ/dISBA5P/Re81vp2Vn2M4CaAc6py79zD+qb1fftv/vW/+B//TfibpmjqdH60/1tn/7fu/m+9/d/6+78N9n8b7v822v9tvP/b5PBk18mhl86hm86hn86ho86hp86hq86hr86hs86ht+6ht657p0Nv3UNv3UNv3UNv3UNv3UNv3UNv3UNvvUNvvUNvPTeFh956h956h956h956h956h956h976h976h976h976bsUOvfUPvfUPvfUPvfUPvfUPvQ0OvQ0OvQ0OvQ0OvQ3cBjn0Njj0Njj0Njj0Njj0Njz0Njz0Njz0Njz0Njz0NnT78dDb8NDb8NDb8NDb6NDb6NDb6NDb6NDb6NDb6NDbyG3/Q2+jQ2+jQ2/jQ2/jQ2/jQ2/jQ2/jQ2/jQ2/jQ29jd9oOvY0PvU0OvU0OvU0OvU0OvU0OvU0OvU0OvU0OvU3Y2//6v/wr/P9/+J/+Gv//63/5r/H///lf/PW/OnzGH3t37o/cwT9yJ//IHf0jd/aP3OE/cqf/yB3/I3f+j1y/38Eb169HHA85HnM86HjU8bDjcccBT8chT6frgc7168Cn49Cn4+Cn4/Cn4wCo4xCo4yCo4zCo40Co0/MI6/p1ONRxQNRxSNRxUNRxWNRxYNRxaNRxcNRxeNTpe2h3/TpI6jhM6jhQ6jhU6jhY6jhc6jhg6jhk6jho6gy8THH9OnTqOHjqOHzqOIDqOITqOIjqOIzqOJDqOJTqDL0wc/06oOo4pOo4qOo4rOo4sOo4tOo4uOo4vOo4wOqMvBR1/TrM6jjQ6jjU6jjY6jjc6jjg6jjk6jjo6jjs6oy9+Hb9OvjqOPzqOADrOATrOAjrOAzrOBDrOBTrOBjrTLze4BUHpzk4vOo6vOo6vOo6vOo6vOo6vOo6vOo6vOo6vOp2vMbi+nV41XV41XV41XV41XV41XV41XV41fWKkteUvqMquX69suS1Ja8ueX3JK0xeY3J41XV41XV41e15Hc316/Cq6/Cq6/Cq6/Cq6/Cq6/Cq6/Cq6/Cq6/Cq2/fKoevX4VXX4VXX4VXX4VXX4VXX4VXX4VXX4VXX4VV34LVS16/Dq67Dq67Dq67Dq67Dq67Dq67Dq67Dq67Dq+7Qq8OuX4dXXYdXXYdXXYdXXYdXXYdXXYdXXYdXXYdX3ZHXw12/Dq+6Dq+6Dq+6Dq+6Dq+6Dq+6Dq+6Dq+6Dq+6Y28AuH4dXnUdXnUdXnUdXnUdXnUdXnUdXnUdXnUdXnUn3vLwpoezPRxe9Rxe9Rxe9Rxe9Rxe9Rxe9Rxe9Rxe9Rxe9Tre5nH9OrzqObzqObzqObzqObzqObzqObzqObzqObzqdb2x5fp1eNVzeNVzeNVzeNVzeNVzeNXzJp638byR9x0rz/Xr7Txv6HlLz5t63tZzeNVzeNVzeNVzeNXre/PS9evwqufwqufwqufwqufwqufwqufwqufwqufwqjfwdq3r1+FVz+FVz+FVz+FVz+FVz+FVz+FVz+FVz+FVb+gNatevw6uew6uew6uew6uew6uew6uew6uew6uew6veyFvyrl+HVz2HVz2HVz2HVz2HVz2HVz2HVz2HVz2HV72xdyG4fh1e9Rxe9Rxe9Rxe9Rxe9Rxe9Rxe9Rxe9Rxe9Sbed+GdF8574fCq7/Cq7/Cq7/Cq7/Cq7/Cq7/Cq7/Cq7/Cq3/FeE9evw6u+w6u+w6u+w6u+w6u+w6u+w6u+w6u+w6t+17trXL8Or/oOr/oOr/oOr/oOr/oOr/oOr/oOr/oOr/o97ydy/Tq86ju86ju86ju86ju86nvnlPdOefeU9099x0Hl+vUuKu+j8k4q76VyeNV3eNV3eNV3eNV3eNUfeM+Y69fhVd/hVd/hVd/hVd/hVd/hVd/hVd/hVd/hVX/oXXKuX4dXfYdXfYdXfYdXfYdXfYdXfYdXfYdXfYdX/ZH3Bbp+HV71HV71HV71HV71HV71HV71HV71HV71HV71x94J6fp1eNV3eNV3eNV3eNV3eNV3eNV3eNV3eNV3eNWfeO+nd386/6fDq4HDq4HDq4HDq4HDq4HDq4HDq4HDq4HDq0HH+11dvw6vBg6vBg6vBg6vBg6vBg6vBg6vBg6vBg6vBl3v8HX9OrwaOLwaOLwaOLwaOLwaOLwaOLwaOLwaOLwa9Lyn2fXr8Grg8Grg8Grg8Grg8Grg8Grg8Grg8Grg8GrQ9y5u16/Dq4HDq4HDq4HDq4F3q3u/unese8+6d61/x7fu+vXede9e9/51h1cDh1cDh1cDh1cDh1cDh1eDoXfqu34dXg0cXg0cXg0cXg0cXg0cXg0cXg0cXg0cXg1GPprg+nV4NXB4NXB4NXB4NXB4NXB4NXB4NXB4NXB4NRj7MIbr1+HVwOHVwOHVwOHVwOHVwOHVwOHVwOHVwOHVYOLjJz6A4iIoDq+GDq+GDq+GDq+GDq+GDq+GDq+GDq+GDq+GHR+5cf06vBo6vBo6vBo6vBo6vBo6vBo6vBo6vBo6vBp2fcjI9evwaujwaujwaujwaujwaujwaujwaujwaujwatjzsSrXr8OrocOrocOrocOrocOrocOrocOrocOrocOrYd8HyVy/Dq+GDq+GDq+GDq+GDq+GDq+GDq+GDq+GDq+GAx+dc/06vBo6vBo6vBr6gKCPCPqQoI8J+qCgjwp+Jyzo+vWBQR8ZdHg1dHg1dHg1dHg1dHg1dHg1dHg1HPl4pOvX4dXQ4dXQ4dXQ4dXQ4dXQ4dXQ4dXQ4dXQ4dVw7AOhrl+HV0OHV0OHV0OHV0OHV0OHV0OHV0OHV0OHV8OJj8D6EKyLwTq8Gjm8Gjm8Gjm8Gjm8Gjm8Gjm8Gjm8Gjm8GnV87Nf16/Bq5PBq5PBq5PBq5PBq5PBq5PBq5PBq5PBq1PVBZ9evw6uRw6uRw6uRw6uRw6uRw6uRw6uRw6uRw6tRz0e7Xb8Or0YOr0YOr0YOr0YOr0YOr0YOr0YOr0YOr0Z9H2Z3/Tq8Gjm8Gjm8Gjm8Gjm8Gjm8Gjm8Gjm8Gjm8Gg18fN/16/Bq5PBq5PBq5PBq5PBq5PBq5PBq5PBq5PBqNPTEAtevw6uRw6uRpzJ4LoMnM3g2g6czeD6DJzR8h9Hg+vWcBodXI4dXI4dXI4dXI4dXI4dXI4dXI4dXo7GnUrh+HV6NHF6NHF6NHF6NHF6NHF6NHF6NHF6NHF6NJp7D4UkcjsXh8Grs8Grs8Grs8Grs8Grs8Grs8Grs8Grs8Grc8ewR16/Dq7HDq7HDq7HDq7HDq7HDq7HDq7HDq7HDq3HX01Zcvw6vxg6vxg6vxg6vxg6vxg6vxg6vxg6vxg6vxj3Pl3H9OrwaO7waO7waO7waO7waO7waO7waO7waO7wa9z1Rx/Xr8Grs8Grs8Grs8Grs8Grs8Grs8Grs8Grs8Go88Awh16/Dq7HDq7HDq7HDq7HDq7HDq7HDq7HDq7HDq/HQU5Ncvw6vxg6vxg6vxg6vxg6vxg6vxg6vxg6vxg6vxiPPiXL9OrwaexKWZ2F5GpbnYXkilmdieSqW52J9h4zl+nV4NXZ4NXZ4NXZ4NXZ4NXZ4NXZ4NXZ4NXZ4NZ54FpingTkemMOricOricOricOricOricOricOricOricOrScfzz1y/Dq8mDq8mDq8mDq8mDq8mDq8mDq8mDq8mDq8mXU98c/06vJo4vJo4vJo4vJo4vJo4vJo4vJo4vJo4vJr0POPO9evwauLwauLwauLwauLwauLwauLwauLwauLwatL3VD/Xr8OricOricOricOricOricOricOricOricOrycBzDF2/Dq8mDq8mDq8mDq8mDq8mDq8mDq8mDq8mDq8mQ09udP06vJo4vJo4vJo4vJo4vJo4vJo4vJo4vJo4vJqMPKvS9evwauLwauLwauLwauLwauLwauLwauLwauLwajL2dE7Xr6ePev6oJ5B6Binx6t8J/244F/698O+H/yD8h+E/Cv9x+E/Cfxr+s/Cfh78K/0U4Cp3QDb3QD4MwDKMwDpPwX4b/KvzX4b8J/23478J/H/4m/G/h34T/Pfwf4f8MSZiGWZiHNCzCMqxCFo7DScjDOhShDJvwvVCFOmxDE07DWTgfduFC+L/C/x3+n/D/hptPh5vPhJvPhpvPhZvPh5tXw81fh5svhJsvhpu/CTd/G26+FG5eCzdfCTdfDTdfCzdfDzffCDevh5tvhptvhZtvh5vvhJvvhpvvhZvvh5sfhJsfht8/Gn7/VPj91fD7V8Lv3wq/vxF+/0H42x+Fv/11+NtXw99dCn/3YPi7n4R/++Pw0Q/DRz8KH+Evj4SPfho+ejx89ET46Onw0bPhoxfCR78JH/02fPRS+Ojl8NFr4aM3wkdvh48+CB/fFT6+GD6+FD6+HD6+P3z8QPj4wfDxQ+Hj74ePfxg+/lH4+Mfh40fCx6+Ej18LH78ePn4rfHwjfPxu+Pi98DG+/mH4w5Xwhx+GPzwd/vBM+MOz4Q/PhU9eDZ+8Fj55PXzyRvjkevjkzfDJW+GTG+GTt8Mn74RP3g2fvBc+eT988kH45MPwx7vCHy+GP14Kf7wc/nh3+OM94Y/3hj/eF/54Jfzx/vDpK+HTV8Onr4VPXw+fvhE+vR4+fTN8+lb49Eb49J3w6bvh0/fCp++HTz8In34YPrsrfHYxfHYpfHY5fHZ3+Oye8Nm94bP7wmdXwmf3h88eCJ89GD57KHz2cPjs++GzH4TPfhw+eyR89rPw2WPhs8fDZz8Pnz0R/r8fhM+fDp8/Ez5/Nnz+XPj8+fD5i+Hz34bPXwqfvxw+fyV8/kb4/Hr4/M3w+Y3w+Tvh8/fD5x+Ezz8Mf39X+PtL4e/vDn//Qbj1w3DrR+HWj8Otn4Rbj4RbPw23fhZuPRpuPRZuPR5u/TzceiLc+kW49WS49ctw66lw61fh1tPh1jPh1rPh1nPh1vPh1tVw69fh1gvh1ovh1m/CFw+FL54OX/w6fPFC+OLF8AV+8tvwxUvhi9+FL66FL14OX7wSvng1fPFa+OL18MUb4Yvr4Ys3wxdvhS9uhC/eDl+8E768K3x5MXx5KXx5OXx5d/jynvDlveHL+8KXV8KX94cvHwhfvh2+/CD8w73hH14M//By+Id3wj98EP7xYvjHh8I//jj803P3oN2Ldj/aD9B+ivYztEfRfo72C7Sn0J5GexbtObTn0a6i/RrtBbTfoL2E9ju0a2gvo72C9hradbQ30d5Cu4H2NtoHaB+Gf3r+LrQH0fDM5/HMq5fQMJ6rGM/V+9AwpqsY09WfoGFcVzGuqxjXVYzr6hNoGNtVjO0qxnYVY7uK51zlczC2qxjbVYztKsZ2FWO7irFdxdiuYmxXMbarGNtVjOsqxnUV47qKcV3FuK5iXL/GuH6N/q+hz2vo6xr6uIZnX8Pzrr2Ihmdew7Ou4VnX8KxreNa119HwrtfwjGt4xssX0fCMl6+Ef3oN33sNn3sNv3sTz3vzHbR30d4P//QW+noL73gDn7+Bz99AnzfwjjceR/slGt7txjNoeL8beLcbeK8b6P8G3ucG+n0b338Pc/jew+Gf3sf8vX832o/QMGfvP4KGOXv/MbRfoeE57+M5718Nf7rr8fCnyz9E+xHaj9F+gvYI2k/RHkV7DI2f+TnaE2i/QHsS7VdoT6M9g/Zs+NPdd6FdQruMdg/avWj3od2P9gDag2gPoX0f7Qdo6PNu9Hk3+rwHz7kHz7nneTSM6Z5fo72I9hu036FdQ3sZ7TW019HeQLse/nTvC2i/RcPv7n0L7Qbae+FPb7yEhu+88QoaPvfGO+FP1zG+6xjbdYzp+hU0jOv6w2gYy3WM5TrGcf1naHjn63jn6xjPdbzX9efQMK438d5v/ir8+a4fov0I7cdoP0F7BO2naD9DewztcbSfo/0C7Um0X6Lxe0+jPYN2Fe0VtNfQXkd7B+3D8OeLd6Ph5xdfRXsD7Tram2hvod1AexsNn734Lho+f+kutItol9Auo+H7l+5BuxftPrQraPejPYD2MNr30TD2Sxj7JYz9EsZ+CeO+hHFfehQNY7+EsV/C2C89gYbxX3oO7UW0l9AwrksYw9343t34zt14t7vxPvfg3/dgDu7Fs+/Fs+/Fs+/Fz+7lz/Cu92Fc9z2Ehp9fwVivYIxXMMYrGOMVjPEKf47+r6D/K+j7Cubryq/RXkBD31d+E/58Pz53P+bvfozn/ufDnx/Acx7AMx7A+B/Adx/EMx/BfDyCn/8Mc/0zfOfRH4Q/P4afP4bPPYZ5eBw/f/xZNHz/cYzr8d+hvRz+/BT6eQr9vPpe+PM7+PMd/Pn+8+H2XRfRLqFdQbsf7QG0B9EeQnsY7ftoP0D7Rbh9EZ/D+t2+eC8aPn8Rn72Iz17E5y7iMxd/hPYTtJ+iPYr2ONoTaE+iPYX2NNqzaM+hXUV7Ae03aL9Fewntd2jX0F5Gew3tOtoNtHfRPkD7MNzGfriN/XAb++E29sJt7IPb2AO3sQduYw/cvoTxXMLYsRduY/1vY/1vX0K/l55BQ99Y69uX0PelX6Oh/0vo/xL6v4S+L6FfrP/tS6+joe9Lb6G9jYb+L6Hvy+j38mU09HsZ/V5Gv5fR52X0eRnzdBlzAGy5DUy5DTy5DRy5ffmXaHh34Mht4Mht4Mht4Mjty5j7yxjD5RfRMIbLGMNlzMFljOMyxnEZY7iMfi+/F/5y4y60+9EeQHsQ7WG0n6H9Du3d8Je370HDz99+KvzlHfz5zkNoj6D9FO0ltHfQ8Ll3L6Lh9+8+i3Yt/OU9PO+9n4e/vP/D8JcP8MwPn0R7Oty5+Hy4c89ltPvRfov2Urhz7z3hzn3vhDvY03fufzjceQC/e+AJtF+FOw8+Ge489Cgafv/wRTR892H8++Gfhzvffyrc+cGzaM+hvYZ2I9z54RU0fP+HD6HhWT/Gn0/g80/geU+8H+784kE0fO8Xr4Q7T14Kd576frjzK/z5qzfCnWcxHsjtO5DZdyCP7zz3Itpv0PDz5/Hc518Pd373Q7Sr4c61u9DuQ0Nf1/B8yLY71zAWyLI7195E+zDceRljfgWfeQXPfAW/f/XVcOc1zMHr+P0b6PctvNtbv0TDZ2/g72/j+W9jHG/jPd7Gz957DO16uPM+fv4B3uMDfPeDt8KdDzEHH96Nhn4//FX46u4nwldXfoj2I7SraDfCV/c/iPZQ+OqRD8NXP7sP7RW0t8NXjz4fvnrs+2hPofHvvwtfPf5O+OqJ19DwvV9cQbsf7Um0F9BeCl89ic8/iWc/+SraB+GrXz4avnr2Wvjq+QfCVy/gmS+ir9+hr989g/YsGsbw8iPhK7z3V6/ge6+8gXYd7S009PEq+n4Nn33tdbR3w1ev/zR8dR2/u3FP+Oq9Z8LXd70Uvsa5/RqY9fUD+Pv3HwxfP/IU2itob4Wvf/bj8DXG/PXj74evf3432n3h6yeuod0IX//iIho++9Tr4evn8BnoR18//8vwNXSfr6GTfA195Otf43kv4ne/xZ+//RXa2+Hr19E++D7ai+EbyJRv7n8Z7e3wzQOvhm8eRPsB/v2j+8M3jz4Xvnn6IbRHwzfPfxi+ufpg+OaFi+Gb3/wyfIP3++a1J9HeCN+8+wDaw+GbD94M3wK3vsUZ/hZn9NvLL6C9H74Fnn97H35234/Ct1feCN/+9D60t8K3P7sLDZ9/7Em0D8O3j7+Ohs8/cXf49skfoz0Tvn0Gz3j2qfDt1cfRXgrf/vax8C3O2Lcf3Aj//NJFtEvhn9/Dn+9dQbsf7SG0h9G+j/YDtJ+jPRX++f1fhu0qDeUiJMU8ZEXYluEsqQN+ltUBf1mUVSiLcJZtV/hksg3ZNqzwq+ku4B+Lqlzjs1U4d64ONb60K5uwSuZ4WjhLqzRMm22Ypvgmn4Z/F+U2rHfsc4fHpuFslc1WAX2sktMUD16HNWzKrKq3IclztLrkhzN+oA7NBl8oQ6mHpuhihf8liy0GgA/h8VmB8RfpWdielRhpjXElYZvhmWdlk8/RPb6DcSdTPqNOsjmGGcpTewBsVz4moM91iaedO5eGGd4kW4Q8O8HLJLMTfm6Noec7fAzPnem5585lHAy+c9xg6PhnsQzzpuIf03RhDyvCvMQfeHgyT0M9W5VljsdVZbPU3BYY3lnYpUlVo3885qys8Ox1ssMztmd84Xl5xonN9b2UD53rC5zHHC+Z4TcYNQfENdmFPNlqdbZhlm13oSnm+GeCLrHac7x93WD6pynHSUdBqLf4Qtik5QaP2yTVNpxwUMkyyQqMCMtbYUAFXj6dlXhGU2SYvJrPnmLyQpFss7JINArNaZ1i0IWeguldLLC7OIxtlgdMygrPTk/xYssU2yrFxvmrv/orDqzAAzDF2zRZh2SdVhnXYZrOkoYP5Ivn6LAqOIAtxr3I8nWos2KGid1yFvISr4QJPMEyNRhYU+vrWDGOfpVhyvVSYY7xLJJ1xgXFjFb4zZavGNJdinNQssM6TWoeAky0JqjGRpvlzZzTti3LE2yPBfd2hY5q9pEmmNYZdjCGVvAHa87zJk9meueUG25Z4nBhOpdYjQ1GZXtvoaU5Q284LknQnlqW7KhzFBJOXo3ZwAjydIEpK/XsOpvh7WqOG9t0xaNcNOspHjcr1xtbLnSJZSnUdZ7gs8flqghHR0cBP8FhzqfNOmz5/RRfX5blnK+G8eR5ecb+qzTHNOCFlnwhvMsOf8+z7RY7ZZouMWPzrN5ipbj/cUSwdc+SYotNUHIKM6zaKsUPuRGwZTHfODsFNg5XK02WTcotiN2tA9RgUWYCjuKEm6kO3SPMwJJntVinBT+zwvtWmmgMqF4TMJZpoffcspfjpuBOwVzmWcHjqx2OKeNTl/gNNke62aaaKQyz4dLnWE98LNEGAp6gu3ZPYwSdkACLjhuOPm+mGC1GcpwUTYI5LGfbko/iqibNkkiQbCrs9B33YacbFkAmPKSL/x2NMQn4QM0jsE7jYmHDLFP+doLX137YNNMcq4sJqbmYWG2clgUOHYa+1W7E2MJs1XAizp2bYYXPb4naODTYkaf25KoETvM4Y7bLWcITM09n9jsMqIezwG22ZdcjPGYZ6l2NicHCcEZONaZhnCOeWLwtvtfXbGFKedaENDPMR4NfUl4Ipss5kCEncBY6WfwFTt0Sm5sAx7fBsV1iD51SWmS5DlWeVBjQptw0ub1gRZjRUZpjHXlCVjj3fP9qK7jD9it5+jsDDIyzSljujDnKAY/MacbdVG7UB8ZVZdushuTZEFUxllU4YcdrvOtcc5RLbmDSgazzipOeTist85TvfLbaBeyGeQnZVaT4zqZKucexHcqKILvIuGWqMuExqHGc8zh7c2z0dXKM780zfO8UaMXZx7RUc+CkbZEhZC+3ISazECzrLPFvQIBz5zZ4FUAmN0iFdcw46DXRjDDFt+UCZ4sF0EMnJSV4Yt7nFLF1mi/wNpgF23c1JvpM0FNupzxEeXIWTktOGE+5pBneEeCHHXRC6b8tMQ29IwptThr2xiBgyDj2WIYa314bmGFZIMMrCPwNIEzqQkGczzcAmWXOBQBipNhjlDSUVQKvWhBTE+4qydaEgocQ2Md52NqZgLYxNwTBWObZaVZznySzqqxrzA5XvweBs8WrC/MWmAocERxryiPuU0r67DwmcM4ZHwWCNaRBC+4pUIM7tjvgWmIpKHaTNfd6vUlnxGBs4hxIkMxmWHPOBB9L+FklmGJMS18nETsiW2o7LKnlQApyboHV/EpaaFfkFPiLBl1wS3I5CR9xJMRZfHGZmaisOM0CYCx/g6WFAChSvDbOE34DmFhTLAKiIFjWJtCwyzg/Oc9Ol6iPqcOczzE3ebkRoGIKcG7wQ1MPsiycrCkT8UQIDOh3WvYkP+McQZgSjeoG8gk7PxUQJ7n0lnmGTYkPa3lmGTcUVrELnMZaV8L0JZQ5nntomRrSuXMXTJUq+CmuOQC/j44pOzCHMwJ5h3rQ1taSXW82HC30kG0FTWqRUbrU24aHkOLiqBfSeTMzAIGkqDIhxZRKqAQA1QP8SHuVi8lVDNOMsC9xlXNyqC/Yx9lRVjSUgFyNY+3Rc+d6nNxsS2SA6ErarVkQtdJ4fhcpHjQv8fltRnl5BvjhzrQHL3gCqLtl0HYWCecNx78uZ5mNfcVjkOTYbXPC7lGX6l0CZErWG/y+XmWbsGrW0rlrCizoCkdUOBOsL1Ffy7vi0cZEAWmTKoNeA8gqMT/qotsJnQk1sEoyoMMNp6FhKYM0vLKQTsc3XvAspPHEVeVO6l4/Pi6da1755QSqwCyh8MerpNiPVbrkVwiVHFGVzLMSyiZGM5ckEfRLLG7LLZ56kqaGFEJ86ljoY1lhlvAlYLihzJqnU0eSMpqTg3fEZzgM7NpSIx8CgrBKGYF9mZYUL1Eq1NJ6sO8okrRDRjiIlR6N1eT2hjYnbDjNpPHigcfAM/yo2ZRUyqFcZGtuRuo7Wrcce4hH3xYwzSIcSpKfh1awwUxTaJRQnfmJpZ25nCpwVUJazgm1mOW4PD1IHe6CRZVQyq2ohfAEY3KBr3hLSkO+4YwwUbF77AQ+DBBFFVhn7JRzMqd1ETUoilD8vZSeNMaRWlNtwCQfo2Ps/IIHWFIH0CGEwZzTMCBYSTPUhA0g4pvUdFfpTib9AI1YGqD31qDOTljdKvTcoRDYk8kE27TOlkQuHbxKx0crgJkpeagpuBOpmtDsOBFpUwEoKfWbrQ4rHjGrsillZiU7raRmT5Q0haJYNhSz3bH08tAdardTbpcLvJlpeDltHQAvMBzDxrmmAoC/YykL/AB6MMytLbWXlJsqw3AqPX+aU2HGhFL+0uDg0Gvs+kJIv4MNLK3JDjy2BdCy/l5Dk7g7wnrQRMHuSkscilkaZyrVhgDUwFw95QphohIqqVwjClSs+4YfxxyOKTBSqPBAhQLvuc7m8zyVLND+P5JqE7an3HNa+gSTcpLKMgAQCRy13yhWCbuUeDirSZPzhGV1NCShdAMHV7XpXlSP0kUEOhrLyTzh4TQ9JGmNBuxPTCaQbV3OOTPTypTtiso+NDlTWCH02AWkBV4IhzCncsXhQaTIBIIGtU5q/naIUwLVZSuZAtVNlhaWDQOlfN7SJE7TE6lmUY3injRoxscoxPCnjiVULjo8qKAF4VJ6HsDKg4/thbde4/0xq0BwzKYEQVNRr8L2poko6VRz/214CJdUPWi71WFwxJFgMRZEwi63eSINro6qrZTv8V49wANNuO+4K6cAn10roDnqtG5yKj961wUWrNDJwL7DiqQ7qgJ6+3UWeJoMiOfSzqMaa5PZqCdYQTgjtFRoGVIBha1dc6kbGrg4E9vsFEciviwGAiw+IdRi+gc0HzLObFPb44ja2vNpuhYmSCFJN1mNFQ88lslcKyFIFSxQEKALzBlmt+JRw67Av5JTrI99DBPWekhoTUi9SvkkQ03gKI+BFORdrnPQl3qOnqX2EFC2VZRxFDt4QYLGGSHAppCCn6ozHyKXTC0dgmqvLCocKWJptuXQyhUnskhrw02zEDSpXFKgyNRG0T2gCLbQbpNyx8MixV4RekG4nXCNZxzRgks4T+kqq2kV4fhIdBA6eH6pKmAP4VdQtmpNFvaT/DhbbtxKCn2aY1B5SZuwoo5aNRgOeq8EByvKCjzZvram4yihk0sbZk6Xl7xY0GG+12SzE248KXGplrsXlg01HL08cfss9KgiCEjWSTtiHuCUeN+cRPUUc0kQ5ZMx8zsNtH9kjhBq73STYBpO5bgxZK/NVVdIFkpLW1FnmZY7U5wpW01cUBGrqBlgW9QNFRMcUZMLAbKCQuA42SRarVVa4N3wKh2ORV4BzKRsBdhRW2krOcVgYnsll0VUpFu5kM4oYGDFEbyJ8HosnwYTqOSxx5imaZ5hJ0T8xWZqERPTtuLsLvn4Wp5MvJ2UtnPnThLtNhoTySyZpzCVoINvzQ1FLZsSiY4L/I/+2dMyp213km62ZiSbtxH/h1V8Ar2FewR6qGlDOT2HgBaDBWoUFAKS/XXULBbY/DlF1DK5QCcJlqZoZSLQNyeC0BVi6ovMO9qiORXnFR1tmDBDgBk0Rsx/kVbLnXA+N78a363OLtDCxSJBcZlVyWIrz1SecoNFIwcQmkAozZLNlpYsVohGNE/xKc3xuj0BQELCMVX1KpsvpXbQ8daZjCfRtqKbjrNNCa/pWevY19qe0gDpc6vp5gPyxfnI6eXdyMuCc2IAg99QAc5lYG/T2aoo8xKvR7Fsmvs8upsgYBI9aAppBv2I8pMLCaRLYdDJMZDY/qYuNC/XXJAd9VYaxpx62ge0GahICkJzdnHMfbyQ7p5kfGq21VghWXaQeE1qG6jk+0OD45cJafGIQfuHJWXOnJoOb3TGg2XO2YRoeib/HHdHSnFquxnfS6N+QaFpkp3LTwuBsGjmJcUClSEZNNKDMKjZCn1u+WG9sFygWDiaxVhOKu7mpk4419QkhQBz86GcyjKBGM64/Fh7OlFx9KslBnLB1Gmqg5SIJb395gLgJtsIDwH5cnsAUL7XUE3DTm8qDlfOPB6Y2nTCJOqva4ku+SQzalYrbh2oaHIQrBn4OItHiK6GFZV3GeiltsAMukJC5RU6k0wPnLlKDqXCvJzQxLg2I8BUpZ1N/VybHQJuayIiWZiHG4tazG1j8WhVW4NYSbhVeUYtI5E6JhFKEUNQG9P1QlcCNUwOHstvbsM4s+ZZjMiWTSttPDOUaRVQe6Is1oaEmOLU5twipxk90MkpOonOZUVUKOQ4PYUJ4UJ92isQXTNzklN5BVyu6E+Wh54gouO1TqS5JAvsYhwGSsWUM0jPB1/enLwMPJ0kVFTmNAW5Z+qGNgK9OcfllC8+4KK2ZieMtFrepVz2trl4hT7NbGaiP6XKKV++Zpogwh/yo/SV5nxmn3okAzQ407ODT1KLy4FXPC7LBrpaKcO3oVgEaMk/uaVnADgnH2W7nfOdwhSY+rWCFfI9UT2Dhtpa4XQbQ4xqg9NAw6bmXtlqzvXOnEOqmtQEc81v1bp7BKTtay4aGs6MnZzXCZNg38ldUBT2ikd6xSy6tRk74X6UvpETMrHFq/I89gPs/B3U2KNQcMudmsoWj1Ztqz/TK8vmqkPGoXGOZOjT8sxyLlcC+wbraYYBfwyJnR5eWC5GiC2cXWjYMw6xJ6GpQ0cfO05vPS32mh8fsUkFsZj+NKqD6FVKtXkouf0JgjURbs3zU0r+wWg7Wd98jbgAs4VbHu9UVhF4qeLMkmXJfTI3i9aGiO+d0RfBgdawzqQZjbtaWUZKTyja9IQNNZBK7g46bLK1lCJNZc4fyH6S9iQdiB5DxUzmaRRIwma6aU8Z56G6SU0hw/bCSSTS0umRJmbB19T7+YGqRM9cjln6HddQLQc7A07y4kmjrM11k0LZi/tKuEiLzgycXHpEjKbQLjF3UGIHSYdf2jy/BgSmtaQTBTjEShN61noW/i1DLz0PFNZOIUTSMtgpvrqzCI86lVMDI+JWlv8eY+5MRhMs8iaVwaFRU7MkEC7MXUNX5yzbAEcx42crc4qb0s9XKOUEB9wA6/EeGx4qzpCpt3Hv8anJRq4kmxmsbEcx2FwON3oMpajQzzxvCMFaqCjZTEGopTspLpXIx82Tfn5GTc1UvLmOaiMHZrY0x6mFN6QMomsKcwBhtqAwYOAFE4UvmhINDRLwx60pMYqJx+TQ25VQlaCKXBl4Uldap+ezWSkzMk/Xiszt7Ym0khLd4kYeY0KG5QXfDnobpfCcURf2MoQsgxaCv9FHVCkyp1DsXBIsxpVtA1AdONEQaWKfyRaBImTWM9Vc+b40mGMg6WYFvaeRscf3ry2aGYcHkS8HTL2VzSiPMzEVJ5Ea1poG8pSbGpb91vTdDaW4aWImPrHVztPFKI0Ab9CXnpDNhBRUZBX3iCc71RTSOpPlgQWH+j2vTN2gHLYtgk6njAPRD45DrpkZ6PigN6qkMCktuCaX3I5eCjlY5KHgB+cZ7Mop48np+UCDIZchyQCSXN3L1DzsOnR1reWjaxHvrnUfhWaz0UaHVa7wLH54xDAJoIXOt0JrLNclj5z0dIaqGix/KWOpZj/YRUUpw5wjPLVQmjnM5QigYrFtbRv6EqpqF3fOefwYuJ5R3pxmMwsORK+1oEE+lM5kOObYepI/DCmlFaQld+hW4rPWcesPoBXi1NMmYsgRKmWeNIX8rof1IiOA2qacsltBV91M5asEhl9IhaZkKpAUQU5FykFhIJlMPpIDGrwsyRtniSmsAIp6G/1tpjFAp6SOt5Prp5Z+t8dTvkmHxzZbmgedm+8CdDKF3BUQ6FLwUwxwCbgNtxA+eHqhWF10fVP4yweYp0uGyKBJiTmStQfLfs1gZxXDE5ghyuNKR1c2JoEdc0w5A7W/kPnfQNtfJKY0au8UNQ3Z4dFeKCbUAIYTRXOkHHFPylci/3drZfG4VRbvr/jjZG5OwKqVhhXOC9TDNDcVALPJoyrBgS5K0Q1yac7mUabbngenhplhUcYUOtWykSGX7krJDgaPSm3U9TosLP5mfq/WTUMBhk+lgPUZgyaFGdkEENnDVYwo1S321SZYqCkBms5a/VMf5HoOR1hFUkAEsXXrAl0xOrbgOk7L89JnhCkK3FLSHMviy0NvgBMvnw7RX4JahyaTwi6n05baSyUrqnXd1FH+kHQyg5AVvwj/MI1ILnQa/vWmsj15TC4DlRR5jqkVyMm1JitJFJVaFgO+wnUvGe3lwVfQi749yiQ6fYjnVUOsKWGrDwf0scKIToSRem8aLVMe8WIpd1mtYEv0SXMGsizT4eHJq6FAmCN0lsqkm5cKLjHWo+gKdyAFAmdHfuANXbrHJUMIM4o5qRLrDakAcoKtyxl3GFS3LJ2ZUaKTm2DYlUwfhQDIpjFBUovqIQGKtezzf0N5szKLVa3NUX9B6hpeGCZGUe9yqLLYvPJzRy+DVJA8ydZyBJKxdVxS89qsdiaQqGWW3Gs8+AvzOENBorVKbwtfps7MlVQ3UiZKTvlpYtw0kcBizDISrRr5NCrFyCy8mkqvk+xJuEo4c+iyltayjUH6Gb4mNgNjQScxDGOGPv3X+EsS3dB4dWjdDKBmC4gFO0Cy0il/V6HXDQc8ovQS/DPGpfFIP5ZnnhMJbYJ+KB1dWBbau/jpCTa1qAJUkahntLYKkOLUhP7GggkVRZN5JYOeAtMEL3dCeTonS4K+5TbGGioLGEF5UzSoMaLCHLi7lf8mjcQ2OXW29IvWgou953IPYFz3oxYj5aCdEQd4DCRNsIOqstzwHYuSeHvC2RPHq1X3asBBMTeTrcVKKDl1Tp84JD2lDBVSYnA0uWujgUjpm9N0YoDsOD3jIplewThGv48DtiBrkFoDqYniKmD7bYxdoI27rIyBtZEUWybk8sljCCFsULZMLhBDOAsbGS5Yhi3FqDkxVvJzYHc2bTB8h5nHChXyF5mw2UfEqcScjwo+nVAEh8pCZAzLrSW2hYbEM2Ai4DnbyEcr5gvQOKFfdKsoQIXFJblujcfS7Y4TlSUFiZAnJZ0L9DkVpIVS8SBzTgHzGJqmDpqsAU9VEm3ITNBCE75WEJYuYPEBs1K6s2gv1BaI1fLVc/17FOZVJh2Fh0B7V5ATGVS1onHQ9CQSutKrqPNl9hO5vEw+VIzHCXpCfSL/HfQ/7ZpC84F1JNkxlx54kuVl3J44feIWmUkmlYZbEXpFEwU53wJvh3+b4M+iH/Q0tTBgHSGYcEtVbEHZREcnmTPmwapJRolGHVRPY1bUCawqs4+ie7SO594YPkVhhox5HqjRTElbkjQ+ZrSkXjHIlq0pSbJigZ3Mb54xoCTzihoWtMrK4oc0vKvouyelk9Jsmql7rOpaltTOhFVUKejD6ncV6MF2EJEvqs5b+vs5B1NRWak7b3g+ZwT+yJioZf1AJNJRuoEGOT6S36eSYkI0TtNI36hlD1BEiqqx1d7oWGCoEeKvCuqjjAiaQXhcmTszlPkOGuCsJvWXm4rs18ymbMpNjFdfy2N6Fo2H01Las7FSGIakKlnhnYqErpltVLRksuXllBGEnIF/7A9yoRj2qy3cT0zFrqg24sKk9rZA5nlDDXLeYD4ScWeXCbDsjGBMUDEZLDWV4U8tB8CL5l6WQrUvEjmeKzmigcmJnE5Yk/PiOsD0yuXKEHozwiNKAKW5WVcLqExYhR5DjCIDy/dKaV7KwbhJ5Pjs9yjF5XJjKPskowLDLTul6ui0ylPRtw129nE7bh7FRbCpClH4RMaoFCYngg6GkewoPikdMElUgIq4p82w5MFraDoNxsCUZm3UXi2UbBdMAEOXtalg/NxE0NJIHVvAFDG9l+hpjk/OSjZjHEQuQtkQsN0vmK+24jHdkC0Rg4+Z+SOAdPKfpudjoL7leNRyzNViW2q+Z0aRmRkNB2IDVscFzBqwaEm3OgeTw5zDi8zo78NUkyAlMkSdkivBw79gAAe/OopxDbkPNzmN0TnFIH415kGx2Cg2grm3trn5aMlbIv2GbscFA4c1JRSnZwQRXZNmYbxOY7KcKpIkTYiczjrq6TWnkqpuZSR2qbQkBxhjsiaDTQzhmrSpNO4nbqKczi4zSIgHmAV8CPKa3ONFLje+sU4q04PpNORM9iaB1EWiHAG7AQYuBSs7ATkdS/1h60OnSSWCYRpdn8leveSb16GppuKX2o47ikwCRs6pqog9SSuY9L2dpDXWaJMo7Er97Zgh2l1LqwH4z09tRivMZZKL0koK9+SI8JqI0bihM4z+OePmkWy1Db2egs0GamLcMQAqa4hiHGpvSZUmMcLXtJHPoQ0GmPOWS5yLrE+7lM5+Odmw8bK6IsdhKVfWcbbm/oDyPy2nUXMk9m7DyLxhe7/1wddo1jdAQo6CJpe3cGO2rjx2Cvrk8jfp5NXYh7LcZfXSItjKn5NRJeOitF7mWg5inUrSe3kCGu7XNiAsOsO61HeK5FTsKzmEpPobCpzBAN5IIZM7tth7fHhIMNh6NyeJAvoVY0o4WFNCAmZTMYze0RF77xJ/KsWnKD1IoxQ3T5F2LDhZlJP+SML5jEITCh40mDOmDqxN+6/ND8jp4+hyU8Oings5X0QfDNWieaYoUVpjdtJ9UKBWf9h2isAkewN8Z4EFfiSGNNM1n85JUhiRILxupKP1hvKItnoWlFVFT4B8TMSxd5lhMaazsDUP7lk6FcmMTrg5PX6CMRota1MiLKQ2JbRWzXLK0ZxSfbKxyBciIwlbdjo1FY/gSNs0I7ttS6IELa2cWDagKTfoQRBJ7VDYgV5eUX3n4q8zlCsPsORWuco4oTATlsJl4gLHPTfqON3rUlS2u713meTAaqvUG6hwECGZQt8Mr1HAzRRaFNmU4doipe9bNE8dN9O/peKQyCWr3oyx2rIHWloatTv5VgW4dbNk1J4xNgt/GOexisSldCO7YBLqM0arFHOW+alAPlU8Ht9eH7+hJJD6aXhAxI9znUiXrGnyGWWe6LtOzjM6T4YBxKmUZ4vCR7uvilYDkc1CxLKqkyLJdzySUvVqI09y+9FArxWuV1AeCsNa1IxNgynm+dy2Uds2mE1hIe/hVHQb5mGUDNsRmCkKaajR1KIplEgskMYh3rL0fQgcGm90CZBTQ0/XjIol7R6ys2UjJaICDDrclFuxr4mc5Googlfqk7WcqqKQkEwgUhUt+20kzJHUnVu04kISzSjhm9z5FE6mm5yliTQ4CwpjF2vLGTeaGoYYXXiRckY92mIWey5iTaUOb2+IgNlN8TnRreZGE+a0fY+Bj1xLhD4ktyOtMI5HuN9Q+zpOLlygaS+jgSk6jPZLQubaSlj/ggcDqNPU4rRlS8UPuctt+ep25VvmVm0rZ55VCxdT85hmLQtAaTB1GNKtrvSmWRVZtjDeFSGgmkhnHx26S9Hv0lYfhdIt3qstHE0iHPGtBaQidTbPFlsZM8bzwjAKc1RVlgwDEODwciqb22RHj0KNvZOYVKasTZjWxODxKrFY10zDopHGfnfiZIi3T6tmIRMVxmEinqi535J5jAbTmQgEl3qpGD8UjPiLXcxV2FLHA4ToPXBYZStdoFaD5c8M3SHXwtI4Z0z7wHnpjZkqw428Nr6yxMq8lPg0QgWZjyQi5cajFmchUYpeVkm241TT2KfCA2nbAKIt604zayuZ1jGmFyNfi8Xe41Ib88to9DQBsTnmDPRmgqHEHASznO7omnRnSnrsf3pV1AU1iUVOGF+ZcwbijnEQamPj0Bsdol1yslcWLmN0Pobo8LkhjTqKqZOMYyDkiXEgcOiMxY+j8bxWNI6EQwxOXCPSxrgn8wTw21d+g2VByC3NyGdaK4EzMq05NbVBP99c+G3hEp1nsullsAHuST0wRZObMpxYRCtiLn8xGgQqYxnFGTXVeVbL8USeqRKAILtaeiBTo6g6YqzNPumsJsWfPqSypJMrLZRQiaOWkaN2hgdwBGUmJyHdGkH0Jrwed5IFrmsSMc4sXaciy0PEJLE40pV8DdhqJJazHwho5dfNzWme71ooVWqubApuAoUEjHFjNEK67ArpcZAg0F6hJ0VrCwcsGuxmbta297eaBEVM0oUjQ1kockpzf0XdRlFtjJYxF+Nimk0f3UF9i2pRQS/Py6QxN5sFvrC3YBJmRrXNzN4yZ5f0BAL9wakuwqMSFac2dnqqdCoVApcxo61lAX/on2sjW6TGMiHBBRZ8WYl91OZMYWBMVpA131DZTdaFuZOZC6UBydNWZ+cptbdKnoRwYbYlt90+j0sJUMSFM4b/qYMz3s7wMedM6r6cQ8mFjMugXOB6k+HtzYFG5jzDSPOQbmet1+IQeDI7m/R7iBi+KmypxpIc+L6K+UIZOk0sZqZ4OB2xpei5OCwKETCSvje3jOtPx8dpi/7iYkIAUbbJo4Qt2/C00PlHjmpTKKF6s8pygEyOPxMhDga0JJthJrasJ32RHFwuQr8rT24q1omSMI1khfOwbCKLDYCZVdzwi/I8TivTaKdYrQuKkFPxP7+xOa7T84x2Uy0nl1vpFDl3KSdUZ2NKesmCSRvJyrzRWoaY+jKPREaJJB2Dysgv5p7ExhwY9GC2qYZavBE61XFKvupMikhamAOsC7sq5olsdWa0e8i1IEziCXKu1hoUMztrUa4o9mRDQ7WOmAioWNoBkyibUaxVkRCraKotKVVNOmLaFBRhuoUXlxUMoWPRpGBH16TA7EJ/TJV0bnZvmZHbQHOhKTjTa2rGwodTCV3TgiHeN9LZ2sAlNTaCSxOjdscZJ+lI/uwLQL3Ii6iValN7A0KEgILeKnOhbk1DYkSgZR/bwV60a5TI0tZbczuWpxgwaYnRNUdHD0+kJcopysLosxE+FWeWpcUPWW4N1GwG4Zl8mbSs/BibNCPbHbA60oijD1+ez1SUUJJRVwz8p5IEplhxzgxngcJ43s6yX5QJLYb6HDqLZgE7pWiMowVJADRfKl2kpo5J1TLJY76yVNcNJd4yDlLSW3huipdWhtzpNUGXO7AzEdVB2Y76UFJh1+NEz06UasxEzfrAHIPmPJdw72FmV9nUfrilPNnSjc9zlpuSI500RoIqbNJjpggn+8y0PYXnkK/HEDJ04U0mvOGpsKAu370QgVRpz2Vk5ktTpKzga/Rp6mRr5sLY4SOjxRypQfmEcVEtj4v/5szCepwqGMcoHJnNRBwF+VKbDtrxBTcbVANxdptClBApVjmthLPMErEUcra86512jNL28WBziQvmMG99mr6qL5DvKoImQ3D8yGCw92wQRZiXySIMjOjFyD7RQAKZTJHK3Pt7ABCbDcZCEpNUxAu0NBh2l6j0g8LyubHMdTBS034LpcKc0sjsd2KcrbZECohE21k1M0+m5RlEft7U5nUg8cvyJYrI49vRQS1km4isR59aDOGIrSsiYV37dIe6TTVkMRGl80cPbOs+bR2KimNHjo2sg1RZwGl9YqT+GM+s2mSgrVE1UmkQNAQ2Shmnkc+HMuZxllo20CJq/RZcpaoYg7bGUSMPCmPK91nIbZgDi76OqV8MnGC7cnWmTbU0wy0yrKbK5a+4XepDEGHvBBJnVOk2Wa3k6/R8JFPWIihHxrkl/bN+iCnVkoXG9aB2kJovFVM/DuV0a4dQ7yCtX8UR1tl5aZgKs7ZZD9mJNCYTkpWtjuhNPRLNtnL/GHhHDoxiXhmzTKQtSBESokVucMbU5bRVQWndTBnBj2tuQTdWu6Ceau7cGVQb7FmlLgHC5FUyjoDQiuUFuH34poUUiLIuNytSrLbpspR/l0ygpCiSPeObGuRI4otFY0qmv1d76kJCrq7c+SfL6G9WmjOJ2Qw4kNrJ14kGOVn3KzpyLJgVUVuRRWwRVoWZzUSdrsX1JY88LNaBhoUoVIOuhYpnaVtdIhcvlppJvxedIsSUpV69iuMXC+hMDhBAiyU+RFbN2qIYKiNQt4GoRFnxVo9DuhOJMFW2Vho6RWnOQh1n4nNJ1pkB1mknuxbJQybskl+ZsjoBQzInjvixH4ESahjOCf1Ja3mRy5Ni70nqZ8qtE7MHFj5FihlXlpvJBPhz5+q6zeXmTEtxKxS75ocsRw4Hkjk+TDTB5h6psoGKOdC4kBoExGHqrLLPkrmpzxseFKqyPAXmCzeXcDqVEQp5Jf9twYJEonpn0DzMKNjGxxNHI2W8FmfBcsktR41ySWaCyFuRvsFTcib6RZIrVTHGfOtIilLKIJVsI5Iq31UEKAK7OHpLPpHsSIqLblccmbSweDvj5zsBH91iMk+jI6U/bFdgFjXn7/wTO6XMowG2MSBON9EzUinFiDbPMtp9JxKE6L0vH5kKFijIWxbKZU7kTpKjfSVfkjzUKieUb1sCuUWdjYesX+3ZooY++GujOAaMW2xIiLoFc60ELvR8BPGrmFhKIrC+WIcBTUKRpJT+oswic61HEm8kV9vWlojjqaf6GusJ8ZAxxnvGEejVFPxRfhX12/UmV5wpGhzY93IkdgdG2CTnWxUMjGeiJaiswNCS+RXRIcmAUS2WsxQr0UyMHdkGthSJtpiqkS1ykZSLVQKdSi4SUZyMlFFT9BWJZmnQYemZVNPA/aQIfW0u7JihaEWpSuNILmQwQeMR/cF0iy7DRGnSBIUY8HZDpSXku0NBEy5vTo+TSRp+iFl0Cfcgvmg8TQvDmbsMKEimMC1lQdg2s8gb0eiEbot9RmU07EgUFK29VoEKk7TUzE5w1JVhonpcG0rtZkuIIp9yhwnVcZE+aPnxZkVH3lm2pyOKpStlIAYFlFU9V2rlPJhqKcq0kQ2onionldzrSO5SXEKpiNkpazixNyw85DeJ4jMsB1091PxnVgYG09QLcT+dmcYu+GTpM9EelWjKHJhc1hSM0sg97wwozcgKXdFhTu4/o845rdEiqq9GfTWFQ4bC3gMlKqMCptJB8LihsgNI+9moVlLFjPzixFIQlDaRGPn1LN3uE2qMKAS9qpRfJ1ERJUjCjdHlpMcrAEllgk5FnQqS6c4rJA4cPsVBIirM6Q2n0qqCZkqmZMZMKjpfvg+u123iNc+ICA3RzLJj1DmiY4mR7lWmdFuZJZgkQFFp/P1aw6F3gbBPL4CO7BhQYb5yQoFsQvqhI4WTwFDvKy3oh+kummXbdN7mp2bKijMv9Cq6/alhqxxRDSNlaacjUdjHVBq5maXu55h6GF2nKeMwFJZngf68VFtXOktjKSpbcyFlljRtdZuo8IgH27L4oXewZJ6CDHUsurDMLPmABRw6zDwnr7RmCNnI9ORUYoQKt68ysqAZL87mMYHTsgf0UqynV9ALLZ6lsR+YlpvO545HI90GI1NqYB5qMvnWFn3eaaEyxZ/EiYjZOXWktzNHBO+mTukehbS2kmp2cOQRnKv0iOTiWcp3k2OMjKkVqXcKR2hS2mIixPLDP63wXtLIjVpbxGIeI+/yEwJwK4txnlWJqF607ywRTDTsDXf7nghlwCanL2Z9paRcjEThBinsqzbHLp3v3fOUO21FmIjvVDPqullbutpatqllRdGtCm1KqjV9EPrCMcwdKe4NA2rcVjjXW5E3UqtotVIhLelhpvKIWiA/g5XKOuFyK+xNzqfqwwRofy2Rpj7kyqiUQWrB0injZAWUOGWymDcAn6EjiJ5Zb9LU5Cbb4VEaS9HScGS6Y/dPy2oldm/0geAcpmsDtnl9IJTNlcpOxVlOua3YRfOU7B9+ivbqCSAyERlzqaSguaIozNtPYZJxVgBGsm5g6UmtSozfQbHHEmRMv9+1iZjKFlHmowLRUoA7vcgHasW/pfXQAm1abq/FrKIzZ1tHNohVAWmMTqo4tgSgkXhxEkvmNsf6JrJbss1GqV3GkgiDPhe+MiOhM1EEQ5AVRPGsVcBAiWWZ5uPg+IDVw5JWh/Q/vBjzRApRvll/LZlJ+LFUSqt1rRuInbVZyxbcsIoEQH4rBtkoeqBUTUUla2gRsbJYnpyx9JQ5a2L1tQSyOs9NxjOaR7p3owKgc/qDMuUfK5gkohYOTjIv4zy0gX9xMhnEwfsqF2WIWSBq6h9Qt+oQfYFkKadhMIT+cyJabS1jBz03VuIj32o1O8ClTJ5KnCemMvYA/6s8pTDKy+bgEVH4SHQZoA+Tfvbk2FiCiYp8HeNdwv1kX/JnpsKFZKJjQk3VipYMQwyGLEvVCWqYgqes6NQoJCLDr4qC+QQVNRmrGlBHckrNgNoy6uQW20/WtIBqcr7EmRGfOWdqPyUf1L00N0c1SSrG2bUs/IR516Ie0P5gxGmbigsbNeQ5NRX8FJ/dxtxA+R/Pt65Lue1Y8YPbMUbRrO5gaqxHqtIi5DcCs43F3KDjbChl9upYKnYMd0FCHsA26h8SyGY6WHUQismU/1vX4sQqY1pke3qfUtaeKyvZRLUd4Ux6iJ5sgQfFD1q6HvXcyKw/SSMJwdZW2xuntCKFNZcr5zhbr1W8iKkLXOdY2oNHBTugOgTXY3JuVHwlj5V7sM+pa7MltU9oFLSZOCxDQmonIIEK8WliBeyqZSMvvWW24FHkI5EqKNtrudsoBl8WLq1NAcaVZYk2MnShxGSkB8a6UrXRZrG9zrLtBfOliknOdZYjhjq4ERkoBHhiGbYxN1skSkytlJnIGhIO3BbMOVJYQQR3xRBM48WylazkIaCMVWI5fyptZawEozZuRNuNRAgdJIrypopFqvhSrEBEaU2SiT0pkcP6aMwCAlJd8IxoVVLSKIUKkLArILp3VgfA6szt5bGlW8gnQnJLZCZTqpg3hZAyk5JuYZ+0Nb/kQaszq8aA5coulIYFOj8KkFJVXBhR3hjhihqyLES+DjlsAKqwc03trFF1IAxkMmiz1usD9YuyVSYJ981SW30oVaOJcJSe8DQMJnisaNF4sYWtELSVNTl3maVjJPKbaqvUWytMy9JJJi2sfgI2Ry3SSr4TNZ6JVso/xksVhwQKCxNTQxfPlSFXE6IbVRzla5OPhyXSjLfZi8z3bJhKR589VVXxicxqZh0e5eQJ+0wf2uc/tFa85OpqF8YQCpFvIIKSed/CYGypo5kC9yrTSYTCAIm9hBQTVlAySgUvt7JvlIhJj2zaKrZZVPJUKJpEjCQMRmG2m4lUhXPG2tPcnnr3iv5Ybr9lqYp+LIwnJyNLWJ/RedoySi3H0orDkGWAk5MU7dHgLmYKHDN1UpXd2qqcEqTavlgc8WVngimPcveCSkNu8OBk2lKx9l5PaQlNFfVBdMnAmdg0M5q/MCvOE7AjnXTW+ooaq6JBrVLlhNaxoAIr2NBzmpyWCta3soMmziINp7XiavNYEaSOWagqFTBNZ4EHa+/pzts8FKl1lXS3mPvmqhKKbaPiJHFh9/lFss+MXhTTQGPe01xxKlJ+RJyjDNvXUJpHJJZrny99osPGtIOzQ3hAFaKkuqxKSYRFomRY04GLefTPUQ0mRzNfRx2VIf82o16luKxizglTnlaHxFjlR2tBKC/FTawtuhLz4+kwXqVM5KtPVMiLG6f+3j4GSInKF6TnIZZqU1w5Y8jTqE1AxoEYs5mSIWn67RkPKgxr5TnrGGCPscdpRTbvCPBi9UusZpBKPFtysDmOmRQmrzj5r+MY1TMLD6rTiSG7kZPo/mOBsflxIjK7cm1ky7OWMIvpLXK9qQqtlSe70rtnjSZEf8e0raJhbm8itzGCjkYEsVxca6PDWbXUOWnfkfpZHGqUK2dqKbJgZY5w82PPlLqkMqzdwdE+qijr0EKmQnZ6dvc1KmqjR4szD/Ul3UZm/y4SRVTlQcUXSU8KHc6rUYcTisfjpLCyRioKSWbz0YSKPoH1uOSLGu2iUcKGWXlpEW0Oxtu3cacWVvk9T2LehDj+tIOtOsKyUs2HC4y+xfIYph9VNg9JzIg2urvKmQj+Iq+nLapI3gYZyjGiumh9ydBnlZ99EvUfM7sZHFPWJKTahCkMK6V6zGW4JdJ8HNtPikwMgxnbl86MxdZK1slyHA8EjDvV7lJMBbZzIqIJZYqI02adWRaeztFG0UgGuVheP21teCuWqmy+2jwuxoKvY8kflixjipHR4TOYNcVWIpsanJWIboptW3ssVulO1+skMo2kSyx0ZpZyRFCFJcxUjVJvaD1V0f9uldMbzjOEWxaLwO4TNFMrn2bvRecIcAinGcbBcXRMx6z1WvXcKIUJjiSCb8kahnXMKZtmTBjZSUjgh9xos7a6wlxeDauSXivNxHqLPKzgfcDQ12TrKTqWKSM4Mr0YarUK1KL4s2oVlCJdaaDcHqitXIuUoXwlVRO/y5N94WLzUxFh0qKl4J5ZQUYz65jOKYbubJ/UJK9ZWZkTf26iTTS6bF/+KjCoT6c434QKGbZ/YK045VEyPn+oJ6NMbFHfDqFusw2Suv1AzMGqpajVJgn1vprFSmSIo2j6MZLTau0r5VWxdgNd7kd96WBVRHO6GzKrv2Mp4ox4QNFhnaym3iknmsb9MmlLVCkcn9OBokKFVnZLOTqMuBvT80S145byKtLTYOoeURmigbFJI+8LDbMq+R7PFzcqXQKKFtmE8dkXqDARaY0o2hbIaKtv210ESxllCWUp00o2kQtiNKbdvmxpbd5Fq4OmOwlYR/nMoqW2mPO9cwsfPo0VkJk2TDXkJFFS3WlmpAPzx0SLmwKvDIf8M6izFhpd2L0MUNiYOKLE1EQV06aNVYCvpGmz7G69L5BXBzvMdHoqMfMCjQ8ri15bXg87gSCzzBORlnKa95vG0rhrudSYwJXkbUxmHoZDbtJTRQ/SMnSGShVqa5bwka2qKo4xgQRCktYvJWNhJR5kHWMndfm/TuvXtXzkKGB7bXF34p3KrFEUAWdTynHS62MsL6YMQO2ndFIuzrBrpapa34sqfzWbELMVxGPOFNmjz5N8tHhYTFCruCzJ8MwoIwWJsQcxxuk+ZBRBCUIZczlYATO1ylqhmCWJ1ZDXTSERx2sV9LKUDRbujBXRGvnlyDxgN2bpk4wdBRce0tAwsATLZB4jjTGCdULrFbJ2MtbFKaxtxr1hNfDkgFeCHe0IWlSjrhgeLUtdwsJCP3asWPmN+4aG21RWwoWMDzMOCwsGMBS+iTwipl7lzlVNuDpuHce0seZtvBJ/AiyOy6k4warfKDemSrSIS7gX8izvoOqprGa9R9EYCK1E+K2tEl4qWchOmS1NO0G1rDarcstYPi0scg8ODiypYuVJnrD4blt6s5Iqjp4z1fm1NyqnmQoG11K1c9HweQFtI8Viacq9FTHkQVHcP7qWGSzdplFB2BkemLxmknVr0US3wdZY0kr3pVtRRqfxrMQ734qlQOaKVGycH4agkmxPkpfYI8LOZxYaqUN86lFH+XLR65fmWcvkVwwpNWFs+axSFaAdySFD8M0jg4g+ZwbsOPv4b7Ohs2CT0cJlyLGy8oq0wc0/kNNyZMyHzL+tKtASTjXHxjRlInAjhu80EkATEU6KVGR5pgwy9XstErn6wiAYT6fu1holhmqJYtnkZmbSKHShARFxrvIsopWfiA8SkukMJhKnkuYctntBNtPKcgAsEpQ368K0VNbplmfeQi+Mm9DVvtSUWCiezmwxg0/MiactvAudLtG5sCBMHKvcaPRYKudyxpQ+MXu22FFZeZYYTdm8eTRE6Kk7bwUxCJKcVeOyQ82xan/pGTMltvQX5DzTivkq5r1gAZSdKVVy8K20rWJ01Dahbn4ScW8lk98RTZViInLStFxP4+SpUGrDcjSHrOQ0Fpo0or7i8nSSsQKnkvvLOc1Y6saK95ABWeWqWjqX1yyd8hknKlBt53/TQNkrjQON/ifDWMYlMCUGZ3UyinV7VR82l3xrU/Spz6lyp9WUNVzfUOHaGc7RhUstZbnMjWbIpOSCHgUoUWLA1VYzsY6xNF5lkpJ1paCxFTS2XGiBEhRZlaLe168jmdScZtP4PnJNqbx9qiTEepaYbR9DFgnr+VtVL0UzjXOsYit0BUPmueppufL8NptY1MlcmdHXTYqYPZG15Ejnb70FFl4UYRiveUa9tjBPR2rejJh+3MYUxBOjyd09ihnD1t+uUIkYxuMoUdHPlHUsjKhpM8zKYJacwig3lUg6nKYyQnasgkDKkAiT0BqZ86pIrxW3TyQu5lZlcxoztC1deGOFlXMzqBYNgwtlY/Y4a6Ulc9Y6LHcxIcW8eVbCz4pdKZdjjnXM5XtJTY1vlHyGkYwhNJcl13k8ppEbqxzrzK7oWlcabN0y7Kiwq4oRWczLel+isA7DDtBBoaJE60kOjbKGFKRgaah8wauD5rIQY95sztlo07bTOopssjtZtaE6pfqhLV5W0fu6rQ/kFeooZ63fkDGkhIdy1tYRN1VopYoNs3KjcmYJqZ52pQNPEVNXVcFR2nugGcSiL9R7WcBSMUOL3AJSJr3WEjlUSyE/UpEn5aeJxdH6QWPCKZAgOdlnFbDGrlX0zlX70aqa58xLmFU7aXWdnvEbVFXiDAdy1Raurk1fZZiUJLacmejC0VnUi1PRLNaqula09ZD38VS7hUMuDWOLZlksFVkbOzuJddWZSQp7kzpkHXNTsoPth7WN+ST1Pum6DiOW8C8piSyeX8WiPa1lhBej/zbJhbdTS16wAnHKqQVSsNaulI7a/Io4RpZsTh5fmqtcYAwAFy0BMwxHVK62wZR+bOeJYpYbu78vUakjo6qp5L2EtqrmM5hZTqf0Qqmy+FrcB7nQzQtWaN9DpjCKwZ+25U55wshxUE5upmCWzEL514+6Fr2iVZcEpeVz6nbrTST/MDwx7Jk7W3GP8eSorR1vXi/FlPfUDPKDp1o8SVsVMD93biEthZHwUo560fj1juK8K6E1TDo0s60k3WZjWUFRo2bPLOxJURkNgPZqGp1/1oY9Tmbl1Gg3a0Py2vCyaSttqtCwXX3ASVly3luXUrzlqBJbc85547KTRShHu2WUYK/Y1BW6ukB8PYx20oVAYZQss4u7GGVTSm4kgG+bNjXJ0fVyV5t17+lqK2Ta3WJWIlFcJ1KEKSrW5FvEqBqz1mngUM+kkVnOy/MUo221pEUbDTnjVYVFIqM5T5RZ1WyNIaLyW6pN2aGLUBcRtr7eMBrFYbOE+ZmFtk+57m3Sl5g7ViCCBfnki7MrcZQAsW4qpn7nYujNk0I3S7SZtDiSERRP0p3oc/Rp8BqBqarOp6r7DpN1rGCXMh3HLPodNXNj3G2y7bY2xfDcORiJrJVkMfQ6jDsKM1vl1CVvumLRpiJ0SN6cSluNlmdIVgpnYB7zmK+/pH9D6icj9G2dZoVTK5N/0CJ1pdHaEqRYKakKu5QnZGAGTWQw8HUZ8FlbTTggPj4yhIAzq/FUvm1MAs24uW3FtkzgXCWQ5F3g6JsNr91jRQdSF+Qos2yEVdaSWY3EpCsNREuiT/gQq6U2R517HrPB7djGKzjyZpYYz9No4VJ4lLqyynSJQS4mk3w3xvawosqzxvbbDB+YWhiEt27RIyZnpHEECpuqTH4euusyS3WuGyhyuqgvYmSUg9T9lL9NEYgJG4Vqtduu1rG4hl5bxEoVnAQUQlsPo6OjMJzohklphKWM0VHfYsFUX+22lirmdvB0sAA1PnzzlRl2fi4/RMQ3zs6kH2tntUdBJdEaSaE6saSMtZWRomeo2Iv7mIprVT0iZb4pMsW7raSG5cssbcas1hGnvamIfVhGwyRoVRh4okuVxFWSN5RMZSBzYSk0um+gtgJGdRrXO4qx7ZnZ8qNOGDPnJ6fLnBXzEroJVA8J27jgPYmZ0gdVIrA6VKGCmOrL/CxkPjAQrzIpApgYdzRXjdUKyk1V2hcWwnaT5aHCK7W0psJYgayjaMi3aS9UwSxUQkQcFiXCJcu2LDLxd5pYaX9zHETvnJScNrsRUzfqQQmjXDhueI8S1eiMihuQinKzsJ+LLq5zMo8qjgWNLkSHdy5dnaEblitIyRDQNWbE9Zo6Le8ChCSS7syUOv5vynhtMrXiZrAG5NyYM3NL/BXzjrZlulV3XbWzk3UYd3H+Mp10OTVPzowhrMU0X1RrPCllcJrE8s4Kfe3W0zK3DciMBqXyq+4e842wF5hp31b/lP3Cjo6hn6jgJEwlkW44n4cUJ+VuMXZJam3O+DnD2ooiLUqJJZMFUn+Vx8UgIr1HpzIbywsM7MwZEjD4PsliCqguzOuMxxN/20Wta2x1W3Ist0KToOVLWfUMgPI0k1+YHicxAjTDeBI0sbbygWjMY6i/CaNmhs312mJpKpfNtTY/Hu+xkytNOfBMbaVuz7w8pYSU+8J9xqTLT3gI6V1vC3zHMtbyN694cVAxjwQiKv5i1MxW+9rC9S4SEii3ePWx7sCKcXnhHm9naC9XSqspt+m+Tj2vsNDGqlVi0bIAMeLjlmuFl9gYYUQZUTFGkZg7T9qm8qjSoi2Iw5/OVQECeyyhAwinm6PDDq1UZZWB99GE5mJqXlk6aSmv8LB+qK2aWJJvVgkR9TT9TlIkFTnowSvm5iiTKOYK8C4eAcJcuTSuekGSf6cqeW0pgKS+Kxsh3jZD+pzEd0s8jQl5pTLEtJcZ15QdfWLFBsUctKv0VJdVgk8e1PEQ9kF9cELTOGurvUO/nVJn2BlflXt20Nb7r1nEQRs6VVKi3iL6aK0SeAwxKlKZbKzGicqLWNiRCdjxftQtDBhYtKN9Bm1ql6XUsTCYXbOj/IlsPTUXwjaxQhZ1a7PSdFDmXiuPmecfkxlYk0F3ObAQk0hvVjxMFzJvKdljsl2k6JgRFHnkVsm5iBd30UgTUTnNtAs65vYg/EbzTi4HJbUTRK18EIytk3zHlLy1EbBV6m3R6HaZSpqRZV/PedkDoxLK713Zhb+tX13xRotS6CqidXQ1M8ZiBaF4UVe8LAfWHukkiuhuk+xMYuOQJ22MgegwyaWWpLylmJFLVZilTqFqXIIo+X5ZepVSedxTyny9D9ARA41RGMuQQlfbJnZDtEISe5pDQkfsuqlnlmiQWEL/LFLyRE8x24bcGEbhUl3J1V4NoKyWAP2Ct14Qm4wXqOvt5HNK5AphcaYmXSRys0RzQDeZ1G1cp27ve67ttqlDlUUtcp63Y6E7SYSRpNpffVvJYqdFrIhnGS8xlvPjtK3ukjAbwWrUWilUBbVIRlnJcKNtWy1to7XzGG/+IXS2MpiHbvydeAA1/cRcukVbEbzDS2UPOfWEa1Zc02oq3cVKL6iIUGqJk/yEbmGqy7aYYW03Ke5iJiCF/04ac2qefd2oQW0vUfmIEjra+bYAwk7qpqof1Sfx5lPdspDNVtK4YTLJI6bKKCyFZQ6tYT8saQVb7qeusioLVgRggJ83h9C7SdVjKZaViEcm4YYDW6N2b9idn+IyqZSbBTdm5uaRz9sq/pCUv5T/gdMlkUVaoFVd46BUiwJnT7WWyfmOGzbYpb/RiUYCy6zJjfV1nFYNqflr3aPMDOS83MX6tqZv0J1hF0bTxNVYomaGbRCp9WvV/LaEZ2H/MqQJdQ/sgSN91eiEpjLHAlS1OE6RCF7qeiZsxOVSZbItw1BRF2j/mcpGnXJv5avMrreuKItjPVG7amBh/FcF0uy6zFRmG7+bnsaQuXy0VEh4pbhKq8H+YB1JXgVI5rQG1Mx178mSlO72/i7O8MKYqcV0Zv77/ZlR6SgK351e8HBHTVu7u6qtXDMPMiQFTOBjC/gw2mfXSubinmRWn4EJ7O31wbajdYVdvNLBoupmKGB/znU9ll53VR5KipphEe9lOG+IycCp+MCZgq1nuoSMfoJYZtAKiBg3jJr1fF+Vai8ZjX9ASIMJqMtk9SudgS1jI/wNILneUTSXYnHA9qDSaUaQuqS23pRk/5lMPzXvXzzk8boChqosk225r00AZWqqGqRjCF5Y5+v2oozKIn7tHXVT5cWumnmtJVrqUrcLJSNhDEEkRNTZqhW84q1KmEj1VwpyaozxfBHLAUI48KgCqWKG6jTWWs4zIwIoOSUhsKfLtL0pUtSh0uxJCQsgQAcWy05MD12sKpYkb6+yaNtMtOq6DeyqZnJu9xi3pc1tg4lIsuErsTYAfrtUeV5dCavoL1NxhCEzCzWVRu/cWqTjLGV6dtLQeUjlrCXW0JWYSMjofgKz0VZtOXFe5VrO+RZdih7GXaWTHEs/YdTDfHt4B/mMrXaMgvk6RtIryl3UlvGYnnRZ9I6znGP76hLYpeTLglZZo1g/8w8BdJW5zc/kJ1ZRZ3r3I4OzljVTzej2iKUQdJyXabGPSll6dobnKotMlcIty5DjpgNWsUcxTshkhD5zcNSqlFosls4MMd3JmbaVaHh7sK5VpbsT25MaKnUZOph0hOko5m1cVrFgZxZrHT0+9AvEzWhpmlom3ceifCy7TQLPHR3tb78U/Vr1nHniLjBzU2pUZN+p+FG+kQm13l+4rnwpyE0cFr2iytjQRqI2ooup27pXmWprmBd7b9y19PBYONRq9dCLZnqRqBu1vypMNWu2ohLy0m0BpK6hAc6e6HZRO7gieWj3q0B7pgrjvKDUwp57m/M03RdiIJpbhWBlLa2a0LLtGdbg3p/G6sQLXsanQsCLtjKL/kazNh53LlmfEoVIZKTgRuFfErxqq5UQ7x2vFXE3shT10ya3JdXNrlZRQ2U9dRmzRXvE06AHgdSseNv7SuZmM9Nu4dWoFpGYf4dZUVuWs2glGSEch2JrdZFiVT7hFK8O5NUlDKFu20rQdA/uGNJhMl9I492sda1UBeOAzC0asGizLO32FjGAdWG7XWxY2QxBPCl1SOxRXodm9ynXqlAWb7eercwbbjmvyXpjnWP+S+103YS1MVe4KqNY7mPTlvlLFku65FU2qSavtOKdVCpNt5UdzsidkpKqSBmrLbW+1r3Ry6Q9AbyI6MzKdorBHWumLnSxHTN7tnQoRu+mvGL0ffOaNVEu66Tl02Oi18bIjFcBzKU7r5pKFQEU8LB7TlUBEZqMKLGkDYqfwiwXmTnk5csDE68swcIrrUt1J+wSZ4VAd8fytha6sWVDxxQtqVTmaQwDb/bzpWuIyXwQT4aKHnXGmVVbSXVJCCsEUseYWsFSvK8KhtPjPy/aK49nedPmqSgyxhKTXNJc9zCIt0SHRyrOTA7LdyWCWsOqe/EeAl3tSihiOvGywbiUtQxZu24qlVuhHazoSFm0gkiu+UgyXzHiYZVhdNl2bZXDpWKVlFRkjiwkdGg0CJIZD4xxvJiT0Bh1BKvDqDUFg92KtFV1QJy8VCQX1fCaGQuJ+ar1nkQnX+eKKd9t6WNlFisbACe1axljVlhvvlaRFV2vWVuKnfyPLKsfnYVWDlXTDDCaTm0KyyYGS1qOpC5PY9UI0T4wjcWJu3/JEm5K0T6oSS90q6cseuPMsiwiBrvW2wtQq2YT+WEWZth7jwIrbxP8V7xbAFAvsh0zRQhPOfSgWM/FLgYv7AINhofaS72UZFHxkgBiaE69It1ZyKbUBcCJOBxbxj6McHBs+AH7omX1RPVWAWuVERB1l5JkbpZyHa8Xs9uoKyv6mdn9WFXK+vkUAGexLMxc3Hxe/87r/QA8TEOA6JCvZO+eikkWdG+b10ol0wWHVezPIjKnKi684SKY7y81qqoq0+btda2pCD/KNLYSMHneWAB73tYO1+VINK2Y6FKp6AurDwQZu229kyjDhOTZsZAqAtu82penZJG96INZtu4TzM2cVSLI2IkQE2vWrMSi5B0ChSplkoewXZf1RtL0tMxOWamX2umUVXAzlR7jHlDOEC++yhLLpCPEqQKEvPYxlYY6s5nQunfP6ihle40kbR2hRthTZKJM6NzRDXyptKxkQw9mKY+xygbEhPnFQomQYk+rflVblbm222pNIVAFza3dDa8SICe8QbFS1Zyy2Woj0tSQPl+lJzy6PV6LFKsgb61GEoT1hpGq0ZjOPYIg/YJ5C4tFGw+Bag8V9CyzW8KMy7cPmDCoRXc7xekKBuo0jUkpUrO5sXdyNFP2sGh+ablYVkFCyh9jzHGbsSi02RlM27c6eptyGysG6iYoFe7KYrXjtNAVr9KYt9IVO52jSP636r+VnEWsrX0mMJW7vih5GXcbl13ppjPVwlrwZmxII90sFa/4rtsCHvU+z0OsPHpzy1gxOmb/mkuqCbrBy+7vy3VnU4x6rVkby+4MUsBH/mXdgqckmBgHGB4dlFS7faWObx/Hy2viWAdpforplDZqF35Yzac61javRK3mHZly+8rP3ajaxXg0DGljur2ykmOcQeBvjtgYZAesnaoQdyztY/Q4Smq79jh6NeuWTQBrOl7h0yYmxtKj4pbx+Zs2m4iQ3xQzGVwZl12kO0UdY6GhWrmHSh/QPp6So95eQs0KLfRhbi3LG/sTACRt4hA2YuBzT0bRhVd00ELvyHh7IDbyPGuJFtA1YnKXnq2aJKy0mthN9jnzAzIz6aXzC8JUfkLH3pwGuk0r8k4scMZ6H7FeVNCVReuDK3dbWtppvUpUYaGNo+elrlKwW/Lo96rsRro17ZiZpaKSYakbznlnBq9KKOiyUFHY1G4zJA9vwQxuM2GaDeuK2cagLGI51WZqF4sJmGO5jRpI0uXl1XRkJiy4rPse20B5ZpcnMXGAGjitR0pbWeMz80gXBuGYjMIu5maNsK1WJi8ZUt6nFEswn5hiJi5hW9VfOUx4FEsmk11nzmVdgBEPwZmVOZYfUYq/pVLaxQ4WDoIyzqRSZbwyR9OyRGcnyoQbjzpEiVh1QzSjKt4MqNwUXdNm1/llVicjJgCSYhmOSzm+SWzB6vC9FYprdHMJLwxgSen0YAjW0ZckmttMOZa8NsMY2BQsyn2XhjWasNwWVCtta+3gmHqkGs0sZQaZZOk8p0TgnTZCveFVtzN3DWVtt75rMUS1N42rjonNVouXmmGs/jgj6X4qlZA+3tFALAMt0UoJ6qqIxsSwghtKMVJVrS/Xdk3pzJJ9K8vItzS9nJbbYistRst2dqZLy5UQQvSj65EUFJoGdB2cQvM29jvlm9XcqOO1L+Q8M89svc5U1pm5IvPo1KUGYTekiMROyLZkl+Q0ptiVsSAAk+bz9v5CeZUsLDolDsfIjmj1ld1MQ1+trt+Y0tCum0r+CWiViREDcXj5HWMwQ1PX5bdRv4tVHfU+CynKLB/Ce8gqEeUiu1UiTo511VxMeNVVvWXM0q7HLNp3NvagMgV9cq/RPVUoQhmRqoi2v8spSWYH6LErjjKLZ2xbYsrhnoBQ2wXq+1QLq75aH6pX0/ucm6Vs/tO2HoUCcsydspJpMbpnjuDKQvO50lyM3Fplua74sTxkcSmMH0XzW9pgspHCfqCGBKxhabznrerhQXk00NbN5TsoTwpcAcKwgUeh0ztSag0vOC/mTTCg2ipUsM3sRXhTuotmKxvkRD6cTbyP2oo6svzXqmRwn7sXj2dVSla8op29UH2SZtpU0xj+V1UbsdBjIYepir3stSyWz06F5Fj1sapQzdvKxiaQeIUG++m3VS/3HqX2Uuy6pSEyHjFt7/WoVQxfDCvqHnIGNtt9gtVcl6el8tmm8S4hYMLaDmB7h2xtLnAp9/7CcHYQ3dSH6t516Kl8RVO3tfhUW9DuYT/kFVE3WitynqR7byhesGcvyHtfk5hDe6pirXKk2A0RtbuuxapJyi0enQNtMQnDTN2Hzp9YFZYpeuTpZ+IuJIlol6luZinjFaE1y4vXqTg2Jtpl5jdm48rdwYTQRtdUL1U0L9a8jEXvtV2YPZnsFDbbrhqY+hZPW8frupT2adXCp00ek3p1bWptGYut6YT3Pc9NMQwnu7wthZlYsY54hYbcNnZJzJnV8Iu3TesqwxiM3ayqRDENMmkMQMkYKchHrK08SBVJfnLd01iDWZ9Z6c02DGO2sdJgGJS16DUv4NzfGrmLlEGqQY18i3YlLSa1YJ2DKqan6paeIxWcU63tXblnoohaPbM7VJl/Sf8v+RhKdIglieXIULXCTRzVhjTrRawgto+w5KpqvG1JNRsVxZJgmkfKl0xfu4TEElVWbWVajl7F/eu2PrsyvnUXEt3uuvfKiBIk2fMqYDkOmZ+YMsI/462rrPJqQSErbyk+MctTbViejpoz/eXi682J2eRvimasSq5G9Zgpi4+WY0uJpg/kUAJTPBFdeVlPzfNt9lwmG6OSo7LkEVhFIlZ5fsdIAPk9du3KSXmKAWNTi8HCC1GMpEYPEydif0MTNAKshd0YqjuzdKm01YwwwhkT98I8OWHBrqKsVBirKQ7VtfDNm68IGkphG94sm/Gilmp/a3IrJOuY1bKxyrdT+c7r1K5JSiorxnCaKf86ImC8gISVEPeLzmK6q3j99B5+6OkvTmIOFuNZ3ym8ZlV7WZbwNJknrLOcpjxi850CA1bOQp5pzbAxGvFwVteVdRhLmSgyNY3hXRVCq+OtnYLT0/am6GV7uGgD1DntcBXOjDfYbpPzuh28soJCqkqs8nDLcpslLfnsxHj9Fq8mdakq/n+u3iTHlXTL1utzGjkB9xNxohiOVSTt0ApeK5xO771UQ4CmoQHoPQkCEgIkAQm1n7Ipdd9ItNe39m/0q84tIs5xJ83+Yu+1VyFMy3kM2SBDcWMG5X+l5isp3C/xT0MShPjQshZZbIu1yqLlSncuuWFn28MSSLKl3otBRbSdWnM1ezi6brnMPtWOYDHfaHwy6eVY/3r3SCDuFKtwyU22r1vaRr3s3vBMpGe/zG1Lexcf8IarnDV/MGrXUgBI41Mpd1nr9Wy9/qA6SJChjGjU/1TpTztX92/4e1qxrZl3AYdwdjSllupiKqg851SibYj4mlm3nZpSXQA2CjG5Zkk2bmxUeDt9qcUbzpoP+6yQQs1FRFbqpIiJB+XAeij5bac2zR4tfbhskPRHPW9N8/pB0PWyZQJ5mYOvltt+uMz4O9s8mx9MOSJHQLx4I1l+IFq/NYme9cX/3jxUFg/vSFqQ245cEMTwV5rKMxqIHT2AX/Erp0w1w8vEa03LN0CBvU6nmSj89xI/keEB4hli/ejRdEkJYv81QsfjACImNo53GEtVTf3uhFibqenlRxWGPFbyO8Nnjn6nNVzYtNxqCz37y115/VZ6SlH2flgxDaQuotJbiCuLFp7OaLse4Lyt+bsXHdPWJcLRlr4YoYFT+xy4rklj8wvvJxJ6MvNSPyhO/ytRj+LMNofdIhUVWTrqh+paYfMb5oeVhVX7lRTJOJsrictEIVX7RjgsxjPYuX7qKzF21Ny3Kt6J0jIphhyIkkvQhPNTyh/Ias74GEleL51tHvalFHCSQue6XTNlyZutqVLQoZASiJ9SuWCnpd0Hg2zzid9JvxF90FNy6ilhrqyWHNo02v/KRqGyD7yQVOdxvFYWDhWyPk85vQO7FUvE5A4Z08olLpL0qMMCvBWaf/McPNq/AYFK9LfS0jFWijKaclbl2KRzooJh0oGM4X0LBnrW2LS5xv7HHhNr+kL01PgK+FQslfVbYk/s259qYuJQaJRGJX4ySFHj3Jl59TIyXaK0nb4sGgJmHKGs3VPFp6Qx12hIjtgZTuGoqoWTVnnuaakR30HXvcyRUzufIvk0xKz3ttWmjo/4+1/xl3esECjkHBOnC0H21ZIkZQVh/H4kw0MykgTb1Al+CDJkOtRfsE6X0VRnxA1XAb5RHJi4TAxEPLDnLcjUOz8YqhrmpnzFcT4cmdYaEPv52ezpokCmR/Wd+1qYR1D3LF6fioBHQoIP1e52LYh7KK5odC61dRSaa8rrMjqUtBFTfORzvG/KE6gzKAYjo97W9Y1HDz0jtVFH8WWWTucopJWUd0olwypjqtj35m1ce8a4Wrgpkly/Wf0QByu/b4b9Is6IdrKllL8fYXRVKbkQu/GRIGWhJ+OEbHIfjAtm5U7TSPW97CylNxr6NDLnR4zVxcigXdfBxPXpifYozQ/CvbjnW1vm602OFTHoJBPfcVDanFzNHhEhWDbSKhQKbacaUirkMZo52n4dMqzYtpcFPNo1jG1aKOKIPHQuy3/bBhEf3cvheiykGboP8tBgRkpZZJYutI0XVUET+fplg5MKxdWJHC/PXpy6tSgHOVwuzveN9b1/lYPjW4UAl1gRzxU8c5NlbzobrN1Y3fFe5Qy0T4fBxrkya7LzUOqw01ORvri2GkQjPZeYPqkkZuTWMqmfpKfIUaMu2uS8qIo9EZ9Va7qRtqNO9Ry6Svqi4y9quP/Z84g3Oa/AiDSW1RZldPv9ulslF+oI/b4VQ9OmeHZARNfM9UXjxJIrDynNz6Ld/hAe93If+pa6INzZvpRO6py6hxyqlXcGaVL0jI+SEEOdm2F4tljHGJkH/f7HmziCO75Sn5tdkc4SP981Ud7ITdddMENm5XLix/77fz4znaUVJS246Ady8JOF4r5Q+gFtKrkhDv+/tVGqR0VexJJ8A6abt6L6KfhZerqu6UCaAVlasgQhysJH0xCg5pJAhcfiKFQMj9tormb3xYt8d+v0SemSM/PrZRcEM0LBJJ8JSKbhk9SQcSZ6RiHT3wMo6MGgJ2ll99UTjdohIn3nq3otY5DG/NV7T37Aiktu9XgVxNqpHUFVOEIIoqI3ief1Z5786WavA77bcdtHE6dkhpn9MTIK3ocp1b/R1/jafOV9kkooHE3J4vJM0cky5JgHPgf3Q858hX9S+fdwAqKUh782yob0MpQxUJqVtfYl0qeaPEn7l3/5b//6ryfZGnGr6WEO1VelLR/N1By7ljg+UnY2XPBXnqBvjxvCBHN/U+BFYZFgbUWbRWeZ96xAL6L/dL+LQ1W5awVTPwZUiynPo80UnLfSocylfdSB0ACNx4/SJf5LtMREQI8gSVO7xCZQNa7YBz5fZnClMR47Qk2RO88458FNMuQRBrFrnqyY+PL6dFjP2aK1wMi7NlvxzL11vBlQcmG57GTa4HPlOy05+ZS+h+X6P0nPJLKbhApUn7NJYbHobtxDVAVr8o3sOHyhYvXvyJyovIPj4O80n6dlFRCLwvAjiwuSiTVHxjZybXSRMTa7bttdbKn4KrK47KZM/MFEYrXPv90P5xurRO13FD/UrnVfXIriRQJUV6NdE2y71mwH2l8i9WQPrM22uoA9+rjWNoovejNFRpQBBj7g5ugUkK3m4i28XSvJ9mOPCFxJJ+yMKCt4h/ghsee+4otX5Vw6Ue+JYu0SjNtUqzju0b49LPjxDZ7h+v2q0jUHJgFRS/CONdBMLCpRa0747hMXyC6OIA0X+3uRHDTkKUiu15+KhVIRvfqU7V7X/KjmenBJqF/Z2yRBPKv7qbjeN5W+PpPENAGKWymh8fRDartuxBN6KeAOFuXdEfWhC02Yrf2wPos51ydCbSKTvrqlrnrZZMoM5vlwap7yq5VojgTMTaiqfXFMW0+sjeAoXjc2pH7j4Fp77C9aiUt6LwChrt+Rdqn5BVIhlNJI5C0ZBu5oxzi5ff7GDRm3hCxBOk/N02tTE8zyhRV8tkKFJ+8+TrvGvpAFHLS78ciem2ZO4jwbRCk02xkHD8kWR4YhFVFroCb4KFfT08AxQe5XCeeyDSxDUlR7ThlAbYolhx5K9+xqZoEdljBPyJWJi4irjxi/E0l2dWL7AtHKKsqVod5iG6iSC76ePvuT3owHOqPJFnGBIVGciJaa4k2IeouXKqP+fDTp0Gv5ZdEzybdSn2ZUQ4rFkVdJ3Q2HB4Az6ziX7CjJH9l19eti110r2P7pPGdIgkUhHz95VTnhdSXS69M/XIXoZlBZI8WorqxmFIzadnYm6IzBU0yPSFz0zmzr35vgponXq1hlvAP3bDVDRu/tKm6FjpqFsc7SDY7E9sheKlzRXdB/rUbUi13titYgQxLjdCSuLElxcpuNy3+OM2FhJn2D1zq3Jb7e5+NWULqSVbk6nskxFtWanr8JoeFfv7kCvqgPfZrJtzrSB2AKr9F4S+JlYcE1r2n3RoJ37JsHZJ2fPzV+FPoqBu4eV3bdY69g61Tnya2HvbQDw/TuFNsogJSATkZZcuscPCreaHVy5nnlZI53F69aB6bgjkrOcZpz3HeMA6K8BU8tNq0ycGZpxjXd8vSj1KeHeFKJ/UUSYIJoJtNttgJlv6m7LBA46EvfQjPes+KOc8VZoNXnaR9zHiFkZtCt1jL4IJP4qq5DRXidzvoXwbutTwUnz+nhXC59V6bcZIpR4WhhmDMrUHf+phfECqZzspAgbgld4rTAWjX6MoJUsmxfzNEY+pLukZjEXTldjfCIa/c9KE7vd1/NA+xqaADTpsEXgHfTym9XNbmz5KSpn0o8TrR8fcZH/8u/aKRdWlH9AsT7FCQFfDNHYcRvpTZZd5FJ1Ycsh99/fzvluFZKH7Gkz5n3ncETEO+jwdepD+vvFVDDBvWQFwDCsKSxa3/DrknKpgIkPwzbVgroyuxOC/8kEqYB1rL/bq+9GrrSMEct9xGYG5X1nimm1SDmk002Vau37TND1IETVxIunGWQFlDrgW9I4RyvFpBm6PdYqykQpGkrZpRaRHJvIz0OJNwAsepme8htruvIm6uFVy6FlifLDLFUiV5RoIROO+HT6ynpKyhSM+xkfWl/3YW6o3b6GJkOBKvajkCli+1sODGE6h2ZeKl6Mo1PhTY2mM7P3OYUeHZHUH1dXdZXRi8sDQ1J1areLQGFpBF9ps1T6tldjwzQtPYvJQ0oe3W/2GJ2zVNzWpzsb+Y4KfZL5nMlw7fSkxTzaJnwpj6KjSn1ivYvbdSdV3LGNMuBNqSK52GwuFfOoRxjctRtj1+qasmCOxkPyxHjSdWpguD0rF7ZXKlBy/IsDSOJgGXsrQPg7msXzY9Et7HUVSdaZymf0Xv35TENI1HXxtKyqsfpUEByXyNPIZ9HPG3hKtuHLV9F6N05VtdiIIIt7xXnv99+Ku983xZ8DiUlTI/zDHzleodnqTObJHQdFlM5AhBfdCwTFWs//xAbST7jD+tR5Mt16f6ZscEhKHaNHp1QovUZr4yz3kOxWNvPyqm4+jogfCVdPRu7/Z7JVHfqVFFyCdeV6+nJfoXJJ29fAiRdeFHAXeYS70sK1qBW7Gw19/uPnyzjHQyjfn5VvpM0+fo2RjlX8Hn1BO5qy0QVVYu6a/9shAqt5RpS/1WLS13CEazS/om0dDp9yKRk7MVvQwctEjIYsoMERHJozUhS/9LYBu/cV6W1ZSCJs8786fBH8/rXkiekQ8Po58RRdSScaqmPKmgWFZNYBG35+ld/YrmEYxfXEO8n/VVGXB55h/oh2qrz9ryLA//USaMS6zJl1JpvEbnvl1iJTcOK2Fwp6+nmEyxnZ4XWOOXLMwkH5b9+/gB8TgtGa4l1gs67GuLRJ5L+wXMiYSEOaBShP9/1q+IrUwHjLSTSgNOU4h9+80qone6XuXjPVMisqXBIj8itRJpcyRq0PPYfu5hMTkkaZ0330Umhte06dLyDNmNmPq/0z4ydSwScpr4UTg+JVyZHpyH2GB2uvmY00JpxdktZV/P6rRbFq8DIszcuwJBtc2VWg4SeeCOv+js59Z2dAJCem3aU4mbLzov9mVCo+VL0n5qSmNu42jWKuZy10v32pfmkytP4K9TDnrz369AZ4aVgI2+rpD76QT9NslyxGIR/BLWDOOuWSkx34OHHE2+z+kZ3YYmq9opqzfZWSqtPqyYrJz64HInJZmK4VOlcOcRqHKH6fMpWRpWztDIccLqsz4AZEqk8c56t5juWOAmKghE9RcLY5twLemTVGRLSPPnH29ubdtj0HPwVqoxtbCDuTLAGxQod3HgT0bWbQCWY+Ynrv4vBNUHBAXgTfPJGb/Uv//L2Fr9D7Z9Mapju05Vcn6K/Kx3wYrP53GnSC7eL1YV7tju7VRR3Fn58Ap0UaVO7dsnoHExdjU8sksn7X1HvtZns8WQsaeKMShgJWiyttTdIKTqttIYzUzNjn7sUGGq1bp7Qo8pedG0j5KJbUtb5viYthweRkYm0K7KhxK+wxLzwS+sKTqiQPDTzWsLnwTwwMdyKYyM80s1rqnOcQxIj8iT6LUrn6ONkTlGdnvtl1joROX5XiejEcJcVsleIW0u4CDAg0Ppmc2y1QFBskaghItdOuwkYbW7XmWyq6VJ8+ak5RTCyEXf8jIuuRrFEZMMxROs2xjckPaCXenQutHq9jhrzmCM+U+B7kcqqNf01x02tGgX/UYH6X5DZM9Riek0cf80CJGIV3iaW6cWTT8vxMhO08Nnt40hkrEtHXKJXFPDOelw3F/gTvIPq1pennr/4AwJO1erPXxYcwytxtuImdzj2OS0JCn9Vj93pBy5MdGNwohHZ1hUCeDxM8dVk0OSBrU6YRIpQa6l/H+zwuGINK/nlLLMx2coOsncQK7yb7kNmeiztt4zBlz/lpOmk2z+jFHHFdNPXM47+21N7V0ugv3uGvljDMvWxrsQRdwkkYp3Up2t600ZF+2FbCk8Zm+owjEzHWMaAEjmkLL3NOBlD+i18vsrwji4ElTV90j3T8AP49jKb5dSUqyYuuJOi1jAFdyUNt7AStSEOgL91Nyl7BwLfTdbnXTK6VjO2JrsPb5YpF4q3tIzyfcdDWyrWz/5k4z7BXi+T4rgLmuucL5vcYs2JW+fvOhFs6L9kRiE87Mr3cKi7WmyNi+onFyLgNwTfpWapOYhgxcjhGiUJMmkK26F4EMDniUZRDrYd1hFR3upsbroKiS7puNs3diMu5XIdj9Ow2SrzKtVNaTJArhv88cGXlSpzIknwDG1L6WYXp60zv2t76GbWlRbXkHGJS5xCn/KeX4nouaM0lFtRhZ+TPCerXe4PL9t5PaHkmaov3uZat4r7K42MmMZlZKnzIJoba/HXXry1OCy1Fy2oGUbMhH/NiKhHZOJ32mINkLmzaxxWlXk+deYdZo+uKTz5cI9kguicXsyYApWMlaz3JvCuc2jXNj+xpNur1xxElAKe1iEbw6PJU9dqOUJ0sjF1SHq8CfpGK5/MxlvTwnzakokYzVkc03cYt/tRecUN9KHpouy5OhE0N7nYr9gBcbMPpv4/y6iw1GsCodWnY7GI1njFXyctiuUvqENh6Y8PKymuXrj5gX2qVDcGE1MPFqE5CNmHJygq8kOudDIsdiA/i+IfZxJB3xbPqYTbCo1Zn6VcomLvfPTJIM1gz31hcCktfVzFto7CtXGVnkw4p/Uk60Mmp45gFmc17oVFSP+XXS46q9MPkqcquFl89N//RNdDxRALHPm4F9lVHVODSb1oHZU78vgYBawepWffb11Xhi/mpd6rg7DkWr+1ziZ23IcAKYkBKxxT92lF6dzO/SmPy6i9tv6YV7dAFCmx4iPLnq0cc1GR7/Iu/ppnIurs47BDi6yjJJ9FhcDBOOWABGqYgZwUJOqqfbIFl1KsdgKXixm8aPX3ffpV1cW+BYBX62uQ/ARkDlpifE/SbmwDr2W12soGP1Q5D1yumpOZ1PLN7YZp/H53GHA/pRtx96qgjuGMhevHuKp3C2JCOB5xmKixSw+bQeU5ruVUTHxxsWNmBp4gABjZvDJ/eJ6YpUv0B5zw+x8k75obfQUS0FzMLnF2ul/uHKc5aV2At2JvtZw3c0kTX9MZFFCK88dXrMhuYhJMBx3a7IzW1RZQ0kNmgR9V6VhWB3hV3yP3MPUim61JRgBLWHwTLWjpGmO5kXmdtkzQt5VXX63awpttmb6KkevZshBk+VgiRbV2KBEgTKVGxvIge7gi9XXMAhPkI71v6Mr0gLZjxQtNT1l9hVKmrO3AjsJutjd1+MN6Sid8ITpRU8ReWsTcaD2RaKrabAt5zijbyUmh9n50kYcNiHrktXcCCAFpIgZspmYSD9xR8Jks5/gDew9ghrDJRnXYC+88juHD/DBWYA/h5zDOtc+6ElnbOLUk/Wuuw/wKyVydqCHhyXUgxXNviJnIE1c6Khzu9sl6dYYx8ZG+sJbSgayzO94D+R5MeaPavJ82Y6jxB9ZDws5fGG1lT+m/euxm4Pwf+1w8YpNOc4LBVu/2qizGdfEHLH3bXp3USS2efB+wlRRWrYrpK1a88FTTaCphIQ4NsessplJqfTKcApI8zku+fvXNu3SQYfGDuKQiKC7CDEGd++wVFRw+WbTV7stByJCnUBQ+qyZhqPn4bbWjw1YSjs3B1JWmFXhVXYiXvUIrvtmYap5Ldy3Pggb4RvY0DRV6q1rIllrCPpp0qvcmJjbCIQ1MAqock8zECy66JYt6mIybPZNNJFiJ9swQJuSauN4azS2jJpYg2lEA97scaGLpDc+J8MV066xO72/OqMozrwhLLiY2c1b3tfcBdLahtkKGwQDJUTQE4vbGhYjSP5bIkloJebdvxchKwDs8cf2JabDRQdFurkx9WD/f+INiEVmWO+aMVpGwTWUuwayTNU4jTc87xw6LJb92wntx6Z9goGAbVfBN0nUwt4mjXvstvogcdE8CB8d+yt2kQ0riTMsfem8HW4FHQyl4hVDlSiKa3mQoNTwLddXjOtP5EPMuWa5ekkcqSjaS1zjDkW/kPxEw5VtS3FjnxXW9RosqUFRBUUH2I2CtLg1xTileNq1e3Yz1UxzD9BojxkKrSWaxD4ogASAqgVZfRfz7pkH3dbeVeW+jF/uDM+VQmdU3JHSUEUcs9t/EAYwlI1HH7XCFFWD2hU0zDuCLO5Ars6GV4kuEIrSE0DbMtYec3NJogxpqUlOYxf2cbTKJ29JqAt+v8SAVfA+m0rWjejQCu9CbXtyQKss8nqBuMZFO4mUJ2n7/67c3cvxyIK4nsu6AaYL+uHvtF1H8oHV29aYTSuX7Tzhmk476uss/ZmakUQX8TGTKCoZMTd9QVSoAR5eUqPwvYodonOqQ5UMkOM21iCijZlycKFQJbRgO1qnpmh8Uceazj0dmcbeWWJisLSWyvKPRawG9GAdsovNFb6rzb6lIr2kxYhFY2lTmHFqgH0XjsH9q+LE5D40GX7/AEdu9rcYVRg3Bdigk/Fmk9B5DriTJJVI1w5BiTGJSr/zGzqaGr46PhmsZt95QPcAV4rhhVevgvyso0MEkEwbExRk4kfhNU2dIOa8SStikNom4vzNkwsbhxN6Eyi44DnUG1Gqz49+L3BmPKipa/YaordiNa5WuWyTdPKU5sxU6TqKEYlanb4Jl9ZcpeMm4lfRuYbF3rfwpxzmOVtgDTG3PViGnq5kXivNRohjW9OC64yz7K/lRp+pxSy1sVaKwUYg1T3K14/fcdl0ojF0eDlfuLEfoyryPFN21TPm4Z7pBuFrcyObVynjX/f4uuGHCD+4ET85tsWh/GH9bFnc0iN0Go+m6x13ICCLLw5XRy0soLBHbzvgZ9bSwC4fEOcdguMF0USE6Rqv2sIME9HmgfMb1tg1XyepZvR1HbfoqX39hu958FNwin7TViPQnWmQrLpSPVdkUg5EEsGgqdaO9ZO/B3n1Y4Cmj7Pe331+DnjXp9odNLPDJtGWmz51dkRTm9P0S5jcrKLWzQ6JSiS7LXE3fqF0vwz65Zi7qVi/ewdFl6v/RyquDEpW4wnha219nQLwY3DC1/Kv4HpfXdsg7Swby1iHqWT4b9rKI5b0pcxRIg9JIO3hXUhjAYoQYEweNSGdjWvbvnDS3HaOqO+T3+NmWgP/5800dv6rjCYWQNcwGeGxzZGMY7bqznsyk+XC6notyYl/XwcjamhrsDIBkDCtO1pZWMRwGBVT1dK+REY/cBqvTMYDstAk9WBJVW9f8/ZU/eyqWF9wVpyiAaH6laZuPC063DMm3KFCb54vJqgPKhjCyYt0kV3PBo2vweZdGaycUjykKsnKAaeCauS69Nmk3p/1+sVfk5TlSDOoC6ZUJjwkzBmpxHf1+0iC1g31yfbay65kIzPDl3RePKSHIncUaI5QyOxAxt+rKqK2UoXpQQj5/QX/W/b1VdqTpMMlQc7/MNsUqs9/W8R6UZoUF5DnL0EF4VDwsPnqLz+Wo/ZtC0Z0919Ahhe5tcISqutD9SHFywBdv/XZariK1rTd5y9qIo04Eb6wPdZmFQFpJ/ei0uEEenuAQ8Q2fzqbo5Bwxxkbhuda1u6rVMJ7KNJlH7KlEqSpHSspFCxJkMYlo99HVqhxCkATFz7ih/GOvHoukt4wFhGYQrQXB2lc8WKfCgDjMcTnqPO7b6gpg1r4Wy5r2GHmy6LYVW0Dxvi5K6f9Q8l3g9ClqQIfsc9djXTHgkjH7KhO7Td7F2jMfeAwjGTyOOMdBp8q7ildRwYUgCjrqwXIZ1tH2udKPlQAbiFqN10WU1+Kp9mzysaxciz2OzAws9zqhmMGaTFDA/ilsQn5luD2pB74hcaqcsdARtzMLM76XnikH2PL3jB6gygqixJ8xHnjXa1FmxLt8Hg/gaywwsvoMXnw+2QyZBJFTXh7lva/pRjQL6md7n3R28PClqs/hhbS82m/txt1QQJ2RI3FIfTM22fbJ09AoYlWqxWE824F6gx2qhWv6Q6wUfOiF8ampVLUqlutrcqrKCqqo1ZnioWSrO2JLvqJ3jBvxduC2G2QGzRnss6EzPiFQJWfLV+wWF5i6rB2aI1HlttpsO5syxfM5or6bzIgp9Px7dWNR9PCe4IU9Vk+2B+fcS24qUjhVbBwdch10vBT0dFnLPlqc5YZ+3jBTuyhYZyFDQ8+3wpJ1SSJ26+wzsa1mTPBVk8RfWfCe4WIb+bot/K2FQD6tfWeHX+w8NMwtIt4c7skNy8ahK+7dkGrXIzdhPSjpLRft3Q3yPNns7Bv5qBjszjJswZhnvFffjJdJPhBve2/TFCcOMWgzperiNvrrVClbWs6e/aTX9rR+cK7VICpSkEu+7xU6/JTxzeCIaLnq62Tbx/UIZsQH3wrDbo9rD4mk80DFNrnPMLHxJnji0cd9bXKZBckiDOivj7M5kxb9cgR8EGifUSkzjLjuYG5nfBaOTvHIaqouE9UJb1J/VoYFGU8Ub12cMlKIko0mDm/SwJFJiUnbpSjbtu6GIGYYFPhE8HXOGEfe+ym2vENs9aoN4ejhq7BbanSEcb6jjoErjy1OX4/KhONrvwSTLyP/2FXx2a9PV72VxrgoeSVt0WQqHdmLHs8WQ5lTqAwItZ8OkaIr1Ycf7BzxS4dwvJWZoJG7xMjtTOBmy3h6ITVX3IF+zVjFJjN2yddgfnPvIWecGYNqRqaT8sfLtIgXJle4WGx/n6AuyzzaX3LoTNIe3U8I1qe7M5WxAJDRi37NU4n5EYdVFZ/nWzriblequArOUdLp4tA9Q/Xsc1Z6lgMstuWV3sdpvwCRpTW+S7Eo8SBjUJtCsrAHKz+uuvuc6tA5wdn5VH7S03mfpL+1cbDAll/7Q0FEqhECIkTkFzk7XuSdLzhszGR69XkPzyKWPuq3gvnhAlzP2NlKpig7um/DI5smfDG7/IhCM2MCtGgbJ0Qvt7SC8jb51IhWAzL1YjiWitRNtLrzeBpoOyag891EeJeCT058Z7LCom0/26K0qAc+uktxpyLhE4mB2IixFH6LjgJD1Ew5kQHEmubE80k/3KyU3/5IpxM8FZCL26ZEy71FtTBNdhWq4h77jENaf7B+Fh6sH8ZI+rJyBHZZnn72sc/Gp9hJwmhiZ4j6UJw9VxMNc+vo3551m2iwIHcSfyO8SUfdgIzQEvPTy/oWb8icnrFwbCYGlcLpm62Y32ETpbZicB69BM5ApO9vf9hZwCSwwfltumtboS01LuViPm9PNRlMwJSX/BU/4YsKRZdhVBvoemT8OqCq6OzP0MLu6Ky178+v0JEDTRxj08YxoQZw8Eqtn8wqp8MukkHGnbOy1xUi2hQ9TsEBohntZZyVekEqemJfB3sAbpAAZXgVhS6eryfVo+Te/UJH1uz2YpEcVotB7NXP7+pDoZse9Mn0Si38ZPPtS3Ly1YBXJhpi1rgesQAkapFrI65WlIA2eojCjPxWcvJ+Vae6NwPjEQuEAGwfmgYRCNG1t7f+F8Cu25lURDBiLcYSQ5P8M+XYHvo32BOTHSXY6nuvLUiZLQJ5ZbsHnQ+Hn4hP4yeK+BqHJvZmVCSIMqRIvcIWdOslJFbAnK6fa/XkXGixrzDrerLThNVu9s6duuOYy1iRTPG2Q+uIgqm57XeBLwfFbGT/Vzqrv3a4d4OL+MIwsMA5yv7qqj97S+W6yAGFKsqV8IP8UVtldue9OMKAGNylSyNVnkADVaiH1mL0TPGMpdJ9eI4i8sJimVTzQCJRGbkoEkGTWY9Bt3zrG3SBavFcsULJoTSMHRFtKQJiwd1hJC+4GT30Zwz9aAfNqvuu8/2mZit2zO00WEGnOUIt+125kHXy5bzbtVrrfROvpLPMQpRl1M2NiZG5+7GNcANJpSEJO6n1JBa22PLhmTkwhtQe+4//DNkrdWH7eNhApjQdQ1wYUN135a0mxJ2KnfvqNFgdVMPZE5LYaQ1Rz8Bc2NFQ4cl7SpPgR/9FYG+VeAy5EEtlF4ea9laawL5VWqAGRFRT3SWZZB3/uYrZciTc8c8/NY1bumMGAjg8gGicdPzZ/T9pPKg4dswRLEZIH48kww3dp2bfopnX7T7g0iS11qBTeOngLMR9H3dvPLjBt+5DBh2Mqrwr7rNBkFVLXGf51UG2NX+cHDZniep9ShSKdbGW3c3w2ppm8mtqky10MBebMxLUdXimlveVc1Rw+nruUgRdy7G0RnUz2dI13v2/yd9IZO7GJJOhz77LPH1VrrVcONUKRz99+v3n26vLlcWAbXyWvta4DQsoPNwmbphYA5J1LuKzf4u1JUg4yRwFzMb1B2XYChVSObqsGEU0v70pVtKVpy0BBAMUR2hyAFSfDl0H86k6R7FoSh1epM61YNBsfFOtrQS5iztqxmSsw3YgYamId6VgA32ePIlDSSzDK90Gqd32rxEK7FcdX8N2cOf0TxydUXAneWC2BPERr9UE72avZBo0W+j4ge5PqdV72knvq5ykZdBoXwqyfuq+Ze/FRgGj1lxmseLKuWvFkHyF4zPHqRTLevXpBeGbDD7WcUrRZdGJ8nfsNKDL9XSvXOr2cfMSbTvrddpCeRMJUXUq3PBHb+eApbqWLDbNHcpMOqe8L7vcaJH7lWgv68Nb5NWxvjfnrlRE6y0GZQcphOLTaDggbGtKD1wckGk0/awsjF939NN6Y6J3XdVm/8q5oQYIOHPPm6luSSZY5/uiwDgFf0/pPbX6nbaMJMihuqRjmVkABPVF61yGQWhsdVFTs82VTcPEaLtcfKh6NKW9vKWLeQN1wFxblekHodj7U8Z+OkW94terCohVn/1XD81RZz3ZSLN0F7psARDI3BNok6m4adwJaWq+dMDntsRlILzMOTBZAZOr+z85p1rLVnxIzp3p61KIpb3E1lsegEz6UvKTZUH9sGzvKjuK6vP04+39b3Wc0ftDXottFl2C8iX1p2E4CsjJg7dCj8Otwn2YvJGi7M9/NKfTkzZXnxxggjimBEVq4hOQq/B4IOFezB8d5UE/ZSncO1KkuNtQ+2LAIVzDxMOH8CElInUK4C7ZNvEb+qWYwr1aLJ2csUEa/UTisBiggUIqVrc6N/CdxUBVFSx6KbafUS6d09X9pSaUkyj4tn9H/ELdkt03PkqSW1uJaVuV8RJWxQ3uhaSBrwxRjkBOFSI6pLA8iaNFDDg5bAGeMJlAcnSvxNXibzxNTL27Gy1DL9lUVK3d4K7P4z52nNDdBGObelGNFQueov2RIUvVmjO4JjlgPf348RabZ7ZBH8hwonwqcGb3gO9vf8ZSI8zawgU3hijt42B4AENsTEpu4oLWNS5E2MsNejHpJEqiRSq72WjJjVgSRGOwIgKeOdDocRYykMl8jy/yVXxVs4mlh8F7y/P+vbHdNTT8VmmQnWs6plLxj47wBRx0kvkpuOblXgwbXE4Xwwf3heTEU8kbcf0Aq+6rvF+GnA9+DDMLUijt+nU1LkJ0RanKbRIko6QoVuWO8IqdsPE1FiU5Vn+ImrNPOCHog3FvsLZoFdpkgSh2DergK4aQQjKuHpctMoCYgLTwE6kdybTputrwXB1nO4+Qp6sF4p/ERRd7bL1b82nc9+VwZHem+Utz0VG8NGqux3POqgdBTRen3tQ9LEhRkshk8xts59DxGGd6f/+JhVp/LPkTcPkgukwcwnI7aiV2GWeSAlFTHxNiT03w+dZbtH9LU2QX+Lr40UeZR7RLhZu17T1uVV5SI1oKKZzEBu6bdPeTHOSMoMx5SMWh0KEOBHKMeNniiNi+Jv4XEajxm0wEDTvmEknKYOKp6LeiLNmOQqF479vb9Ab7lBtMXm53GV8wetX6QvRzF6V+X4its5q1e80enpSpTU+Qy/qc5uk5CnpWDuMDP+1lhf0Sr+BXfBAxhBE0rPNZK2L6iH+UQ21I2KlX81z47tAyhX1og2FUJq8Kxi6fyFqYyfVKWd1MyC0IlgAjvXUR64V1sDUmmeyqD7Z75G+/y375f1aP9VAd2+6Jq8+nulE4ksZMOTPofJczvJ/OPTPJHtsmzbXv2GsyKsp/BxIpbUkcc3/FhSNmDyK0XsV7U0ydm0LgUDXQ4WWvMdwxW6WI03GsobzyPDSIrNcErld8ORSUs2hiH+v4CwUEumuhs19fVfn7HClcwx/PYkBDc4LFr1pNBxTCtotK3WDKQ52cimQVYZkFq5HC9Xmfk2G236mDM9J9RWLnfrtJsmKryvf05MKWqeFzyr/6ip5EWktJ+AHhZbs6IwfswoE/atpE7SjMqWtXumZ8MT3gVYEcy+hDHIPPqINnjftVM6HI0HY5d+mUrgNjhiUhcfaQlpTYk/6ar0ZmlG0edQV5x7JA0/fSfFU4JSGIJDkPMg/icJUJQCU+YHVVzJhN2S67ICJT2DgM2TFrKZdgwg+MLzwh9Hh2y+tIKIFbm/e3V4Twh8Z5N5VTOj5bBlYw3A7vZ5qfIZPWzQAThVFbSR7/GsLYle0V+2x4P41hj3N4ZFZB5tTIKEJzybgI7V/Ur7Bf851vnWw6NwwYiVBINvSp4mhwlJ28ebPWUT5g5tQk0Jm4mvrMJblbs/C/BtGAHfMZcmzuoxh1URZWteXBjhMlH2aF8/hQV5Jc4Pll+TXpivK+fqi8WG/rt+vY/ffyJOxIDItudSSBsIEP+BXdBKO5LbI/sfSG5ABkarzclw9lxz9F+mkyhLHHUvIEOjIeO72gb3YoUo92BV92vWszF3uuY1cZS1I6LRtgxqXwQZX9cmMVdYo2qNbscUoVbjU9LffqvjmDac6F0chX9o/ursAj/Nz54m1ybZaRUDNZ0MnIAX1N/L9bPM3rBAX5pmDlDrK0DPrMwRRiKI5N7H1dcjgerpO7bKvZRe8Rr+7cJ8Kjxrib94EJzstszEckXKwmHr/P0dgDCU4Das/FzVEkPfyouCmzHdIAoT+9//lGVbmuhAkIExVLerWFApeQgNnn6oSJaE+GmhIuXXsNambU2mC5+U23Vreln3VcaoOdkqxfyctkvRarZw8UzEbo91FTQAUm2Q8NLbthTlNwMN3bbJK3dkecZTFRu2D3gGH+moqmtN4aoMiQnvbo6rqQUrU95FUeV5akwOogo8P5qI4xGveHjgvCKaYF+3MZwakLYNljO8npatlO9aU79v3lfFKWlopnuxBgITjJcmFoiKp5kDezCQnCO2YlNBSFyDkqOPQwcn5qTSpPv4R4KxAOcyOSzDMBTF8qNbN3DKvGjOIwBhN38AC7/2QbiZOislMJ43RMdd6dPZo0ozvLT0OGw3hkixcE9PnjZ7yTD/GolLAt3rTmgv1HasEnAgkZ7x2UQ9St7UxlrxTwSqsUbvKsUun3qGruk2zUGDPbCKsqnpBI1jWQEhrKXbj1WRU7xffK1Mi9VmxIuZA/YQIUm0da/CGK/RswR2bqID0FVCEWynZbC+cjoVxwWaDbV+dKxjGyi7KUKzVnlTnAjanI69U6esUHqiR5yLED3cHsZOXGKRRMxterS2Q5I0nP2Du6EDtiuSnMjt4qrox687szyGJLRK+thgaywNpw6NCNqPiKB+C7LsuMzK6I9fNYkRuahtqlqUSanUxRBF4U0Imzhww+zcSQpIEraKEE1e2FpFEwseIQhI2VYIUrrPLf4jXJJnTbXp4QOi1t+St/TpSJ8gPejE+qKqo9n4xHM1bx4OaW9zzOEAtE41lLiijFlY2b9xpWivO2q5T30RYPrG8ZdG/fDNE7J1tkzSmm6AJ9r1+tyfeawsUjPmNPJGHDG6TcKQEpdIxiQePSxRZROHwGDun+jWUPm8u2XnxFavzqm2m2G++XeaSqh9i+bDbdXx2Yg/KaOUkhIjlEgLBUfpZOiiZjbljHA5zXMg0Qu0gjt6m/dxewSdVdGS7XVGJqanKh8mhiqmMjVGvUXrkMq+e/amp+vHEuR2fUz/S6u106mpyvddcSIlb+nvztkpJk6b5T6Vf6DkGpUcXEmWW10gbtoe3XsubJH1GK5zt+Jfbm/dVhOrR16acZrZPAvDnhyTjSD1t0EqftIyNnTj3IjIdV8AFzRslQ3Nlyk6AXi82puUBraZ36ivbs0ETOLA/vBuilO+CMQhfc5zN9jQNJqcR3tRDRlrG3rJPGWk4wIzAoVgq2tVOoWnRLPIZb3DHNYPN04uvEF48ORW7g0ZfIh8bVMlB93bWkqyeBeh2qgmEpaXUeKbOn4mcPZWiG/gg3yVaoKq4vxDbjkkDO+uLJ7TFXcAhLhxL54dHRtbIBCcnu4vbE7ZZBIr7q902/5f39x6k06ezGxpZs6UoKpdw/RffMZnJJVMgfui2a2zPjCYAjEQfbLA1ybwflBsQhjdHjVzxMhG9x5PDYlDmyQzLyi8ksU8QRAMwFg+k4yU9fKr6rGtXqWFcWTapEJdcJzJdSvKZ+jae8NxkCIg+m9UqM9HCRd+KJfA8NmKA1z/tdC+DH728eWt5TkmsAXHisPZKBVnBAzQk8GJMsxHH6XYAbnOHe3796UmRufnWPU1uSZghyYE5pIYk4STL1P2djx8rclX2bRCOneNkhEk6fMJDnLh7M0HtGIDZznbV61x72T5RS97snejJtXAh43eHFSKsbJyDGG6Qqtq9saFPLaX0FdnXVLSHkq8GWQ4N/ZsgB7QdibxwMI6LAnqcVD6LpimRNM6gbCLhCJ2cx6y+7tXvn3VO6zkGgk8W0WxqR42Zytk0Cr3acQCnbijkx6ky+VmZFrjkZqSusyARDxpq6Yi3aekonwZVPhH6RbvUM9SqJNQwftMddGJF9fBPof4NYpmdzecZnWEUjqRi32Hs/erpoWoC63b1yU88iGEuWeulMMJj6TyDGjGmLSlhvkOHmjbkScVrRPScnOH7dXqkW7SSVc01jD2MHqjkhrVMK9+AMJPXI8q2Td1N8lF8+knphhx0w51MOGMMZqoIs0JbuYooffjODsE712/3t6laol4Bm2BMydKADkl0qe9V34r37doOA4/PKcQ9FraK7vO05Yc6Ns4k1YtdrE7h46+MBP9SqRTmXorZ49ot0OO1OyJ7Dc0dlVuwWrh7Omuu3Xgv4RZVidA39UPBBvWuVBDKCG8bqZKvgeCSrGXENIm2xLyqISdGiSJIbVc56U3JSFIHVUgLS5HhAZw1JHh6euqENgv94x1HJLsV83xqqvF3OlIzYTr4MZPyyfvOlQ4RkWwD+rUaYYOvatN8Lps0DrZIocKbYwe9rcAKvWcGnCg+fRMCIwlaPhzmY9QrF4FU6j+JLe5Nk1BSfKC1+xsGkCLtY6k+7aEW1kbEy0XR3MmtSBLuO/agXNgYMabqzghWD1Tt+zK9i3xrh8iBrsgaDoP/Vxw6oH8covZnTDlR7wjpb+jcwQkmFY5e49+yKEbINyJS/8xVvWUMYRqlD7/QgNvNFFdKqGex4/dJ0zF2IvONliWDpTZx5/UliVkXSMoK5otgQrxJjjd7tWJqUrhgV6QWP5MRliphvg6qWh1TB8OP+bCc3BR8ncmNk0CQb2PaIsrDDKB8r3k67IEEplUJ3NJCZLRqnvcuTeZPzVSFVt31UDrPBfQ4CKaczIDC+5l5EMk1xbKJKmtCeqmbbSZTohhK5QehpVTwQbsaUZOmkIdDy1V1k0lDJFlOkd1Ei0g+eGmhDMpO9Vaz3koIyXjCelmW8JnqSbsfFdO5/9cCNOnBG3xFIH3XO4uuFahygixfvoM6aKcj8pZbk7tA+QLW4QeSlkTwaLBTFHLeee02ur7icQgWTt4PieuBFTSwfZVxwWpNNWSQ/3ZIlH4u9kvsOkt+9YZXe5ug74C507Txlk2t6611MapJwOLBAcPsONrgaAFFmYgXbfVsO+0qYkZz5/bef8pslfcdBlxkM1eD52mHh7gM3ztBK0wwCODqcox3is+pB61Ru5MKkJXHPTE2VZoRF/fjr9P72N4RAerXZcrJJUo3Cpabz+Ps0rQ/gcHgsd7/Dpx3F+wkvu/imgEAXG95ouAZ35YJKpVqESSB/k9F4axxzLYmI37RYQEo2dyWuKN5AF+s01s/yvebLgskg4hb1gR4GSHpShGu38Ivy7wAvqKZJ+5C7WfHl/R6P6Rvvop9e8RHlafOEyDUQzavRtJo3uTfIQG7dNWM7YrCF3JLzytoFUbLItXJ+KCMmv0JuzZTwxE/XqGpeppK8SFjuMFTtK2J69TQCEYOta6LNuI/aUtXNESbFoN5JmvYu0BBoxpsYbG4p5ACltnsKchwPIhRjvatSqkVRncuFwQPhtFLwj7LlgXNkS/l2jrrWR6qCKuXS7cBh8Lf1iPLArAWxMfphsmnse7KYzyJOko6dXmfAtH/Gk+7g7HX7tkZZGM8EjJnaTS24CbKi0s5TZppBfrLyAkXk00pmNQZRf9zhv/rQ7KVJ+fG7Oof5sWYC7iejS2VEZFiz02D+u/iQNTq/lQtpudH5xFWlRJ2bS+99eLksqlIQ8dcOzIAv1+iHVYado/u5WqordE5YVVcnt2H+fC1VE3OYWwhdR1SFomAX8hFXw0OIo15hYifG7+sSYhvH1iVzzbnJTObDtoWWB0S2WtaMbF9NUcQRaJrmp21l+eVNMQt67TkxV7moRzN2ohbb5tnsLjq6+2w904xjeHP4k6w4cEeXWAvdVr+iIInoEbYddsN61NWLA1V3uMIEfXpXNELKM4lRwzoySObFCeZNV+x6gHHg0O7ycSpX8xXPDONiWlMjKYkD7gRa5JBPh850n3tswLiYdWTj8YuJaK1bSL4wq13+5Pt14YWkYLN62gYHu3ThHw/VaJOo4HCdVP8/Hl3RXNVD9x3QZz9GYfpJj3KLN1a11G8dviEuiBsFbwhS0g1CEoxWht1EpToW5oGVPbDPACnKYBrIg8tpThIHLLmnakxti+80YqGQtc8Dx5D4u//Xf9GOeT/tS7yw6pmjB1WEuiP7F3hNx4tC8PBPF3JqWO2pYzEO8Z7OWvaNfAl9JLbEJPfDilTAVtF4Fc2RZ/yyXNDtiqudQo4Pc279du2j3oRflHHoYOxUgNXJIkRKi6ztzEW4d45uoqzXWdl78rNhRKMabzS9WFYO3UsRSyuqU9XyPhG8igL78ZxydWtuNbNGFVQ+2erCZslCUvfKQYCX5Mx0+VWUv/ZV3a6IUtHztqe64GPicytU0JCvIIZhaI4s1H6a79BBHX+0KoPP8YQXrZ9RFqzxoxwEqJqE0UxSINoD4V9L4B7K7fc3u2Un5o8BwOR8x3ux8QIXUFE7VOjGb0R0XvQUsYrfADudUouubNBuPH3pJpQfu6jOAHKjlDOmZ3FQLdnESzLeGZYD6poySlA6OKIQKqnL4llxP8q1V3/4Ccq2yQi0fX1gMeM+ZQYl6nQ8mx+/vfkoKzT12NUXpbJ1o5KgVd67JuH8UoPjP6SjKtrNbsBsRGLG+nmXD/f7328Zf0I0p0b4z6YzFRaHupXFqela3kjxz7aDKq8Yuozr4jXflfRbASHdF3xkBpsIXnoBjZcqk7/lUajT6KKWxtwgM2amjHAn/miz3HebezmXF468Pq/tcqqnNVdRUcyrXaNl5rUAEIFFyte1bzHbFobRbx9pRLV+uxH0b7UEJY/vtEFaEI3oxL7SJOK8ZyglesD4QHMOPoyGYD7bcfn+J7utcoZtiROj8r6obVPn19rHUxPxMvd+iSf1BAeN4Rpol0sn+ZG6vecosq/UfRdrkLROZdifwXztaS4LJq1xYCtetcaBnQmBsJnfhk6e2bE4+c4fuvZEumFgI4xIy+o9am7GTRJPrThoDt1H715bDNb4mxnCI8Hz4cmzkiXV54ySmaFenM7m397e3sj9wlbzV/foxGsqbbS9DeB7e0Kt5GbrtMQekrfSPc7bsddUrdZ3VGSvd7v0rTojMlzl7pwI3bhJ46aVmCD1tUrrEaaw1nbJ3GBi/fiD5AUcdGedXecNxt/FK1qQ4aIoH+FRrrgkL1bfEmvsuRInsaC5jkYRZVyjs7pXPAP5kajqzDU34Q2ugQ+mmfnhr+JuEXc5XrcZTB2nPubzvSL3piQ86RTzFxOnwTsYYGfTuRV/7qtyi9eRkXPtJTZUTsFDiFDbye9ABc4wR1W+n2ONRG9Fmu9dX1e4k6q2jhA2oRFdtDZxoTpqpy+wTnIF6rnainPeepinnpr4E/G89m6zAYQvnxGg8ELTMZ8zl5hQBJ3RxJednLY6p1EfwzzYEA4gimPg6wspNhF7j/4Y8ed+6h0eM4769LcpytXDJrsD9YgFOdyweOGoR04zEYGNpema+bM0+yumhpb/Ar3oPu3Fg5OUeDAzTglCTFOrDCAeLvUm4g8wsfrHpUBCLfg1vSMUxdh26VOeHEOKm/hnmH8Ve/XBo2spel5atM5U87hIihts9yVM6LrHEbuOh2qz8OUzvxwBlA0tWuVeJl1QsiFsjcqUjOwJnSsV+avkk9dHvlfeL19fs0RNzBr0cXJgs+b3dF77afy4qyhOfoKjncVyFISpC2DAZF0pgkjyFIAyqYWTW1mNa844C0XmPCdhLTqFxTS9xdxbdAWE2RuOiu2yEPKmb20xhk/EbsLuZuks+xRFFNNieDoK53zyRfXaCZWu6lrPzCx6mTnlLMNaP7UoSYOMXRTfhcsI/k2nQzaKwY0UYqH2Mv+pYlsg8KiXfbM0VQsH42jCgGJFtWyfWOozCRSIQOojaCe27ZMn6Hry4H6V4CZnAWoXWvYMliQSkOZDt0pDMA7tsuBcQP0l/8yUOC7WLZSkOzW3cTYeAcrR+n6cLLlyFEDbmwugMexvRVCqe2byziRuk38vofuLOezmv4R1KENMdnUf/CIGWlEj4JYm35teyvjRDhR6wlsi+ytqcANzE7k5T9EDtGsnBKg6Qtfor2XAcK/IVbql2ZTu+mG0aydGx5xnncUTdn6HtSOdw4zxH5j6ikvnfBFrRz4WpifaDvsUBU83p2uUtEm2rx2O2BTyJ9TT9XDln7E4BqcM7S8UXd25asjviYZ8NhzDxrSm6bNoKkqKwhl/2II9g3WeSZ+qd9JUOlu8XvBM1fg9XrycsO9pvUO+FfxMeKMEeb8IlrEXHg7QkH1YXG/jwVyMbsLGwIaAJTjW+djjbnq/dsLyYnmQRbfApqwyObgtTsKifeqQ5vLWeoVK3opnobhBenXMsGMdRXdHJK3OSFpFkU13wOcuii650rJJntXpWTWMoh9VTydctXR1i0Qedylal2McFD9UdQvE2rieZB/eYdSl+shTP8E1Pm6ox9JainlYrOJPpfXERxd4LsjnLk8MSS0s8boIcYQQcN9tS6DjkpuiON7J5Ei8jqsgPX5jlD0qoR69x0saIIiv5wYqChDm/bXABjl2VantrY0JSOiq4W+SmjuerHPAwcDxJNQfkF2nzdYMFJU8AKiWm9NRuubg0tOfZRmgPIrncsTQwPj1AOpZCAOi80+MUuLbmKKlFqA6l8AHYThm2WowK96cuAnojBFodS3u+/HBxoqsngmeXTJ9OGNrbGWXKmceEoLpySjR2GzhFcKV3rCaO9J55mZoYFimGqUjXszzIM1JVQ72wmEmUg2l6HnqhGVgfyGLLqPzfFTIL6SV1dtERvUqW9jFrt5yhtUhvWdW7p5Rv21hFevRC2WR7XrVajV1wweU8Nb5NgTIgWO8vPORhaSrIWIhOApwYUgoVpuABKpWG5sm9IOjJ+Yog0rciazFsZLLTp05YdSmAlcA6e1dRBnAKHr+cMnVeETIuRpXeqM+oEeWmdZk6aMkm/x49jsf/zzotJhkXRHl9w8pslyJK49bcimWCB1QVOGE11VWeEeF/coNaE/yWTgS2MwwTN71Gt9UFyGXmgV+E+d10SX29emXdq5pi+AxxD7IyVJNr/guYs51WcGpSsv8lZ5WZ8B+AMcdQkLwM5ghba84Usczw1/02oElVSfpTmUAqbLIlorxUCoUHfpPCJubbiuV73W/Fdr7VEZf2SVnFO9Cn5SyiQun5GK7c7twxTp+mFMX55F3mpKTVyIppHAWZcfuxwB5/Fec0n+YG0KLpyFgm0nJGqxrylFIAG7tQSmvWGFmYKAhtdSgph6VJCoYr1TjcMZXn374GaJ1FF2M4OJeSKvOsZvutRwWUEDfM/Hv5xsVAnm6reYQkoJ99mZuTcpPtptyWqsDIqoS2pQiou/6AFla4ApH5fLn37952HPao34SpTnKL/4WeXbadjLkhj9cqvSRaJbxZi0BL1Tf40vK5mhmQNJRZWgyGX99dlKDtSPQEEaCHtEETM6zMg9alJAFVw45DxR2t/yXWXtiR6/aOm/vAhDhqqkrrrISAnXvlw8T4ouFEu84zi9SKkXcPGenI9xp2FvO6NUeuR8cAHTIdEISH7rg/ernhMhbxpv2uNwE5+PVt3BLdDTF68Go0qsTv3G9JjFReKp+xYeqyE+0zrHjuopC9iJEeYj9E2V87AM84aPg71/ermnC3VxBqgWKa+/oyo6L2jS3/V5U2SKSTQVr7lMHPPTJsFQpdDLp8bQv7S5ZF6FGUbG8Sw41NmBEzwygtNOfOaVYuKcnX3zFOJti+13lf34kwwr0Vj5STp2kxavXjF0iDvtpaUUh267lUjS6sWUHfKoeHYG8sZVehSKzydhacenr6+ylNH0Co+k8tGlKtY0zTgZis8XNMEXfVjm7rYvtcJ7BMhkM3/q2LfNNcb+R48aurgsvq8Qzmb8JISxOV8lfsQpYHBnWqrXNC7jKyqVq5+GsuXr6zPfDy3hVvJh+LDWwzPEyrdiTxlErgzpnxyROimfxxSQ/vsZPEcPliZhdDHKru4hBXS5HUEySz4qhfTVqA/0BmVvPN/Gk9x+6h34TIO71MRkpBD2IYu7rVGJnqKWip44T889MRUJvaSkLju0qk3QUdJneeBXlYZIHKy9LscTEM3H2q3FZmiIhvhRu29NuDTn2lsJU9qzx8lwwxQ+o5IYq2nZRUDDLRQh89n2rYmjI/G6cWL8orWOHdQpffv87FWhauHqmNy2b023oYBzABh/trDvG1umxCKhLjJOfG9WnvIxoykFNdbDMG8dOCoxAa2gU/8xdrDtEPvxRj/biW6sXjqNbHJHVktduvXo2fYlGQOPpk7zh+Hvxk/5RqbaSPcczsZ3YabRiwIifDgf7JdBBK4aTqBElWL9nPm9cHfWAHrsaPe8p0GKCEg9HO3VSk2PkVEtuopL/sljOTf6CvCjMiXEaqIqRDjrjN+Te0h+QOxmbHWTwjfimm+r8+NOqcTWsN2J+ev/xXpwy7TJxJIaffrzBgfr6sor64ClMwMrORuEFjD4VD8ef6jTSh1wAWuNOToxFHy1OJHlfX2Vcplol3aW39JwbcHya8UVlds+kXf61t/nG9W3j+pGKUD5QvtBu2mVnmQib5e4KKIpArqsl2Vnx1y+dv+6W0WdfsUgXuCOQZwl1Mjy+2aFCwcxOklYUU5yI0zw+M2Q7RYz/AIjcSZ6rNrKIPV3H6nWDseRUzJJ/MI62qqMFh6PJ3WwVc9HpOK617edGKyL6vPVaTOfNeNZjuHUOuIkue302V+oI7XlsRH1Dnpgk04iN3eWkYk4NMEdY273kabJukCvxNjt/pL/pg88j8L3QlJlhoShpomKu7Gai7OOqHMAaKgsrNet0FkHcMfxk7XsRDbB26gd7+ePSyQpq9i29n745iTmrSiRl8az6RhVk39DXaDyUF0mqEBypaf/MYcBt+9bbBavhpxJMEe9TsRIToU4MxSDgfKRGYjtZ5iuJEwZlccHi/wRO2Tj4Nc22VdfYQkroT54oSIqhUMAtVUfZAywIdW4Psf3qUW6KFy+mJxElMWu5Vx/9x0nmIjQGi15Su2vAt3oIM8s6gKeMr7KufXxbHo4XNPP6sk/mX1vUkLmBahlE7pYQUNPz3pDK728pAbFPlNlMjlTTP/hv/+l/Q5BOzYeWzYIm3GkIIG7H/En4WL3/9debFtl8t7PP6qx6ucbRsT2szBtFNRLvx2jNAVHHhgB0umjabP+Xj+xpbfvdp+PccDzPttNTH7pNQhXlxlzNUf94Wsy5Zc4HLY5l7Qq2923awWy2oHboHNIQjUGyDLWFM301Lho9vGi4REt3ALruBOvpZo1HJkaF0XzYX06HIZLi1XbUvZ39aZ8PtjzBiq14GjYKKe7py1R9m20r3G7sJBsj/pVA9djmWF7tVD8ap0h9ZyIy3sJRM3cP/TstBXFC5dTCASa5vMJjNJkr0qVVMMhtiiJK+ZIPT5bnEW66lFaNrfLTTurLWPRSwwMRj+UCNYWklcEm2ZjAdBPmrpR8ttsD8o89+hCUTUlSp4t3bYTHl3fh6lrzZQFqGuzqeEu/+6b0TFJvMs0cXBV8oNfGtOk7+/TUfMnU79DkrTbP0VabIUutpB8IKtBUWpWt9WhR9fQ3nV9TcWNpkvVRHSXgE2xj7ECUml1U7U4Zeeaknm4zZB5ZWXLO4i5VG3q+l5RVxskc9bgLDFjaTrAm7C6hX1p3LiXsNSr4SR4Lb39Hu/kTVmJzmtUXqSdWm4gKUsikSqKqxycJCsdn56KwA6b60gPZ9FbizFEd1tmJ/Mf7W0JUjpMQmWq72pqacepZPmCbludyttBhl93lhYWf2vpqGOP1ffRJGKtBv7YdGN97dJ/2dS+AdEcaysRyt0/7lk5+edTXpJ1FA3FzNMxlskGpJhz13IKK1FLU7I0DHgc5dRIQ8f6HcsFojxzf5cw5koS79ETSaBeGrZFR3njJhWfFLWaa6tMw4wDbU/2EsKd+ipMuLp0+t/rybvoePOaML1OHybDBVQxrFHMWMeiCSUBU14bxRYmDB7t1VOFhrcZ7NBYm+nBzzvxtWCvYrWXA/ZqJJ9zd8XM2+FlP7qGBnfzi4aVHtU0QPpXqu8bLnmTHdgPq60Vlwkq2cy7fevr5huqCGMzBtkHjjmNhz/cifcN6gBn3QbMPNxq70Vt+czGUomy9us0uvO/vf71mhaLiAFgx/G+qWc2K3CFae4CPhZq0OmV0nRjxyUhMI2OlzSEZ+pLbUs0oTfd4HqyxAxamUTwD3pUoxF6Nak9XWMNlxuccFJ3rdskCQDgLCHw840w76UD/VTVzjcsrgEpV7662tbq6WWk3KwyBWOOnZG9rCimgcl9O0RJSt1cygNQRIJbGqqEb8ST+4MkRWTgfWuFOHzAZ4rn/EtGCsUyx2SHgORkfcsK6mOIC1wnbT79ThBeAwHHBs16JArf/rbsVrJoVnKLfiKurrfK3TUwo0V1TRicnBsUJRxnrRkLFS+dKcEtw4izc9P3Hn1GRCa8ji364Xw+bE6Y78p1w8hOC+P2OcvD9z7//erHRobWTQXPtU+3x9hfInod0K0Jl1RRa4PFJa5JSZ+ag994uHWKc9+nBEQ+PKFlFskBe3g6DTwVB447jys3mklaATq36LumgFtsv3lZ5DxXC8qm7KLnEVCslmpGkrpp0FwiHCqc8mBnYRmgYVD4dOc84sYD04PI9OevkskFcllbXg4aebyzVhWYRqqYY9YhFqpasWtqGmdRc3TiKZEvf4fdFRagUVwv2bYOyUEaZVRj9iMw6HW70kL4xOv93Tk1LcblhmDGIYq1RUjyP9x8/jFbpqNPh2i/02LpOZ41AQFnixpibwttu55Hx4oZOSJf1vbA4Z1yTbsKgSkqVVRz4HUWBJmu6ytRF5gSago3rccUUUGQofGLBOOc4FBixaifPSwqM+jsU73iPn469IaZzPsak8cx4CxuQPVmhivNWRo+WCMEeP7VZbWogBxXXi/Eb4xEr+Psuew3P4aKS8kkcj84Z3lE89oXgbmbxVrKOBK8/4sn+phoN03DHor79nhGhIp4PVLTpRIARlntOcwyf6ecogmRcOJBs8CG1TPBqHvvF/g/qX9EVN4ZDF83Hx4d6T338L6BcrYup+pK+KpolhjydzqZHCrRimQ8g1GaTKDhMiRpqEDRrdkULmL8AUUuFEgswbvlntDOVrnj1cHGSb54tdRhpwBq6iTq30D8989dJuatueP6COXGtzMnOgn6xCIlvI+ams6fWOFxc9nYZmWnCa3SWcRjYuX7qFXk6fXPpWvHeoLDhuptUlEkKUa2IyepZMRsMPc9nOy1Kvqmfk9x5Xuqv+eZBwu+x9uLbsen7C2Esjd6805b21RU1Az273lIUxina/2OfIVBuW4ntpL6oWNWOu8XmkzXx9XW69QNmFiKcjfdMDIBSk4kBsIBl2X2eKVwPN6J4DpIFxjuaUg6osubCwE2pD+JhTLzC20TrvSKzJMlrmmzzYu1w3DKdYNAVI2+jtZ2GJJpAXc3t1QmPn/exrPnLirZ7jU5WhJCmrQqIPuJ40MsvYDxjXBKItxeRAjIAyZUC547iDtQogcpfT5wORizVzEx2dKpVca/dk2kTFh5dmUo7IVg54ovQHKWA9nED4FQ/NQB3G8ZMmpDWsJ73wcOsY0olCU4aD4wqMWSrAtNH4PktFpliPipr3r7Vmc/5AugXdcfPn3KKtAmCGHuCjT0adzAzd1quMc4eeIb/6B0rRfb1JiLk+/vfJ8zB6Gjtr8EQzDeNo0OgeEVL/Enc/cfpN5WF++TIFd0N14MC/lUO+Fi5pqNPWv7qHOO6v3U4cGhzY79unGcu9E4dlJrUEx6vVzpvhj8aa6PFvLeb6OwK+UZLqZPE5E7IGOy4zYYiYyVmxjEWzVN0EtecuFFoTDPhyR9JoURcUCHoVwVxdfU3N/JbuOPZ1CaRGi0p9mFx9em8uMWCGvul5Gbaz11mQLYaji1wxup5W7ouL3UmUwogfB4SxKWEtlW0RcZmWru1xSL6lWwIDW9pozyZSzi6nj1LWD1+vkMkb7uPuZi0xMmpku0hS7zaW+PRwZ7NWMaKPETZkexMl87nzLnSOclcXepOPZhHGi+a3FRVUC0F5Kn81o8cutn2QuPdGerAC63ajvlRwYuVZqrzXEkH+jDvOd1Ijwcq9AtYnBaS6P5GSjWS9DLppCUyweA5fGQ4d4pdoeJQE23wM2XEh6PMvcIxR6NxPjwalvX04/dNwMC9I32h5+C0iQ9gxNxW5j8vMJf0C+Iwf3v5pel1dsrdUmU9S+Ic//6n1uUDV8P4rfHVB5XnoBmJV02xBSbk+XC/14zKktY/Nja152G9DIShwwcnx/UxQ3dar8tOctY/9l7+zSjy9PF+RL0QBWV8jB+GWUefQIt0nyl1kYq0MSbdfaS3CYkMGxFHG98dn7nMYTLBzoKxc8/R2zmeUZ1APQht/vHXm5RXN0OCCnCJ26r6KPHQ6ZGXdiz3WUx5iLSVed7pi7CptZEVvdqTCZqHnZPMNTCXI72Bn/gF9GNXpmNLe2iMccvWfj4E6zL/Va3atukcGrv7MzbFgF6Q8Bj7zZEkl84FQmx14JpFivBoZnxpBt7WFbGh3XZpkiXfhpcuPknR1ywKysYfmw3cYbBun3MdbPqRT2idX7rS9rVJHuu6lWEhzeZeRHvyIxaN6CqpkQQk+q5yDxJ68hE1MtxGHu46Zaqoog7MC6mW64FJMBQS2emhAe0mR0KQjUVZAfqQPnxzCltNF3tVXxdx2PpyYBVA16OLFTTGMk4XtySQRfXWOQg0zQbEK7eWdNqboYOuctWQ6xcv/w6G5WBYUn6WuZ5tS/4yT/opGYEiJbv0iry/PEAucijYbR4eh6Yt9aOw+gFM/nROiHde/INPbGvXA5q2nY5GMlGNRoeiZDz5A7niEJS3jLsI57e4vTds+JxgJhkIkypzJL4Ra3OQDw06nS80OlBZo3rATGbIG3LosiNr2x/+0nKC+ePNLl0r0c/pB9R8J8U4q3WQAelZ4nqZmusNnXQLnHUAddKK7twFNsiyzlsE6miXuh0To414wBVV8EWE/us85fbFn6Z+alZzR8O9yIxCSE0HkahqrqIkVa1cQM28qBnivWxNv7xnF7A1UhHdpX50Dq5SdNH92uuAIA9c5b2ZbcrGeZB7+dmvh3GhgcplMINBsRsLbg1lsqOBZmcUKPaCsqzq5lRhMNHEFpEYOdaahRi1Jy79gp+gHChlv5isJRPbUJLmXHI463ACGG24x3YJsERYZjZ/mfFVXl+aB5O0B/0iBp+CxY35DPGVtW+65WYy7mBTVPyDaEei5sIgVOZnDY4sKmQt18Y3S9RQWQ4pUDMdzRqbjN5FYo+XibF9l1RxlcCLYP7RF7Mlbv/kim9jbEFA5MPFB30anoF1uEALi4fXU3WT8y7Z24Lh+VBhw9suvhtWYyrinrcLC32CKHtR7i3DA12REi8ssrlPI9CEbXt7JrKNkN4CeX9YqJFWK1onilCERhx7E3cCjRIgkFcYOw/ZtihXQ8Qz2V9Wq81lFoEO26zOUWLcJQHsbzd37ORYMErmVGRhHeXHDtx3xVQFnD5egaw/FYsOQ58WN64+KMuzyGC3WF3gpcN8I7TWPXjVmqqmou7DzzOdeNLSTz9DIJVuAAoUde0KmM74FDyw1K+ukDOOwZGZl8vrSZ+G5wKz729N/NRq15CnpN2Xa22swTqV3OrmBHB16ZZr247hphlSSkwyV8Y3wFBre3qsjZdzqoeN2AxOfu+G410OjsyOroagokEMqmqAiYBsds/DHDOV9BWI9S3DP1RyFSKOb3y22GCYB/Z0D0c7Dh+ViM3ffrylbt72e/v9nl0qKjTZXf/v6mezJ71Va1mJjntrPedA2x/H+qFjsjc/GmIbBMQlrp8TPWV0EZUsaZTFLOTNoN8w0ivQXuwM5Fag6JQQmKbo8XXn2o1XrK26ZNUWT70t7lCUp3/9rawi3Rjvv/+E5Kv1j9ldlCWzReQdPoK7HPEylSLuP7naOdDAYTP72uYtSK1eKTvCpiX7p5M/Vaj++PPt9Ed0p5I3zKN3nrzio3TPzuUijdKdIa3PT/UA6LUxjtzJR6wWH3fTjerK1IVlRibnEC7xKipOTFEGZ0IO4RWkJW5XOWHJL+3hpIb4rptooKNL16gexQ5pdzAjkr57sjO0ZKEURS2rIUaVp2+2R/xVag4RzY0s+SVhSXvAckeiqpVQ/bdOdEuTMBFFOu2HrnA8V/TRJiZpISkNeDYf7YLg4gN97K73BsFylXOnojVLXOecKPxQpcERQwPRL2TZR9hRBw+VdUJHoUoM+yoNq69UEksJ9VIwhTB6FTMYjyq4Xaloq8UiZjLprJ8T6ybKT7+PmdUvKz4PyzZmw3Efx4EW78+QnWA5UTo62IwmRYk7kbotCfmKAblExxoMPeEA9oh+0g1YX3nQzFyestHz/C2ZwA7WFWtwJh+Apnur+vifUe8XL2LlByTlDisS9AH7VjwKJ0KdBpXY1tgmWieXWnoldbYjSBT904b7xJ66H1VAN3RmJBLeRaiOJ5O+YHGkoXeWaaJgWUZtep+6O+6pKdH0/yJVyZ2A+I5/6NRgg3qqKKY+6tKqB5aQQW4LKBGlMyLP7SnTu673WFa2nlVvCKGqW7X+umUqan801joz7mtUf+QT5Id+ii941sBUdR3+CfGc/7BbjA04o983ZnZXGzKrxGtT5RSrA2YYBH4go1XWTQXTACFRnz5E1SSOiUZaCP2qcy+aA3ZU9WJTJcd97r5/0tJGZlng4JUlAj00I12FWtrRq/RVVi+H4D/zOfZ74oLxsy52YoJ57bP7/Y+fau3GesaaWIa4ctnFXGeCU0++YvfgGF7iVsK2Y0NNuZp+4vAA/egL8aj6oh+pvpusHhWIpzP0t/h/FbYyTjqsN3sAKadon8BMasEnmLjDhBJsX/AKCGH6cXubgY9joevrAlnS8ksUx5l5l/PRFMSpNAJSu6SDQ2eCjYlNbTc4e9Feao8ds3Ac0mULS8K21/vlKmW9JD5EeMSps2jYqVsl2rgdzjOKhvU048cwA8fACY6+CHupAV5AnE6xwP78o+iekvpR7c2e3rCZ8+vm+YnT5TTT/t32qB6+nqfUsyI71HCVMbW9VdbqYfsnUkxRqKQrcOoR5WIGwr8wmsjydimoE3VE1PQSRqcbBlbyC7MPgzX3TmI5xXqMp18zNstxaB0Td2UTTj7z7bVlSYfmkpZ3Y0iaQ5ruMEnkoNfFvqEdAworIVq4CVQH2KCIRbtAQomrpi0ex11n4L3ro41DeOruMQolmZM8ZHtktbmsc3/8gV0W20mD7qFzfMPMO0CTcq1EwTxjlhqFgUCN6qO0zvt4tzJSq3M1EbRiwCdqaA5kM2tN7MCEJl62dSDYS+1yg88UNf5FFrMsZMllqU7jtPkVR4qNSKVQlwkt8MhzddB34SJR7wmTFAv5CC0RFiG30agPipqE4x7GegWiassjePZNlQKteIGkecTtFQvyVjLMbNvgm6k1k1mAkbCtJLGa/mnyXSrlnCGwyniIzWPaPwtlnwYPt85OS3LXQ7TMkfrqWF5P+ytX1v2v6vrNmUxagKm9Mr3biXMWLQQqEm2cLmakMp2nBSqspHgsN5rTq4g6qqPnH56CmB5uy99/+5HbWLYM37mS2mKdE74PgmKFmTRW2qXRh7v56E5DRrqZWn9XTGY/5PesnC8VhXOv76KQyqG6Hr9X3VV0QDvktEl6EdMScVSaESpoT8ZZ3Ffy1pvliPIVBWlNAkAF2MRhEv/5qwLcjWMibV5WIlYzPVeJDD2+77BNRluCIGYeylAjbsc/xbaUl2rsTjFzF5t5FTMa7QvIt/ats+numl76ral3i+2FRSoRLK2brspUJcIqN7l5bCXzrC1+bU8m7/tJYuKMqRyKeoBShBNH3+oHAfVxJm0iZ1wwql26Ej2AOu/hfbOrSD2IgI6P1H/89iajgFiZM2MDRDTRCsceThc+R+FeO79Z4Sp6L//xfyDaexYfadF1Joc9kJlTDzut9+p73ukR8T/+3/8+T6jCeASIseHWDchMbcCIO7F7B4AtDTH2VoKCoh8QFennT1UVk4bAG3ryNrMTkZUqqnbmEr9XONbvckBO+OEpQNVI4nUXzAuJFsUrbsra9JjhKO0Qg5e1S5fYFd4dsR5i2tfyR4+q4QpEU8KY7QP1ZS7N6NFQGQlCN5bOQ2u9n4fkVYJscndE4S8CdO/Mu8Rs9d8aG8I6UqSXHrsZuVf7x+w1WbQvnFK4kjBarAExlSu5Cu3pt3jxIv41G0Vq5+DG9ZVHcGTf3fB2iJ0QK+lm3/GFBqFe0sBaLidCCVA+nwmevafHgKNjJdToJO5Y9XE/rWW7qmjb5QSr8dWlvYOmLT6pqaJjycfVdSt2plEZ5Q6RqDJHnYvJ4w8shHcbGbdohMZ//1/wXClBmjazXxk3jPq/l/spNiJR3fd9SvanGOEUavpN66DpnQiXImTGP1A/jPAFJHOFH1+wKBWnwA1I+z761mN6JxTxLLprdDgAVLFUrtVigI9BVwePR2OyxH8HCZOXvujBMiGIKi9+r7wCOstab4JPq48iiPvqrXdWOSRKJHrbZoH326omEz91UDbpl549JCbCs3eXPVgCkNe81k8ra1S89NoyC/tmPgxiVMFe9l+aPyB8J2pPdd5eM1256ppS0F930QnmkJsBDzxJwGU+qGadIm7qpepzonk6cQhFJJXhQ2DnnPLcD/hDyjG+SgdwUG9krE588zBItIcbvkiirpqPz6EV/suD9tSqMK8/gFIQH2wr4y2LspJ3MOOTnYxJ4reGrI7EWzWlcfDbmF6cphMk5iNTON+QUo0qrp7dJMH1gU6WSku+60uvulU/CLFGNa6ZarVjI62xLkb2e7NlCMOgcR4UsYVl/kt/oXWVN8aeSXF06zqBH3HBFYqg1cP0ZYqvBldLRvjir5iNJGChUj8jky85ufSZ8njGJHcobLuD1DT0yYXtDsJh5nU7ScnZPqM8fHEd/odHne+xmWAb0m3GQRRnbBxqp6/rvCt4lW8AUB5lqG7Jzx5oxmwsmEwz63h9WWXp3X765ryfT8oGlS7uh2xnbeM/wFtXMqekMk5fM0YazXX8nPmzb7tSx5td9tHLEYa0dbns7VA47TjrQzMOhC3pAMLAASq6Bc+SeJT0GW33TVrcWtem4RDoaNXEQ2gENIrEdscvQgqzXpSRon5/OqKCWmCxv4dZU9eojCUEsVQ0wxYRYVfOku8hxtyrocj3RB3UBa14y+o521V7sh8ijsTqKhed0uemIYhRfcaQql0mA8OLFMLg8Rznhlr6X9WtEjEDU/PXSE/FkOJcGYII/kvgy7zl5RaHvhxUR9Bhiz/jRGtxwWSYHAfUc8XGCsfRDNVTBRCVx/ks0/FeuI8O90wHN/AvFoTMYVsDaFIo22PhNBObHMXEKK3ZdoT2rNU4Ps2/7DhHpBcWDmDJRJQr+G9vlBDqOcvVp7ekB9jJS1sXqDhhDa6xH9KbxH+rODPHZKw+T8WptsVLLP70M8O7LOFzqNmoSqTS2S5Gh8CjOMZFwqRLZDBjDoo9e7HEl206iU/bfbbWM74dRvsns+x11ku8pG4lPSLkZaHGK9/YYpzXjK99YQWsjU5ckesMgKgY++TOSHGVuQ/Jop5RkYhINC+M2G6d2kPN1ONky6UUV4TN5uXYRDByLH3Vjf8DoNF3G53NWtx7lnF381QUaLGc9qYHoOPDv//2WyEXlQF33S/b1UiwINQKJcFQOyENz5wKkBcE8BKr0IFNGW26ZIAcIo5Mz7P3ozRpUEQWfEajiDYWpL9T3KZ/7SobDTvJCvniLfT+7pDf8rRgn73M0wGyBc4mZ53MzoqItPj/cU7/+//4jtcnM7O76q1pYuKAe3RyHvWqBZgMaUqPdxpQSId9j7Uo0ed8S62mxVtkVKWmZUiF/Ae+D/pjYstJhVxdYAIAQF4qZP/NLUEzTZ/vmjvOEq9dMKzaroNOnGrxcFEEQi2nbyPA1fmGvdmt2nKsQVY0/HOLlBQeBTbVirlmRSUTV7qeblVtPZsJjc3jUMReVwY4t6W6KczYKVmbs3oETMrjJWUd2+ZJ/Xx/pgMZU0Y06wlznHlrZ6dOmEguS3jelKpg6qxbb8se/iKZlVhgVesrvVaJB5qgqoXHKZ/Q7mjj8HPe9smtoxbZZcJWOy66qHTEeEXPt5RUrhkR81TcKoiOm+88h//6XzLGFQD04ZlEHMgL5fKjvxd6ldCw7f8X3MJp0J7ueVpZLL6lR0atU3DaktxMylbqDsFUquODo67kwls9CnvaXBeqHV+wcPyIypHQlKnWZtkWBaTVIvhwjKj/4mHUDOpRaOrjyOvt2pMd21P6CyYQEqq6MWoWXaT6ckX4v4ggoOf1y5EOFCzqN5azQkGi5dpxA9JkYKuSMOia2Bd21Pha1a+Ycw41Qql5ZFvv+ErFnYl57VeDH6dcJ7nZL8xN5QaA9XWU+xfxh7vWHjB0kJq8VJQ2cRRBZ37AqhxfvkP7hHeA9uPu1PCoIKoG7o0UZOaNCtZYXayr8B+sNii6ijg9348J/pDMKtyZOB0OJoTEcbLOdCzU2n8WUVA0baKUbs7flInXKLV+MaIj2AXI3mHzSS23MDlO8QzbkxencvqKKaQGycWeRKZsC9bXXnar4Y1/9GYuyRMJNrPEGZclR5H+mFfI6psG8PHGVCUwBTtMr82o3kw51HL4BX25d8lPdxgfMy4sxb+N6E8c4bmJ+AOVElaNVLYDKeD3zqUTHifdh/IFNqyo8nmtm4kIL8NHDwW7FIv7+QpRG3abjixLZhGtDFBv8mOSgnT3pIVwhpHxUtU7nknWxfOauBNVdZRUcu6FOiuOg8qye8aKnaW5ENUQBECvesS5+v333wFapeizzRl5lSuiPvuUvWIgnT6fihykPXHpG0bTVmrLoRnXt/bFs11ia9jXJn7v1eMyp93qYmUa9h0ctTbeC3HnEsMdMW6CfVjVturbmCacpLKDaMAMpaky4dEEr7YrXAL9BSzVZkHcOEqVzC979ei08hshuVuCNpXRCzVrXFO6jz/ht5ZsHR3D8mTWVhTwfe++hf6seW2+pEiuanJUGqUhqO9yfW5X7RLNumh+04hQBGKiT3C6sxWA6Gn9hUYPFtcEiVckkWiy1tUxeZ2BSHmtLT3Yq0B9D/Xh0s5iF8+k1U1trcNJzvVERqOcbGCaKXZWkaY44uQxAqF7tynB4LfDdwJnUpWqdad2ChJhNCLKm3iOmp138SUQouBJbaSVzDOhqGMa30EutxpMfdm107Dcd/Ck4KsSK+jqsRfgK8ZEjS+eBjvvP97eogeUkqbKO6E2Y1XyNaGmNGBdu7Ob04Ax5WmHLqvtv77i7N6RoV+pcoiAYDB3lHXxxvHDNz9yhcPhM3VvtlTxL6StDIU3rFuBmc3U20nUFKURBzyp7+FAULZY9cZBPc1ZvJ/j6QtLFE1Ya93MVXWdd0cRfPSu+HfDeedZfjU3vx1BfYs9aMzVR5044KprvpC0MX/E81PyGmnm6zGRhhuFK2NaDZksVeiv4BeqFeXNt2TJsbwYEedBbnekoZze//rzbcU6VteBR1h1pfF9R3mDAEQTkQHbKYLochC2zq0j/U4kO+ox7qOJLek5DAgch9zl8kw9edbcF6lAnJFMUUXEqooqYABYhDnyiPKRQFEN/WbrAS5LHtbkiGz4OXWN0kdtQgkquMphUf51xECsSVws0orN6twMKiHxO5/ejz8E+TMqAXekcBtlcjCBCIkIIia4fNCaa1QuLdryxVZBVhN6SYorujCnyQyvbw6kafWvEqZfc7lfO4W7VZ9HltjksLCPnooW2GBgcgYQymMepQ4asczU+cXpsd8ZHJsGTMdYiU1YcU4cpqVHrq9JYR8Z1X15SQWUDlYLtjlGXQyGFyjNIDI5CK8+TlGwlb8Yd3VvYG0m5xYYT1pVbP0oWY5FsOCgLsop94kCOaKQx3BPhRMCAkLGyDbD1/2Fj8Bnjhtw1qDtzyjiH/p963N0WnEcV93px4+fWF26IOsL5dQPRVWsOUe1/64qj3vs+Wj3OjoTTb6P6YLa1clAWxr7Ir+yBSLVdRcL4vbMMC+AzU4uS/je+cZPcj1m/LleuiJ6vMI8ywil4lN7ev/5I9aw0ARNMDEMa7QntjlDKScdWW266Z4Hzxoa50x/C2CC2+nZhUeG77/9lWppxXvFs/ns+z4OCuVoqKWJtSS5ioiKsw1kTh4Lr7ri7POq7CtshmsYkuqfUd5l5KZ5uWCEzSkNUXUfx+r88ecmHq02ut3TPRR2EZN5XbGqRVv66+2kzSXpr0RBcwlRS1cdrpO5bUuw4eKeXpNrD5OjTBOF4rZe+qRuLGQgXzvFlMgnpaYZU99hvs0W/QJkV5tz5HKNhdIwppp30DTMAMzLzVhAu7NMa/ZaZi6cUReu1TiLT7brGCcLYyxz98Ro4IN8Uct6Z62jYhWX6ksS4N5Hb9/CQkFixyLWlXma4K3phPgQfcU0MVE8ZxX2GxIN3bazj9QZmdQ1A8TQJWYGk1Zmdbc/oOfJY7oRZFxuCfYl0uxwMpscwCQtQDpfekZPEXI+j7BM2vlh22PbK4lus0CHjrJ4dLiAU6Tv5BivQ9epajsClEWTkhd/1SbPUhZv5Cy7G23niyUT99cUncdQ7phX4/shWo3wSxlSpzcYTzz2TUci3aZMy/pJwqxeif6rNVZePDHiT2u5b4fB5vtfcSUMeO3Kew2zYIDAA16wH8liRWMywM5qs/b6kEBE5d4K5Fn3L4Cmf4LAMbRWFXVVBs09Z79DWyX54uWjJ2J3PLGoTrH5YkucHWuis1xnJwJ31ZCzxu3RURDuLsRRiu4MMT0ymPXZbr2zoz6gOKwbLA+Nlm8d6gzZ5PRY5a4qJgrl5v2337FAcdVfZkFai9ss0sM+MY+hEbHn8gmzuf0sWX+8K+7QB5zzakwjGe/JjRRqBGhs3Qyilu++hlBLjnEGawDOGTcVp2wGKajDUTrUmuR2fzj1Q59sYqJf6uqKoWRjc5FzlUaTtrg3sweRjkh2R4hp8l0W24fun4zc+jwgVxsvyV/qS6zR+mnW7JdUPutQjWO64DDpWA+mOmrCSXGYQ8aBkgqV4C9S3TEObibh1x4W81KIxi6ftKl13a2mWTNvjM0t3Ge3G5E5BJr/6WCNcmoqRlYCQZ5E6ur+U8xk3+r8UTQ96aUqpLani9EHE9J1shlA6zo0inEjvojnZeizDFLPm1ciSY5tGzGbglc9V5Bbknkr/900hHKO/W6qV+yF6Tm6ep0fq4bflUm5QMT3ErvuNAcGa53ttsgh1fSmSsb17VrZls7uBBIWlYV8U8WHd5rcHEhYF5e0GyBniihv0TE3Q6pri5tfDsaEacVH8DCrchjI0npIeE2xy2ZRw2KtbSUW4qIW8AzsCpqBCPhD/cqHFsNY/YIIjMURgQbizxnwZ0vEqtiZZPYmEDWZAkp5OukxNQs78rxPHBn/8b+qN6kR8K36s79mBXQph71+sjhEDG47l4//9f/8v/+17Mv4Q6Nifwqk1SX3B5bfIHCt3BbEu16KBchEaqzglxLhgX+MKyfN3Yj+ZAojmO/2NLk2rhYV1SI0zKIp4m+33nxuriJ8qTNrisyD9S5zizS1FANCkKc+kMaG6M4LbaxyatE0Cx0c1rTKhh2ApFW8VxuGdWRGC76QqdjM8Ckql9/Eueq+dlH54qoCvtg7WHh11y+7VNS3jsGlkMuuaL3F6sO2coIhEaf4lhJyhL+r2WaDkUc9IYwXe51z153heBSLX+I+mGjcDf1YYAqAGQlMZdat8wVHKgEhT1y85rJbYKVr5gmjwDSa+Gdx6eoEmzSqFc8t354uDfFANp1n603j1ah7opgcklJnn9U5hYWEqEUj03VdcS+1WUjvTzk6ae5VH/sbNrf9Lgb1LJQP6WI0sD/1SU1lWWAGyZmkWLxbNHBDdacgo610DzLI5fXusrWSA0D00fMpuaP49BYrRadanuY7o8ooJSErPe9X+0r8P/+TLkV1NyLx9dW3PAhDZdbDGtinn451/GXbweVl5++KjqhvBDOxZDWqjB6PTiy2p0HWNS7UP1TA9MrLLJHLiBV6ELti3sNNtOMl1ufv+I9/+49/eyWp2gGUi+4faDDGy6iKqsRmpnkAh6rYLh2YVc2kaiWZyqfRMj9VlSIkWa/EYxk20O0uvkCfQSnW7ca33oGX5erErHmsGinM4x/FuQXrPwplqoszHtbGVZUbAXos18Yips0Uq301HdKoLReJJx+SNhhmR0ZGDupYGdSY9mS7y6wE+j44r+8PiSRJYDuxQ7iM+kvS8zkBoIGl1UCPu2J83yxOG/sAzyuTQkHDk7CQ+3WB7yzldJk+biBZE/5Mi9K6Y28QJYcviWLydlUcURRHKfW77IcGjafFKQElRewT5zKE7F34sBYy0+Tl6S8cm7f+Z2NBGUel9zmdFKGKoCwtkteVSMBllCZusBRXwzaV2KN0s1Eg70oe3Kco5yXKacgD2Ox/XOcwoCqeePtyuZ6UJ5KplPHopxLGoKPMg4VdIHd3JaFND/7rup/cj1ycXHMvPupuNjlO+hwZnDsO263HBXj5VH0gzNjq9QEGTOdsheTZkTkQi2p13JE2vlMUpN0YjogZ0oWxF2ie8sZjxm6XManLJRRydn3yjN3XxSWA1lkjeGdkt62SzdfGiYj6xVmhxLG1S9buKezg+KGOJNBHn+D8evrxF1MM+j9iPu995whGlnYhLis12vawZMsiS3assOI/PKr+x96X1A7emgah+6GvuO1La+cbKaz5ElG7RAdwFT3nlhCI3Ww6Cfcrdors5l0SS2LSHdHkcV80SaxR532zinA9fX7YL8RkWp8OouQsN5fC0TehU3lStcItiRO8xaiSk5kGNh3Hj+1kurAK1xomTJ/y5smGrtagfJO6GBpwMEOPDdY8XCorwS6z4DkhjK3yjCxW2Tz+KPBX4R5C4O7F74vtg7axt9lHzUEr9bgL297wNUo9DcaG53jXPXEvXf++IMagV+oesmWtrA8TCjhJq2ifGWOhDY5E0qppcxlvmzU5Mmkt59U2VhENxiZB2QS3sHl/zZSeFdgOJYPY6uvO+xnIvvzzr794/HrPz+6uz8DQwU7qTArvS3VY3F0lfRfVRqQR++hOfWrdNKRR59LGqfclF/4qtnkli8CeSPaiJvYM1bH3lrViUdvbBD7HwEWWhqf9evd1fFYu4SkZueW0O6ThgommXzJhiDfeOQW5t9uWqpU0cB5j4RLwXkHPtMeJhBunCtkHpgTTjmuUqfjdKzGOAHDl2FgjrCM8DwzHJ1wqhLFN8XUahFwMc2Vi4YzOV2JRax6piaZZiv4MBLHFppqhhbwU5XVtDBMmHFo74g2wPrpVJOQyqfAc/q+fb3DmaeMSKGQjnEFjHWxv27bWeBblteTtM1LBK6HNngf/f1S9uZIrW5amp+M16gViOtPjbDgccA/4gOsDEAipO60HajSjRqnNSIFGjSyyzaqFbqHKSu3O0qpE1pNwff+/HHGuknnz5jkRgPvea/wHuG0qD8V01MD0hI+5r6IFtM3lYcDt4flDNVzv2BoYEoMYyzLvHhsbC7AwvowUtE45wo9ww8Wb0D+YG3lmeWmkAkMW11b9Zw9EbLkZye3VIjzoyIi4HonG0HqTex7dWObsVFV2KhRbYfUsZUQ5wUk8xS84zrggFvaMhguIS2ozb/qMcUa6HeU+SQOJzMkC1elNbOvnC/bigqPIIGt1H6bB1QhV0R7wQAhy1pYu4lKFWH7zOYuof5BH93ADxazR664IW9IJtr2MejBpp60Fyn6V6MtQCAYb4UbSmdOZLNiw49+cFLpaAooXNEgFMC+S2dnvaHeU/sbxGPHjp+CRghbw4hiyrF5ODybTvfMSNzsfdheDq9hFifVQfzwmPHwqQL37zXskLYI1ztOCG4T1JJxrzpxEKSo7o0tRaMS3FirlKrxUkVeKNKVwIPIZZMqkK3BFv8ab6XuybWQOH7X1ejx2kpREg5301JXRa+1TZ6/lodjyqRMFwkNBqBEuNcxHlElj0oPBNlCY1nrgoLI/2l7YCLbfHVo2GuZFDVkw+fnwkf66Soc0gN2l4bwkUKTAjKfqHM9Gwxu3Vfr6iIvI5lSyVIZC7+XnzOgvOpLqYXdJQGql14P9qyVZaQdPnpUcsV2dharnqM21tUfjzcMWr86yiRqAYMB51TbowkuTuLD3nXwFABCL9ejawYXboEkRvfzYWbw5A9doUhkddNm70fYwV37ILZpql60Sm6NgJzRFtdUopayzteGs3yE/BGLO5CAhNdHRVMiVkaMDYjvNFuYebECvmGGViinvQDwA0Xb2KAeM1NGbN8tltV3ExXbVpTMdOOoCWotPY6ba8aDFeqtRt8yYVZEpMJ0U3IGVmCk0Cmt3qxxaLFphNbHHxEyx5QyMNwoP8XU6VzfSp8I1BOC39hgyc4gzvhcMq0utzGiqJ1lLzAkauIG2o2YCHdsOOqeXSRoZUbYYJ7/BANhSWEhAXmzRLZ28mdLavalBmDfy1O5rDjNffZy4vOWi9hkGk0ofgNSQoLCtY5a4+YvES9uwD2lxE/8eYguzV60/4kt+yaa5kHQBnY1IhPZ1MAuyayUcXcuQs9+Q/FWHxIRMqHfPP78/8ZD+5T/w5k6mcYvjfhx5+ghnmlYoIBSV76Xd2vn7+eEDn6a7teQtm8VV6t3yR9tGqtvZIq+r+U54PGrzAZorS5hutFez7Qv51UAcq7ZstoiuyDGyGhqt+D7a6w6+v8TW9kbqXQF9WF9TS5zp4Vcu5bzZYXbDB4IT3upvmqZcLHxVJ1tZ70z6GCZN57se6uJmpEF5/TduY+SvTOibE6DEw9ZIYB0r3hR/int2RqpMUwJ+0zGV2bR4BOb9KC/iI0LoA/jbIplAZpOxJ8Ma/DJVr5PkZMBai2ekawWkikHAZLCgmKaXzc34kxZqs56SD278Idlrc8s8KEIFVCyZXt7VRfjpun9IrpR91Pxtp8CoyV5nuMW2PYdFzMyilpwU7zEu7se6s1pXbTzg+xk9pc7aNlNrK7tBjQfxV9hr5EHE1oj3Z+1T+zlwR8/A8FSkdTtsLL4I61/2vCk+r/H46X6Z76KS7JiFU5GuHVqcQGPURsqczNybfTvmbDQH3q0AFhRyX/4wl7W7aJx8qVXs55RvUVsViWpnSafrICriwQK6JmHjL+whlBwSIyCvELyGGojL69vTw/gyyq0+Hm6Wl0rMsxbGlSb0WIibdid+jrGza3pkUIgycb07mlI3ZiFjAEjy4ZKtKbeuc+3zvsfuCMUdd5NYSPGrn797YsArWy1y2ufr3JfG9oRrt9nnLHJoOnbbqgPAiXrt6L5+OBhsxd54HQHjxDeN7Fw5/spQMb4hs8K5tqLL89urqEqVcL4Cw3+ToaYGR56PX8bLapubm0HZ56IEKnOOjin56AL6s1gPyyOEfRH35lRL+wVY0/xQCqJHMMrLgiqKtpS/8w1lUH7396f4cC9GaFUP6wH1HOQq6hZi8VprGGZg7lFACnI5Sj1TFP6W+e1H7bGxvYyAIdmhNX6NwFFWudEo6pOfTAMNewB0U+Res0nP4+7Buo/HfJIGuOzPd8L/yi2Dc/5ebnMulO+bcYWYDeiZ4iBwaTz9G7QGylwWf36UM9Ixb9KJwVmcDFiVKR9E23Z3eYPUgxpeK+9p8qWxVLP0nQYJu3JFTAf917YaUdqx+XwzHvx3XGrkdpcZwSI0oSDwqCvUsglPsXi83NAxsf2MUGBSOfjx4wcgHHAezEb1ep5/6YmXqY8n1KZaKBtrnOpch8SP+GPVqiaTbunjFDOCd/uXukASKu1ymis+GZVKGR6+OjaKGOGd0mPOKg+/rBk9njybaiLksJUzUY2tNmdZcQVSZT07JrX/WeWZB+ggUcMFONzFct1wJEmyVUn23/9rRLlGopPAiwmK8RGjEB/UbV9Q2WNwxwIJThoPTefevjvyFpRVenyc/So58rvX8YKgxgPkRRsxMvdM21OuWK8yspSLhouUwIqV2+nMphwb/PW//fVv//p3//Qfd6rbeonK1bb7ij/57elZtSefEGjx+0q7ouT/ZR4bnVF61zVsiOtBZjz2JNvXZcUUQcPDAiFkdd0rkbtlYQaArmVEYMlAazTF2J/qLr2rPKx6cJLoXuInPG1if2zkzuWuBukIXuaSk9RhE/R9KOfocsFtrV1bay1/kHaXVzqVpDeRqx5S7hH+6DikcfFBDjqUybg56Y1fa/9NxooGfLadnKnKrv6cxPEGG6JHepXirHUhsD3SDoTIl6QdaSGCbFZlhPmRhjYo4iKtIWzdupWJTaVRnZERDPv/0OSzb6XHoL7kLrSGVV036ohgnJA3KJh4pTKNdOaRWO2XinSNtOEOGxkEhaj0ZHQK/DV+qKx80Yzv93pZcQAupoWkYDPbmNu4bcVu7SkNXoxFkd7IOhe7V0p9HcGQ4fPea5git13atd6q46Ox/w8DTimoDEC32nEB6jpIYY4NXpkvGJoJO+ixFO1CaXYCvkoV6iIyL+ML3RJ/gHthpgmqBd0aAVdqU+8NT3cbxriouxbwF6nULnk+JBOAf9PlJWrYbQJCOsJjmFkjIzP1R8CTREp++YUOutDoi/aXqp8oIM9MJKGhPgzeRs2OZiEpQR7P42SQ4QsOCoNsnoQOikSzBUqxzH9KWiaSJxJAvdh3egXjLGdEEt2+NolHp+8ozFA/ClZ3eaRow5eXFp5WZZIs2/T49c+72zrFv+gFLGF4fNweH1rkKfToLtC27ycYbNQULZLTnfEGppYRne87es+dJOw2lUacNjQwMEbPcp0Jl7OYr2zjp1q8l9xL8PJyrzSeRzXtB/Zv1uNoFPMbbHIYiQOOTFSOKtK6Sk9Cph73nS8X21i1b5J7dEsPJJ6qRPqwHUpqhNp2tHJrn/ituA1VPu9eqHaIiQj/WfBgJ2SbYu3ZdsHjwQSYhG1Y9ZnMJZfx4V6BOaeRmCO5o/wCYxz3hGi+s4002SwK3IbCQpc+9XCmzfv2asdVqfjzitbOi+cVFYSoqbXiv1q3k6PA8dEw6lDtckYv3dOuDA/FFQ2c4t/0D47xIO7FP/ydwnABf2HL+N84/rv5CBeUXnTe5Ji4i+vMCMAr50PjIqQe3FgxZvHJFKps3O+efz09zeq0FJvBn5sfIW57zn0wTBg3t9TI0McvYQCPgpb1AgFBQkFTr1QXf+uPbF4lFKRl4GkotjtANyE+xeuPJw/4Gi1omTXHaeb/OXl7bww2DxBukvQhZGl26sb9puSQKD8GrhQjpflNCsqzdKVvXeC41T+3Saj+fhsZMs1nH568tV9Mm9rUwLaiRmEGYkHAjTjuRImsUhonaUk01wT+57cfmy3w7H8Qc+0E0IV+IuobxGAS9XQaD1F4D2mmRaZtsGaqmlFqaJ6r4vXw2wKe5XPCEasijPxgqSBt2gRWk2nRt6fN3wSSL9UXW1mbksWXpN97MEwktjmAv1JP9MZzvlmbT/MBz1m8ZkvRIWY9Nle2+uXBskEFVhnzTVtnp5e71jTI90s2CR+q9qF8JNuPA8uderbqcVkxDDGvIPeQG05ttVQT4NtTbUW0S4I3k7ux0cw0pxXZAdLQe31TkBP4shY6cQCLdat2m+d82T1/exZuTm85hS1ZnaTyfP9QjHY3D3z+LsmvOKbnDjFK6XdGh0uhCOGgvdmdl+Q29rs37Cwkly2GQcPoNG54fY8UzbbwYgswkMI0FzqfCe+oF/lxefdQI2PaCKLKv8B8RoKtU5EAY1fUO03lrCraZRuaQ7r8e7TvaaY1fmVuhTa+Lc9qkQP7TVqD6m2r+1CjVW9LXIiyr83Fm5eJOqF92Yy6RXk6pi9ubaa9iIRqlH/soiW813nsP71K6vh0zbrf81sbRL4GaADsgGu5h9abN5f2OZRujXnPx7br8bVNO4tKlgIHmxac77UgwYBlRg25uza6pTbNDTcEXESWuWohWLV7OYwOY7d2a1KlrOvGpfrx9CRmAos/o8N85PbykR9yVMA68yx8tfst09Hj/+eKtWhv+XoI610qp8/W2KWD15I4rYh5SiUzRvKTCvGX6zawYM0tiEsWBp/O3QZ7z/b4+fWXQIcczLhKs+y27mIEbqAKARD4tY6aHYezG7bhrojlE9PzxYY0S2S98jUUAdsXP5+LOKwpLNpseKGrzI1FowVCvAghOWNnNKRqxBTFgY9aPCcsiwT3Y8oi+x/Nv8a+XdKbw3JIbl9P7KHf1yHhAVAWK1XxfLKK+eTqacFpjLP6KRzorW4RA5dgPq8ihSqEG2buCGby7G3bXapasHmJCm/WTyiCbbSquNHH9XGcEu0FGOyap++oBXeB53EWbqAXiQ2rwjpdir2RG6SEXG0WZ5cHps3rK21DvEfDeyju1Lg0aQAbj9cgqneEG7Vr2atwBz+ifehcSSPyoRNkDZFU4ZXDRHzAuz68IoZ0s44eJYACpW8vw/u4E0eQsMuoW3aQYqpcW1/+1xcLMAweQz+aI0AzUi/cXLtmKfzbfigy5bdXC2WqE2TDVs3JC/euKkH8PUA1absX6YN45GG1THXqkZ9pxGiWWuFpZaZgPrKHvmKZSrxFnHNGTgIaoP/Z/yZxPu8+iUrHhLZE/zjOhmgCiRZj6Dsx5iIh4HUD3ggzXk5aWn6yOaofwNsiCeM00YBgYu7OuIyVSN7RRtVLSsZxsvftNtu2dMnkYYfyzKeFN2Vljb78kBpYbiazcX0414IRiAO30IMx4t0YmvFWDLiiLNpGHOoc9MMUQjrjttwTZKcmSOs01zrJi5cu7I+J/A1Jq1mWy+w3epePZnfAw8QWh0bjEfZAmMyLnZ9kKTbmN4g4sbvdcOy52EnxodyAAmHqc0pFYSWWPX//Ibm6ohE0VcuzGvKs193yYRNx8Y5YjOoGJkan9muWGOFcSNiHYkriHP2prDSwso/LwSqwoHu9WJpjOPpcsRh56GhoN8yrnAiEsyY7OuxxR9u4QecVTaDJzqcfYE3eKRhHtdOcHKSRd+ul8XpnHSAmvcczss3hVJ+NfpSx1ywMAYhNsUUj5kV8iIMX1Uo9iJJ59fNMFI/76pO30NGLs9rRDzhvyD/N1tUbMjlMyWVJvSOmNWwiAbgE/5RvrFRRXHOtqB3I58ZaDvHRrc1bLCGhenrZmHlq0CglcVxWOx0f3XA+4o38t+J9xNu4NAreqeMx33xJ4+OeHrKj3owTQeHWbAa3UWdznfA7JSp/XKnx/unfaL0MswFun4TAz8MoF9xr/QkwImn8eTl1ZM50W/F6yMyAW+tbNWb0ZjdNcDa1je5/7NQAOfdZpnk8bcf3erCx3OZUymcR+LdJmqwcGPei2L6PhaExqN2y7twjzk3yZ2eylEAGwIXtdtuUzaTBCdmFm3V+TC2U3uvBg5C9aiYuy4tKhq29FyB9Xw6j3Q8XNPXW+UHB10WR7MdHlIvUczo6Ep5O8zyIK5S1SUioP6QzoveH+87By+GHRusevBdRdxNcjKi73zzps/L93ODvE4DiOJH7jZJtHfmhrruHrqkd7MGhPz9RZV+c/yE7HaCe2Rjz+TtGr0N7yRkeihdtnK6kZhbYDDOoyN56pRt7cNqLQV5Dy9HY5/lNniR2MNLe6zcXHM46Gyw7jW1eo7MBS8wupZSmV4Sx+n0v1aRN3h59jG6TdikgpwBfSSC7DJjXzKAgKMEjuImefGF5/bkakkRcucqppIP/IVFsBJBkbiPYkXbPWdXjzSVSGAFm2y6JCG3BOyotHdvDXvAiqsKT+rXkgv8uCGwoxVRvIwOWjYkRNY/ac5iDHHSEmcRPfkmDzZMokYc6Ud7iiZYLYID7ZTYTOKrsE8qAU/14Rkrzwmcbf0yugcDfm3Fd+l4a/BMPP+WdH5Z3lTwu2AqZMIUhgbrth3xplKwPbetNnqHaRinRE5qePpwgl6DJ/Ju2svsinlXZi5/XsNvdzadFHIZUNPD5/de//LsUc3XWYsit+ZaRa+fflzPT1++Y7QAp8vDosq7pezEfKCtffz4xPWwfuELWY95HyEX0nsKj0j1RJyVFDWl9o54VXYkmWZJGvLU8bw0Lr3gTiD7/LtnffbvOv+Ft0RAwwIVlCilJoIizl9KT2usmunB8cfSQTqDnJNmMKZOAou1G/Fw/Ja4111/UNUkuFXRaam2w45MtbljicZodPxuROIwLCW2xo0WP1gnjytkrno2S7L9bCSVzKvPFWtSLVDFhyl40ZznEeRSgVYRVwBtnbWXa3geW7LLfbzb1AhGLoABid/3c12dlRToEKIm8tHgHja+QshM4s4MdVWXL10tlnOsexX2XGvLmzKtXabK3ME87hUN0qi4P7OJcZM/KGkeuRK2MqrKPsSj0JFReOgdUozbqI8OItF61EOQAp2j3+qzpu1ZJh9qTCXELk02HajWQhdJofBGtBNSNUcdCZZTZ9HKwZQG80W/jFK8bDOmQyhtVi6OkRxMSam4F+pfMOu2Q3I5E1zLqb9Yc8nLXbfo3dEq8gk/y2gkYCO70WvkfvXgcUgJtuLRkc0nF1r87iyrLTgk7etTlKgBuRXANc5YEYGg5vqNA3Vvfv6yCYnb1w2Mw4tk5ApoXqBGgzm13rm38NS1yBLyaM/r8ymvhdrA1ehcushGnBzlay2zphOF7AlGhi7zVWHkharVTSeP5TcxwflCYt4HGl7SRlaG9A/jn/xup26W1f/2jB8U3QBKrwm2MohALcIb21bC5WDO3QM1y0TDYmGhPrWEBdx7r1t0xWROqzxrLR3t7GD9yVDugtPPJl16n6HLlXlXL2DDNl+qHCJB9CDQOopLc7wV+FHo/Cra4vcuSpqnUHKCstKI+ZOLCzD1pFb00Q68muGAmHhcNWUWDGejVb/Kd5LaUg5Sphjr9NChaMNWo0x5vD/ZQs9FFL7fEzXmSrnPGB61wx6jX4xcg/UOhxtgprmtO0Ordw+J+HXopYsenvA9F6yYc3cvn78vIeEVaQWthj4bMLFGsddoNk1AALQQe8COl35Q63NEtdzzucObd9XcUFG6qBzPqsjWV/t/Lr6ecyoFrXZgqA8jPdb4Lbw1MQeabmTpJpR2TsMbYHDo47m3jCpvdezt4HegvgSXYTVRLCNHRH2FXMzSqae9F7dlgwZF7fTXl5KF3IrHexgqWEnGptPOd23ND0Y89TKXYgUQJP4GFc/ztbTt1aj1tFwByUlT6kr+KenWvTXgnSf/N8TtlJSPc11jvueM0x75m2ontDsX2N90emR5G4JqhG0THhcih1Xh2b9+fuMmabFrc59pOJwEXC+2gHvvLt++bwYnP0f1jd4ozAgqLBC+nGcx58g9h+ZI46ylT97FIniE+wrnWZlCVTZHkbLQeFdLLKE4WyQiyPhUKyHB4QvwH4HzxviIwGgANu1dYM27luo/w/fZT2529PMTiIJwcNjvJEF48U65V/7b1as3Fu1TjW/tS7t+3nXH8pU7bRNyoPQiEJ9SgzY4msIK8UE+3kpA8n27J9KQqnwUKSpqtpETQ869vO9QydHPXQfaMcgGQH7pxsr2Jr60qg+jKdIGqvX11OFob8lX3eCqt/aYuzDnqhyw7rQH+GVncPb/9iqoBOrvC6Ve9XIu9qamKBoWqUDZ6bi1F2fZslz6JEeiYeli8gnc6WjvkAqizKQmQYX60LCautMO1HGwobMO1RQqvQB+eH7JHrMb6L+ta5h21oIjchghY1HrXooJ7YBO4WIkPQAdtDHjhbJrqRLgC07xIK0bz2Yp+6C7UWrys5+/PRqXMD8MyyZZeVompNLv3Ne5iGufG3z7Ip5ctlClxPNGbGKCARQ+QkyUMpeVaGTVEUAO1ALOSO0FPV0edElWVhCoa6b5JLCDV6r7EtB4zdlcE7/IQA2FAM2WVASWn6LXQP69sjFxb2UIsNEad+/VundF22dxlZttiArSKKhHzPRbqZZGoJUK7UThVtVd7k+zK593ztx9wyLSAeRHcUEKEKWAjstL9awShV0j1sBvnm91CCMvxjte0qT/fPaGmdRGfkp21ZxxRDyZk3L5Dl8XFjecf/e7t7YkMSfN2B2sB1tL5cGZ+4YuKMPDmNKBK0XXMWTxlcdAjtkR7IxDL3/zNP/3PgHQvBNmTpN41EwV3HCH0u35Q2T+khSHveAAkDdJtVJgOIOql45i8vTxRKbO8l4OVRjWN4s+8k923mZQQWqWvEndZYCx7eJlsZ+JAAW01W1C0txL9ZBq0RVSl4oUtaFu7x2wf7geTFMEPs3qKg1n6uCA/Br9GCrw8m2ZlUwNhSG0mUA5ec+m18crE6ji3D/WwuP3YAVdy/NYSW4/8MkXkPIjnCe5mrVxpoU4DWAFqz2UyNBWTatnHPv/48SKz9GUEPzyD5FmII03ZG6atvS7SW7rrdn0A1cn4VQDng3SQkeSsKiHJu7PeQHxZjfyEw2dC8140V/mH/yQdIO2sKMgWt0U3WU4StWYBO9ZW+uJcT2GVIwKoLbnZ3pVhXWY+r/21YynI/qK9kJNhpY2IHjfqy6G1qsihkbBArQXYAT0nqu9Vp0bSDHNUqksKObZjWuD+5nLepjzpbNHVSE5MkwSiwvHmx7d8B/YdRx3tggI7OStaEMrS6Bm3qnR2XSDdXv1TFEhZpkwqQ6hhu1HWERF1xW0xGKCyYHuXAEgvBoBLSWThvuHHNYDbjAyRKLw2QASqCFwpZKdx8ewLYaMySSJ3uXu68yVRD2Axi4B1ysgx0W4Q89rbxmx0tu7kT9mN9+StKMMMNkA9pgZPBJUEWGDI8bmJAP0mjb3hu1t7qnsRZjkhuYVmkL7ARP/QFxd9I8qUhPdYKLzlK3XAYY/TqL02AxyEgfaWHqtFWBxxFdU8mF3efsPAm9hlTVWAHVWCH6ebjCP5uhQccYnewLCAzRrSp9G/Cq04AdekcisttnoRNwnf+G3f3yOkaViWJm5tiilI1Xe1RBi4x9a9wiKxRhzSAVJ0o9wTUR3bjOV7O6o9/3rZtKwR25i8AI4P+wsBCoD7bK/W+BA2yQZYZf3Llr2pOlztMhjTETxAXZvUV+/spJR75MOXo4jemeaWFyDQzhKALgDW3ATMEk7oQtaz/rWN8tgD7XXmVmNVDBCMSyDKnBqoyVaqlhJYI0TXZcOzlaylUwlHZODq3NQqrudmWMXzSYkQtpCzWysqYSlF3+F31cJIdrY+G3PkH+3v8GnVZP6nCqucREvkjm6cHltzo6FcvSk+yKg5Jx3XON49Mah0kAugnDVil9jeRnn2IibhoR3LliHsnJqbmTmB4lqCPoTYSKhCMqPjLD9n/B9UVOpWMwEQgtv87s6K3Yxk9CJ1c+74WmqQGqFcU6/xkpySA/AFlmdKdnRALH73ZS/01vPPF9PaDoaeO2iWo3p0GIzP335GEBhlY7jX5bcoYavqZTDqkWYsJ0sF995JEnymbZTU0/Cf24PYn0xMfMz1ESbqd2f8WX487Yq/Htlpus+dZNfVfvaj2myWOkXQkj9WcmVBuqhZBWGU5ISJgtMWGoGPGXC3HA2oEeTPLh2JBQDZy9301ZBZhah4lQkLiRDs7ikGpkgy47DH2RwBjs7eW0bO1zDj3HxKimHD03Il12M0L5B7+qovjdTBho1kfmlrx5boEE72fO8k7nEQYKf+QJqedCsRVk6NQKkgyHVluOZ7Zld4qPEtUsfiJIVKow3sNb5I6f9eYSoRfwPIrkoezT4sX8F9R2Awnqk0VSlTHQ4W64C9S+eazryTaUU885MchCvJf5FdEgwsSm4ddy91eBiDXmoCiWYSGqYuUEIg+dg4Vx9Q9GrkmQXavmtV2kl6GZMnIbb39mekwuilZGxCCQy7gqZGSgDV2zLP6YhuYR2M5375Jo8J5nRXrwzGQdMOzAuRa3l4ZJD2XbIzvzKckPaqlQTisv1dWRhAxIL1NnYwYNRGy6eliw+L19N442/1RRIo5aJZEpCqCCtkww4lOil/riBXh4SGMeBlHn4Ulvof/zIePj0mGHeXKP3nlRue0qmDhUS8rBB5vNj4dkqVm3hT8YPPm40ceO3XbwZ3ueaB4vch+2/pT1oJ7yHSg6uATN2ev6PH2k7H8hEHj8Rwac1y1fag0egKtH58/1UNOJVBJeTacD/U0xevc9Od3+TlJBqrNWKdPob7+3RI9aIsLCpzV+VqkwPoXTPF6ewLzevuYjceShdb387zw+pXzDrzNVIArmZGQDd98HxPlGIML24cqsliaoVREqAEynG4Toz7u6gJRbOgkqC8jLj6/VUAnPO441aeC2jjprYrjTRzJdrcIGQomlLEKdz4rJY8afcfn9T8DGx8MFWek+UcQUaufvucUEQzVfZqOA+PTtjyxJYGFT5nge5O3EKTIn6dlICLy89c1dBh+bQYmCIitj6UmMy405sX3BqxtqN+kSEJviRssPaSIbsjPAxkDVVEacgLOqK6OBpjELxWcxynfuMypzjSKQUW70In5ZGQ6rKAhxuJM5JVy6NoMeZgtm5PLfMcc32sV67BVsMosrP92VX3wLJq1am1J89BkErCdbyalfaegHbYfa70QHurX4q+ethQAeXSyudSuSRCQ68PVMsdouaMRHI628pU1d/DeWUxgYh4lei2Zkqc6qR+7lZ30cDYvtMmNwxEplqKUN6Jv3G2lHziTWx6rYssVuJYXNIYbSiPQjJF96P7NytGWHNEFIkw0a5///6kfI/1D1Ax410uSIcwQy1VqhWXLx+3ru0V1M21rCCQI+diJfykY5iHQuiSCqIs6bUdYlUjPVepYtuMR8kOjkfeZevN3NjEuHGo2ouFHQzaG0XMJgkBMwMSqSGRbZU224lyk2ovqrDxQgiU8YkvJj21hzZ3NBF0ZKJ9GPeyBkkXJ78+LTCzw43fgg9qqyA7b44Wc8qlas4txYAr1R/YrChtFpuOlNs5kojdw2qs244rKL0I3GqEXIfwY+MDA1RrTaCjakfkaZLNUq4RPQxqNzlMAzgiMbkgKQdU42mWJduXQ3jAl2fCqpYY6TWXlGkDkhWWlzRXquSaLu+5zyIEicbRUu81sVl2DKopLZLKnXtsauvisVQHR2WJqCBWGTQSxtOqruG1AuSad68/4Pl4pcnf7jRW/7jLcdn1hXE0yPj0LiQdT7TMcCG9KUgo+eLgMyv+8L4PtTdjH173T/JtPCRrxBi9Y7d+7NChqgpT54T/1Bk/a/vBKZ1WZWRNsvpjDDIWqTttj3atZcagVMlQZy7KHBswTYbzs51/mMzcdddTeT/6VabZc2czXXYtVHdMlEQgMhlknb3A0JTG+Fq46eWo7fy8WeCpHpwUsk7jNdobIT7Yik3RNV9cI0Yk0KkxBVXB2JrBRjKYTnqSz+V+7Ja0dEN/Zu5V9cgpgB36LBcs+vVLuTP9Spxjuv3KVVpcDXa5BtcIGr8bp2REI+w1rYlTVRHVLqkAw4Bm8smcUXeJSNaeJWA2inb59/+PxtXxbzzIXHapoJwAmlrVpDah02UWXa2WI7LYAh2XxGaERrgd1F+raWnFcJpNixnjwqIlrb111AzqiieZ9HHtIbkCkGmjP+iAdO4WpL0GaqCxoC+SqtYaX64dGKMsdSzk51kSiojVZfOFFytO77gFK9eVWwuwlX/z9nOXrIRcfZ+TI2fN5/vgsIr/uOgyqfkrCfsWpFwUAfofNae3emjrIJ2giTS5WH5orVR+xUL6lCPa2Gv6iw3D2y/BWyqkj2QqztOe9MkPcCW6wyjPMqMw1+FWctK8xtd6eX5xwSKuZTy160NcngZe4iDxHCmITS0/gRr99rSzpSOl2gkxbo1xI4nefKeYKZNb3qMsjPTq7QMfTCrYlJOVmOTVqI417bFgtCIcWD4ZIXtWNIuHnALEEbrjXb3bGjnueY0uewPldTIV0DvA1XXHTYQ3cqxwSPrOp0pQU/EmGLoDvosAmJ6p//2/6Dbk3OikDmrjiOBs27pRmy+8oxW6oAznDg7lrvXv6jcIdLKWiVxMEJAinSVkZUMtNzI+mmVyarusfWn7p02QZvZrgubV5stQctDQwzJfwyllNLr0Roj385weWWXjn8cPPKIwbsI50V8DWjmTDwfBZsY7K5R9qhWy8NEkGdMK/CvGnDdI2e40Ho726C4z6D3k+Af3FGnkPUpLoC59jrY9qlaQjUYWdQE1VCw3VAwYK95ZfhQBEnwbqXr2ddrzVB5FP/94iSAVD650ex1IadJjzismYo4DNQ7Z64eRhZv1oNnsGt97Kja2wKrd/BetQwT/FBrGtE8UMRskmpW5yiU6DNTQz7UToQaO8ZIehMY6rmzapnurmZC5ceNCas8GMFNf/T6UFH0Riu8k5PfOjEsKEMiWnWZfel7jfZvoePAm5hsVV79H7bY3t1s+n4Y7k2TQPGIW0txTOED7m1njxzlKmCU30jrBIowm1EJ6d5E529nCneJqLYlPS6yIeG786FuN3IZ2m338/HsKFtdJBf2gyHY1A0+m0e4ewby4Wi6l68O4u1bxUo860O/REyezn0lYlBGfg47/Od/NVG+WyA9gopVD4kAJp1c+62lf2nemc+ZARQqtZ88OSKW9W3FTZwAkTtYgnUVGseQCti7XpM41gGy2UHTIZXWvqEKXwMWwz1VkpJLbHzZxY1w4DynuGqOqct7kH+IfEyc2sTNQY9t0eER33SaLPdq7wU7pNw/OwOKxt4lfM5X3aIAfMuPuph3bh1LpdUgg0XP4/aTR1ZorDFQqq2bR/knSbXGH2sESgxtheX74rlJDfRoyMCFafNbX/NRqSx95d9c6+VTjCaL5sSZy9rRmBquJdtTxnGe+UPzcm2MyQzX0bvQKLQ0VP3Z14Ma7C40R+xicKdMr+RZ9rZhFa2a1IZopW+n6wGtGNnAUivQiRRLe11mrDjsOgeuJAmqUrai8xqFLuXadxvccGU52JWmFRLN4n1zSU+HxYPhkFDXrQVg2nZ6IzWfZHUOPkJsINaIEzlqsaawALFB05In3FR8CPLggA4BzEyHpLoaBVpJbxXDf/A/mB44pznZkCPPtWp+UKSno+L9Zj7tYJB7la9lCE/3iTd5AKSWSk7HL84/vr6zOzcs+1N4usXrMSX2lG0FFrBKDPEtbtCcrFoJQlY0IJ7CXDyZ6gxm8PGUxokJ3XEARTxZQMpsX2cYZYK8hlpKGpZxAgtM7NGuUyTC6Ou3Zuo7N4Mbvyx1xL5pDLSEfMZMQ9OFgSJj08OUlLnkusXBlPM+emeYhEgyTQw3b78z8uuwI0OmT1M1Sp/lkM15UNOectbEws8znJIumrkS+iprw7hVTh7ZnAIP74YgChwrHWzo5RhdYPj+Ni7R17yDFqbjSYi8cgbXRkQ0jyipF+AAR5Tp2ytHNbdjsR2FqLa+0nTpHFpyEoTnI1ICgkNBhRLik5stw8jDpFwqNpIOMk/RRrtqnIsFRFzaEOiQdQAFCIvxsbaTBn9iPHxKqLZ1tp72M/+f/41/+w+7l6adbkypNWLSraf/Y2ic1oUlnS2r95OFcI6vCu28145nIlGInwf5Ge2mTpPESrtdANDqaSYRlrvf7KCd7VWVrtTXh61yOKt0ETOBVlBXmy2/ksihUl3pzJTHFOEWFKvj/PltYZlgB7eXp1S85m+ToBDWzqO4XiRJEDxaZka3XZGNj8f9q8xpq8T0MjN3alCNOQBevRXuK37ZjnnjXjuWsxm2uwRlOG7nbNPCRel5/C60211Hf5XOsR0Jfs0C5PhLz43o36jhJK3dkT+D3XYXPPsvVkfbS+ziPbU9FRD/dSeol+80YZn4AIN5G7ETXbi57LwU1mrIOS9QhE3PXxP5H/fr91+4y1Oj74CdQL4rds7zjy0cNa6i1tQXw+a7uDO69sACGocCSxHRa6wgqV/xpoNW3hqfUUSE8Q4HrSr+BK615jjBC2slb700GoL1YnhHjttV21KdRZ412avMGwiThdRE3rlknwe3jo/C9vpPZFudpkbqfnna4C7DuEu904/ubnGj8reFwvWBTMnRh83K301GcCu4Vp4dlmmS3BDuUYC+plOrGjmC0U6Mkw6kVHis8QXPRlKbKwoHKYM2rfTIUYdymf0Z4pVdEnmC0ciiTu5zKITzVsXxOiOMg39PJnRSQ7nZMRQ8D8MwVsNq+nEV5d2cxESJLnVyXY+1yErnmUtf2nmkN6e+dU8tJS1M3Dhsg8EjcUnb+o9TCF1xbtXPTINGbI2Cy7PiaWwS4WnP+JFkKBr2KcQMo98sFJUq4yJ4gxbltupWi0spcVKbfjKLWNEPjU9LJ6E4+/3yF6oSapaOcZPYPLfM/oA4iELTV559wdNQGRUqMYtVI4tWi8D48rRfesvVSeRyPqeznlW3ftA51C1NlOH3io9S0wnQzNPnStlu7VFSqPTfYDY25gaiPVXeLr/32aWqbIespgnskU1HcQO4vkqdTrG9Nvo4HdOEPXXk5qDgil/TFIjhzCz8WbJIb+a2JeDZitj16Zg/HUXgKK6JFHXCR/o8lb9TSa08ZT3CLdPIPcmtNebjtqcSJkvhtOSy7v/8v//pv/92//uUvEYW7Nt2abMcjqZXrhrNHOIfjOI3tB+5pUaLFSxsP9xms07WIpAUJNsv1jTi4XpiD1wK61LnwdZf/Jwd1l8NL5IjvcUkHjAguEnSAQKgeL/EXUclf7gu7aoojJ8Qoh0XPXbMUFuPREpt8IO8uG+IPArTs18CO1bXsy1DcRmFB+jVKjZV6Os3Jor6ysvTBPiVH49/dqu0bzCNUYSaA/q56aa4fNNM4gtqgRNjycpRmE+NAUe2j7zePGhqBdNIBd22e0KVP12sWr/Ri9O4RbSv4UHurxU1F4THuFpvG0yo2cJx2ea9QDHS6F3FvhTIcb5SkMgdYRE3QyVBLOLOMaMwbY4CuCWidp8LIsQ7T3jjbJkElVeEgGVCrzKrre5fjVVwtNLitCpM3ZeunOXb0c5oAnCF4Mx6tewuWs5nCYlIJDp2VfjYiftr9weCvO0cFelJ79Y9/2S22eSkS/y31ZoVZbmdWT8gJ1pb+kUFs/B7BsZs6Maovb+itiKYq2o4C7bHbRNPQc8Anfp33O1k+xclUkN2ERJPiyfK3Lx+tZOHU+BUyUjoFG6JhcSQlZ9axX1DUOOPazE3WAMRKOueWeAxR1Jw9a5ZlaHTHkYx75NStYH4yWnPs1vRgGwEvVJtxYmQSWELiMQogs4z+Yaphl4iPxjoKk4OKyWYSc1cs6vw/sbYAvKeWV0ZTtWSPrG81swyXV/gg3ewoySxBcu9WEyKqUavrqNRHoaajLx7q07iknRQTsAOgItlznVYrkjaSQqew4V2wO8TzjEPPOGrGMN5wCBmFDymSBqKVuYetPRW646MtXzS9ebHnDNR68NOiwRNlXHPBSjqMQ7XR5eMnCv6wH/u9Clp/5HFR/xrlAOIB53w4760nNSNco8kdNyPS4u3COB5VcVi5pVVUhA59GS07G/dTyhJxMOjunr/9YoAudlHKwbMr9Vx+WQTLsQHuKrpN6qCy0IofWUs3eDEiYaMOSLgxKRBmeh8uQiHLb4LiMwqluyebLJJSqSndLado0LTL81/NRdE0HmrITqNL014lgMi+x9pYYd0cGa7Hn43nyfyosrA0DCBTiCKw3oiBegt//a8749m/FJ/4U0UCcbZoBFxKQMyBqKxfgbtH2Eh3EW0C7j0rMGD11X5K52UEfJJV3Wk6UNa99hzyBXqQ9x61Qef/8lXOvw88Zt8ZfmcEm5dsvBMKL4XMG4Ijo5TD51vCh7nfIkpuHhFstRdrHJFEC+WVwAagBzTF0bJBEgkCgF6UB478FUlpiANZ2WGj/tjcz9vJ8scPJp1N/sABi96cq3Qa7MUywBOJKxkyU0WzYSBWG91P3Z0JzLuICPJuR2LnPjrV14k2bAvdzWTjnm3eC4nTe+qK6f+6KOvCK5rGu+azLhZrBkJIw+AhR81w/wrKVoKSam2vzf/Ly4sdmSTXK5V1mCSGhVzrKs/2ZOVYEcHmvXf8swHH/MZzwS2NP0IGORqyPJQVOtDeamjnSWBfRHO56H3WMnXK2ErUJ2cfMkgrBwSIe+eKgwXQJIKnj9AwvqsfyuS8ZEr5XbRWQiayH7Shl4BJ6pqlbsMGHscF4CsrXst3zcUjAQG+dDyrlC9tbV/Rj/02xxSyh4pdthswOaJBtxWNTCo4G0MNyb9Rd/NHkWZMLxDCY1lCBYDcKRu3eGALQE+Q03UVQWJGtnGx8vlJs7YKN4HUaj/VfeTRhk3htCIPfY1YN8jYFXWnsbK7ZrweoadNr2Ehs6Fy/Mhk9PDObLFPrB0ejMLNi6topxgIIHtws4tqvn2xqDwW7KAVE+FT5ICk/bgUV07UBvcRSUjmAU9CkeebosM7q8LaSyR/VNd2FM6Oqe4qBxYONHjYcpNLxEDVfFnFXtQUCR7PezmPnMT/7z//b+IZ/687C9ce5BG7bPq0Gqnehfhtv8a7qksW5FJoELX4NcQQaNPW6D7//ClHCwWt16fnnSDUPOipl+thbayORGpq4e/KuzittkLUkK23GltyE8RQRgu7iDwrVE+Et6PN2NXtLilkMs6jyjl35NOQZrc1K/Q19V5L7+2rqwcDrHg5N3iw2k/2QhhGZfgu8xTZQUmtgBXm0SPRWX3J2/OTIJO5R6DBt0xUmxpVXuhYpMLgkvFqrrmuak5yc3/SjwdNFeVes2y21xzgKxKAdhecjfKQpWv8kwxeV+1qqT9gmu9tNMsW+GbGepyH1aKfrMC410PxXbqhJLYQy7QAL0AZCwdaO5Abskj1gi/ATb9gL9L6MEPKZ8eLH0y6sBhBVgnuWudIdxfxi57nME5eL7TNzrgt6XrIBjv+/PCuXvfSVuto1vax3ZBw9zGSNIvl67YRMwoBEDmsM02I4QmLPekh5N5OmHNvYROaWH943GrSl4RxoiHCGRsxUI8jWC3pNMrrBRoLEVsbvUg0xx1UUSHtxqT6SZhB+C+RYCT0BS1Etir9Sgma6MDU/Wn1n1dv6WCLW1ybdonVFgHh3tusbE6dq1bWzPo3+lUrvNp2fy9DblBs3O5H/vL8LElo3sy8wnwWantTrZnEk4sG6WJj2+PRth7L2JkacCx3oFVG9f1JQlUuYvH0TmmGIQ2P2UmMjQWyVmOn9krmq8IQTaJa65GKk/GnTilqJgZ28S6a0YxlFLoaVaaS1E5j0v/217/FW02cUv0A7Va3TaMx3Ok9PxkegoL1pMlUvP8IkKiIEDysAogwbwJtlpQTGc9Y2cTL8Swhu+D438CTItCpDvaeR3tIMcpQVd3mh/tFhqpaFlZFnsWNoQTX5B3Zj1zpt77XHogz0+fZugBHqO35x8/IMV2rI3uz1A0rBZHFGVmZms11VZm3q265Bi+6VFHGK7OnqczV8H3vV2QbrdGLx+U5qlEVqwFvbz4k6Pe97HPfnmZfla0Y/Yf/xPxLe3M0MTzIF9ffGyXup9w0N85/tLkvSCNKgmVppMxsyJFrbezBmXFf3B+BGiiWR4aio2GBP+imQSmWtfkSS1T+xkHGI13jTkaBKP1oqYoBM/V4dDiIIbNfcR8QkWGVqRcH7r40SWuTZ8+atP7u4DLGm+Wye/3+zT6dFBpd5/AlyQBtMYYIKlbFrlRB716efsWrGAZS8mFU6Keno3GMED3ZXfCqYOmGOIrW+7ypdohxoc2R1IpPupFNVzd1vzvDy4XoNdkqhm95uYgkMFlU9IJE+266rztURQXKEVTg4LmVrYxkR9aNosf5LFKuMhiUJNbeYT/uMKXXRiESNX/Y5JHigu0SdyMqX9qy97JdGFe7nUY1Ji/ROJSGSSFvMC2P4c/m3Z6mFnoXUXK5kqzRKK5930arOQ1JB7Nj2tTudQtN85UwMXDeIvMR2IepU2F9wA+ABa23Rkc79co2RzJZMhmdjKK8OlsLgbNYARAbTrLt849X4BIXQSfANqMHg3mJbnJVW21Z/NUk07y3Lig8Kh3jumgPjHTHsKlrWfQa0yYO2bjRadLAuEtJfaO8EImQ6B2WBny/g/1dGR1O9w58LF/mn/9PVVrVmmKHrA0ilXrCh4VrE40V9cCnDCEkojzMFnDZY4PIsK7ulLI2hfw9X/P55w+mHFTdEBTjx7FsUh8IxOQxqTabK66FIWmbTDFQHpnCaJHUZa1ER8xOVO7NzFt16zqM8Eiw0XL8wRRTPCCWuLKYttnlhfucKJD4JKLr3izsJCj0JE2HsodxGIfL1Ndz4xncfl/vPgtTIrR6D1qZCSrqcCbI9+MtTNKco/KneGy1+/+bv3n9toM3HHEMy/dJsS+NMqfxQCQjttBA9YNoVsLnSlaeKD7fe0Bd6nzkTPj8400Fsab6c7axbO8qrw3XAVXG92KneQohj+WF2ogjlwyf8WCncNVCp7ij810+rYo3qhjiyByKcLhxHyQ5vRkv2GWeSWbTimqNe7B+SVlF7K35TLBXFPEp6dRDMMrWHvGQyBkOgOazB3qnG+TkRnMBVuO7j9YKB2IFYnQpmxZkoYHWL7vn16cnYRS6VtcywYBa8M6PD9pgmdNGh5cYjMiG+7uGjSVqwPXkpYBCTWrNuBuDATY0D2hwnJ+316cUhpMsCH7HdiKksohvlSqGEJ/xsb0Id9vcI5Op3gBbGg0y9I95uXu2YwyLErT18NaPL5KPDJlZw1D2ln2ReyQpQa4cKB9payHkIi22TuwdEbnSqgpp51H+MauH3Bvx/IA5Nz3aQWFtjrMVV0D1wHlIjKMWAOnXPKZTnyCyu6MtTLHJTHjUuLoq/h9/2eGmfPaYFYka9ysXq68dWakoE0R49lGdaCrQXR4vW32gU1w2//hVdViaUaa0bJ36m+A6IuG9vDx7rUUr7bZt8G8boI038n2QJO1ypxKIo0F3XIllqn1rLd8QievMxQN7OSJbFgeJzL1K+rqyAuXzT/ZA/e7by5MupUVSS/5DL3xiRFzIcXO2zV3ptKWvj/jxrp1Y+pq2UrPVHxt+5+j95aUIGHuEegXMkACtkWcdhVtTs4p6s0kOzkz2kC2C2KiJ5nnEtRLylIMb8Qv65u6O+NS8k4GBCmGuxmVBFzEHLlEGjid1WZsyvhRFoi1V/Z2iDRbrHITQFNpevurMCI0wWTqP8XEXcK7WMsW+8hpv3ZiR7rEJfX35ZtPAOvWwBDREfFQ9bPlgTmGjMfnpknci20vr5Lja7Lr3ElD87ft6boHwlYe0fHVWfwZ74mFUPot4mbKYERPgMNry4eDK4SKiaO6q51kTe+Wpg+S354cqmsxxV1nCrD1+voIcPOABFMnMuuNJi3Ls7cgRwd9ibEMVNxtGHxYXXuDf6f2k5kXToem6wDRaYkgENiorYgwNEvSjL1wskKVoaFiat4a4KUZJmS8iuEey+Fyr5sbipPO7ss/yfqvj//EvJbKYJloKR0DDfGIsAn0r8gxMaAkH8kWKoc3s4hjc2bj7/va0M6D34e54pYKsDFOQxZS+qOixh/K56YymUk/8cVjsJ6Rs+P+OEfIooPTsQeFG2Ir3ImaXilvEW+SH1+83d0wpiSrbDJatQRuBHjc6Pn1tbG8waU7jSHXyUZZG4tX+cOo7R8GmyPp2j/IUigbE8TiYF0xqegnITQeJ7Oyk/zwUVEPW6RD9xC3xsDP3T+MHboKllhchrbDQSDEVnLu02eN33S3DsdSbyqykBaaHrc0aH33QPje19SDAdPwx6TjmAMkDjkb8SjB26pQbsaXEGE29/rgTES7lPjP3m+iilFJSbERw2s/UxGJcakO7TfR2bHN4PKgEWu3C9YeUSICRN9IHZ4Kryh9o96Dveu9Kiq6JV9+n3oGsOmtBTxCET+hAqpmJivgeb/v5x/efgv2r9N9oI9o/ti6cq4NbXJHihV/0gkhVszxAZ4yEOsexcpnUVtlJRKDrNj2z4CdJhQUT1F78h/i9o+BWmymBbXAF+pHNj+ai3msJs04ip+F0y+8ZctxZywzSaMavTo2vRdOISfY4wosJpWG4xcmK9QIFSafn+/OTyGVmia+DuvArRod7q+bMnRd5gwh2eOtcqVfZWIgKp7eNSCvgVk3ShjNxUs38j6ddf42s84POcE33gFvcIXjkc58dyuhtyaRQPVkzE5GRRTIwnjR7thWvOb6j7HwlD9PXdllhnxtNZZx2lPSMlun83iiZwbDvPcC8jqp67aLUaCv31/9LltTU5tFC+HBW9fzoob2Lg7QJMkrZ4fnXs3zEfd5qlvcSjFQx1BNpUMJAZ3kl7z/J01dYS57PfEZx1Ox6x8KX59fNVylXbcJAsWhQMO01hQFXN90vi/du2ArCBGQDoeG9cGJIF63bkFgr4fnM5TjPvxn3oISznjUK7i8N2QLxOzkOyY5zUmt5vxdCyfC11iYDRnae5U1/yUY0OjHLrwn0VS2bHn0R+LmX5x2fKGdWXtQKr/H8I7peZM5Gg6jq4SoahN0uGcX5eEW32cnOwwav1WPmrSn7GRn2+BNAORqkT5N74ibjxGxfy//3kcWaPQg14DtoDHbgd8F/6OROG/fsEK/jLSWuDpaCWkSGRuWC1ooR3JpuspMmQiBNqHYfQyWNeyQBMqZwGACDkclBdPWXzTqH7Vp0UBqxPRTYoCOtSE57P2zA5nRgn/T86w0+T7yYaHlr6x/QCIDi7PVk375hWghG5QzWKfK53PCy4I9/dixg5YJVfCq8d9Y287LhqgYDlIJVl7TekFtDLXrFutg0+fnXD5VSVFujFtIUZ/HwZ/p8liv3ItQUTCw0uOKnStdwbvS3X+1NvTFZM/HGx359et39en42EELnshnFLvMfuUUBRdi1HYhwuizQZL9VCdJaS1X9Y/epOWQj74D2NIqztO90855//aQVwoGTaHUX4i0i0j2RbPNOF/hdsdwqb3HDZNI9aTd3s3frY1Gky3Fn/i6MRb8h1rzIVr9WsIo6LvIl59Ofh/Ejt93ttWgEP+xefz0x6xoNwurlTLhZgjrXQ3vRDQcyUCWV/8ZenTCxSqxt1NoY9Hf7uzH586/vRgKOnnQ/aGnS58op9fxQbD4ItVJ3Aj8oFVnGQHOiKLA8ZbImuDoB0224YLPZsasl9+c2ijCBQ0WqKZocTso1lQDDYmqbfiTl2H22XzXFJEiCwTVX39cPnFauPKVytrKeQxtBRiDNMv+me3OIIlZaHED04LbGF70Yp617TX44PqukcicuQJpdLemR98BKF8B0Qr2KFBI9cNw9adaUByBqRgKGVXI0TveyaO5x0vKJ/ILqrilP45dVkAvhsXPpIZbVtLmjU3pRPmH00DrK5+VF17LzMukiLxKx75BzXmdk8GV9SJ0xJup/nS7G1WoyLoQxWvHmSOdB7dflQV+qqcQ5tfO2RkkACQ2oz+JcHxmPAPIWIHMZivBE6Ypl6QpZyLW5br2j5Ta7fxXLBFqzD5XmRzQ1Edf7qIvKyL3xSGsv6JjVILRClESLxoCS7Posnit8oaGmekOhDKM2TvFEkwQjgArP6z36C+N4t+pwjojbX3ZrcxRUV+AA6Y0JGBz3acETFsktBLAmu1pHwqODoB3RMuKMhi+cA6xt1JtaKH528bl7e3p6AvNlGaMVZPsDz1QsvxPFGwhHzFs1ALJk8jjYN1uqQVSCN3HqixRpxMzrHEoiEw1L+8hCmojU07a3OGsVzbIpTi9kB5vCT6Oou2WSneMo2tY6FPJ1ZvmLqIDRkU7jR5t7G1hzc+M5dLMKJ+N+7aoewTyJrcc413e1OSQJ76xSeE41LOy9XBpZu1mndg9j2zsXpsQsOuppvzUfn1+oIMHO0LQbxA/mtxePFWZnoFrqAwVioDwMR5NqNcGuRrDCpHAtsLAvOLUneSLy+6Jprof38e7NQJp/cTxh375+i5Khai1dMu6ldIphwpeJ1mzjCWQkouDskxGv+as1ltLDjF1Sv2BOVzXRB80Y1xSrjk3Oqmyw/qwJB9AMXeL4kR3qwah1CpwA7Zjh+lfk3/ojixxaSNSeoJKmjxJqLkjQaxBzJpnQUdQoXjR5/eK4c+Iv2mgph1/WuPU9BcdSPnbF5/DQVptnZHzY3tL3QxRhh8UmBWnVDYoSdkPE7oMFi1umb6oDNAPObq+Ov9Zhh6itRgSuqwCZS4436D1yDX6qR3EhL3LljlRbPxCCEXP3aHlb4cYC7BtvF4cNG5N4oyzgG/MHtT/I3EjrzT5yDUSME2/hvvv29rQZvWnziZb2KJduKunPLz5VGmp39dfVJdyuyUTEbtd0is2bAylBSh9Z2saVAXCtD1O0SoCDqeYL0eGIWSck+jXNjQdvtG6LSqsLVZnlDQfNpO2eUdulqum1eWC+X9+lXPMB9rIszq0Ard0UGsitaPzy/CfJWTm59NHR17TNYI5HIQMeZ21uijXy9rUeviefu5fXZ45yPM1WDwxZehXXPMb4AiCuFwjUt1osoKSSPP/4tZNSLii3uCCtLCtvOZ/2FCjpDcvu17cne6cvMnC5GrM85ZJedYeERnMBJvpUORh2o3E3XhbUVDJVMIH00twZllJXHayuPOs4RxGglf/JeDGd4bUaSBxSyJsRYvixM/ZoOERMEaYw4wNHbZfTSg1KpoaeOArO70+Ca9v6unONBjginker/WkNm2DvufjHh32sT4m7ttI7lNCjrE2twa/Q5FHALMS8FJbpDKMrzI78ppAhDZnFvYM1Lkl4ewSBvIUbr1lSqPToe9cw5Ne0d0+2m3WUJv4MOgDXcbH+r34b3eYgH8xepSsXfHrgkXY0a+XCIhFmJcfTPC6app0dOOr0sUNUq0t1dKv1XMhzQn820q7cr582XLCUtyGCZTLMeuy/BPJ1hbuV+8z9iGjLbG4TWxgTGLbiktumPAjIMxMbZzmjo8Wsmvvn61M6TFhS7YRQ5wBefzeVvd7dRCKKC/z6xNavWooS1mUV2G9xMTiVTxdFWpidR7vTAOfP4sSolSsc6g4a0I7MIWJWQeN/snUsS93W8++TvLTOOCFuZvIpFhsXTNt4MGYGxh0osCv6QJOJF4yJdFYjbt7l7nqwv5sU8GovSiGPg4hQtGYas9kniQ0/rItcxGb5wtPBzvKBJdgQ5MWlEdJts59CvrDHUzwOYe4VQMcJlse0Irp5yVB/qHEaaIYoWfiBlZ0ZImt6DKOuKp6deGDTymaic/Bch4fmul8rgLlOOGPPeqvxzhBwHfbyD9KQ97x7fYtvlrHarjFRXVaCv1XaFFUa09paUfvmnYX6NixiN0pXpS2VeqQ9qlXIZjWykHO5NO1FfcE0KupDjSC9eZh3XxzWqKvHLDMGpZK1s34b4wRUws6Z6CIrnqOuk44NoedoaA3TSblUHURs1NdQgh2/rNxZNYnmsE5pu9AvOwm/AI7pi3Xw6nimxhCy4j9T5zarIUzqAhil/fylEPIpdt7hKk161q2fwg+rXpIqg9mgh/Fjdx/PI146VKqyHIizPZxnLWPTNTFtUk/xLgoFoY5CtFmi/4ocX0HglqntxVJu9bvzL19QFWuBRgEqd5WoGit6BGEy3MQJWlMtas+oGlieMpgB+1IumcQeYooookE6B/DbRekSLAId3FOxlYze/9VGX00rKshenDUmHlPkOf5DoTWtauNMCvUj2nw5LiSLmzOxdoRW0IyOOv6kEa5xFMBlyoNigpX58h19zrTmrCvpqFYq6FtLcnBoO/LkJOj3Fecggf2i6Hhga6SN/Xm1moZQvGsyce27WW0PLSGcmPgWe1HJzohp0yw4bv2QuHXdsHYGqeTsus/MtUrtcFiEr9VhPssex/Yt7SBZ2ogT9qVS9gTEVJ13kuqLauZINI02fr92+20/P2xjznqgQvbFkjrr8GgT6ejqxHkBkJu0Py7yhxV7U8Nyd+pzl3pXlnu2AdEe1MRo5GxJTh10JiNQr20hwT44wHN6usfvYt8V5yvCS781P6exO4pLMJxuQnTOqUTX6b+lbx+lLBwzBPpqz9HV8iHioXG8PLmpj7AqegwmJAjwpdS8e5fwMROx+HA3ZuOdJ7Imk9Z6t+OX+KQ4b1Z3Ba4CMhlG4tTc+1T59tqsRudvvNSmtnPKBC1ZJrmF715f8GyNkCUdOGajI/Lr2WYoOB9MF6xtx8Y46OX51+7l2zcvR7I5oEFdJYIFlEu80IPL8SHKnkbGWEgtQ9U8IPj8m4y99II+DE494k4i75+IMug1G8nOCOQ5untgPn6u2lLiryWRrUT7pPcTZKv4DIAGtcnzAlF73WPXujGJkhjsJouqX9Q+8ZCA88yNBrQvry9ai7ee5kbmaTS2p6A3gxNZ7oPorjYHA7QC0IK9riEhszz4SLUyyrEsFSJWxXq6tSNue+p1mFILUjWlo/qkxs26MJ+RAodJkUDo7TQIXygZ490v1ke1E5QwU15EicpbH4/p9nCLqkhaUh4cxu0AJXNQ6o7ayvhhJNXBgq9u62XVoPDS7S1/pyX9NcrWHh/WmbXrIL3CeTGIitXDs2YKE/Sr2RoFCYqKzD/unn/9Iny8P1woPj+LqWrSAFWTfC8umxB5fra1/KVJJn2PdcFsxI67zZJIMSm+7iIzW8xENaP6rDNJsJz3QDBtHstAWQMYNi5ACYY2AVMZdhG5mkZRCSQkqHIHFkVtLVVxF9VVQcaNe/FzJ5OmnIta5kopMVe+FhC52IZ7jeCGSgQCUZzpgg5sLSX/ytU+ztQNwJhkeOvhia5m72B3Vkji6KAL/PReEBLoBJelqYradD2UbJExhBg3L6nZ3dGMN8YqqWERYS6i+6Cds/fdjBsrA/fBw0bvEoVWtLsb0MDk9UWjS0zYrYLtiJUdMVXv8SJOL4qXhrHF7+NZX+JXu17KNarVG7v1w50jH+YPPdVjUbU3z9JxApjLAY2wN0qHWqIUylIHU8uUPOu0Wqhzjpwph59XBluuMzGLIPBtw36Yo2lh+hOOO/ELXl5eeWZAGCtffHvOpuJ2LRWJdWOGlPFPxsF4lYztfPdczvD3SEw32Xi251rETYaHmL7haj9G0yJpTq2h791VBc++NSfpspWLl7E7m5StgHh3lCuSL6jrQ/KQNI49THeBrs7nwjQovu6LtGpYyc02k8WLaJAydL2hb/311MEdfmNP6C+I6hahTH3WacXnYqo/hT9qbYFgj93Sa5zll9RoY/Xzu4FfoknWjoadSjm2XJs/QnoHSF5j0DmIOkJU1AQtYnOV9+re5ZTA43gJRgFf6zWYUkVnYkcOAqOSXc0gZCSD2O5B2XjSEiEyPiQ7mzclbhIXpUleM3M0yEgMt1SUXW/YxWKKDvSuL4ST9P6+9C0le91WuVaZXQbaPwY7zENBrXWXVN1tAuRNJyQqicalDMLrq6jiXpw+/MU0exyVeNf+4nl8369DmxMXFVpqZEnqqvsQH7WcJJGXuq233yhXiZmVHN3meTJjYzEORy/OswnzGrR725tiAc73uNrmkU9CGNQIYN+OKiu4DvUSefjDynCqgCuhpQ6otErDqz2rwbS0TmV08wIT77I79fJlr6c2q8T32kvaq1cPbBe81lyl/rsOYgL1qQFJGTbdLXZX777j2nxqT0QxaVLJYDn3dg8DsOP6TiFrCQ8XYxHvGOGiNHhXs9IlLHPGrIvVmyLPzZ6ZOaNC6ksNJOgnXiR7ZPzLUlJuHwXDbsR0dPfRC1FftXapOhzluVnghUcb1IM3kijVxb5xnMD78lC+e3thXpVxwbJpx2OJRgcwwbmNfpkVG7VG9OlSQ+jSmH3Dou1zqXGqv9SbxDXtOnYgk8xyirifNB+kBi8DJvKZFnaUqA2CAN1o/YfLJpYBGqyN/0IwZxhv9x3S3V83RcX8ddx9NrVELfbI6cl0SfjXWdCSY3oNHbuVSgBJSiF7ZK+qf/BpS4G7Wu5zG7RQd3+y9i8CFVWTTuWKHxfirTmx6TUgXAwTkQjVkseIOo4rHfkhojZyJi9v33AC9jZn7Y478V0fVpRJWJOR56JHJff0Ui2bwsWgMdKQakG4CWOzII+0NCWePPUYhElAZVwNnvq1XvVez0w3otcJ1e36QzKH6mcquzeLPi9GlciK7A2GFOtXH3pUbP3q1MS99nOW7E8rD72Xl++71+cXiIA8dGqTA5P3Vopn87aNZ03SqgM4FqHCKr3Nr0pwN9rQFPd0Lpt0ewbw+IQcmZaZ7tTFgx0kOqqtiIgkRpWDVFq/ZDcLMUlqcN6z/HraIYfBS4tc56E8fOTxg6iQUHS06QctO4eKDu7tx5MkAi4RsFJV6yR1yUvL9s+LNNUoYI8H0Ye0H5eST6P3FkXYdG1xtY+SluYQkckLYid3osFyE+pJDt1k9CqiX3zIRBRV8oEFfCQ2I6PRktpY39+Q1UBfEsVmwXrTMnpB9Q90/2B/Y+NcNslNOynFBzmciyXOzV1VOpHgO/JOWou+Q2KPO1yL/mZR+ElLPZUpkmTS3ITXMlz1nit90rkvzseNFXkHEZg7Z7zmvmJ7/yHedCt5v2Je0ZwmUAo6ZMMoCFPN7iE1c9id2fwNa56sKZ20jVvHUVuzH/H2F91cJgRRRinjehqGdcfSsHxRjjjHdUM492Lixaqh0HhSjhAsMEoXKu/HvBReU3yCeLnAx6RV6CW+flgv0KsSBrgzbRcVCjoqyTo+57kIW6kmdNoDTiFF4LsYH04DzE2od9QCRRR6OWpp7FasIU6HWgb/9oKcSveF7z5q2RslXOUKZGbWp/Kq4MhLa7pYd6nTiLZacjAf/+9e5ngQnTQGFcEXe2VRJMpRIUgE8UFkt/RR1vA7scnePgvfgQB65Dc0h0RuhP9OL2si6j1jUSWoQaQcstgocP66WMA3PpQFq8cZ3ZZ1QRlvkS86Tqta2edReICnVVDDJTiIGXV3aw4AvKtPDdaBct50VTxJxFkAFDLMp+hUEUnVSIpshlVFW/eRJ4/OhoKx8+dFS/9N1UsCFIlCm4ss5SmcpaOK7cqJZCT/+riBl6jdXik5i9CfAEmY9tqCYbe/Hdk0XzaQ9GxNdxhmEc5bMvTdzInGixPhhiYLBHkfGI9TR7JisHfafpSADWbycZTiSuLpbL3ZIZWWTAupZPuLQw9MMZgyQjV6ZtfaPdP+CJsei4GUV9thSaSGL35iAOnh5OKx4zokaX3nHdogoz+Ji7CqFcjFgUPvX+bFuGE86CWeyCb2BGJsIy8Jj2TkrWxbmlol5ScXUcYbbL1OErh10h1N5z2MbDRLOTIjZhmfljbmGolpKIFz2Wvq2t4aMeNFRJ53375Dc6qBuFCjLd7EoaUpSWDhzVz7QYPaCv6yv1slVDjczj4g+CBarhXfJZXfqUAW6e4TXzdkmJkAyfzWKmGzYzwvl6HnWpsSIc06+az9sUo1ynyUT6uvzqL0tfpYnlyM9KFn1iX+WGoxcU3kQrBCO0IJweK7lW5O48KjbqUDHl25DZHEHIGorqHL4F1Vy5IFj9akbbdLt3GAcKVuF00BBnsLzvbTPZ3mPyldiXGkoZK1XSzCT/Gd0OVoWrXsGRJZvJPfrADsKqqR+TCOY2lB4vxmJB4x/WqpINBCuDUwOuLUbUsejw+iiYGdkxoep4dmGBaDxa6X6ck8mfGfnlC/mRIryTPDVWCbUUY83zVFX7CaWC/ptxqppcuhGFBsU9g7SamVI0i3O8GEMQnF1Xlu+taQwG4TleEhCKCLHmKFJNxRw8aD80qc96oBRs/fXxMttvtS4o8KVLo6zz++P29udHXqf9mKaloSQmfoi5fN2NJkoJedlyTySc/4TLW7txexwB66MKq7zDgBbzOKacT6WDCMYc6ynYUDD5p+vq2xcrvT9shns5aqQJ2uGhbtS1hdB0u7vqlDllgM2rIWtm4lLt95kl8wtGHapgFHnRRjq85F+Ovt0NfJu2CWMnSfimaj+deViWHeqAwHWQ1cGTAWaRyeCv2xrkJclcUdqNsXSjPQXlfiIVslYnZlYuWefiSe//fdcHE/q9Ccmqny7kAX5sgCbDYWipnOt287gTnL3rW0KER11L0C/tfmqVuhWH4L65RbPEFHt4Y3AWnLvUS3BLlpyPMyXqLp0lxplw6bV+ED9NrVCbyXvl/RuRdHrPNCQ8ompxFhHLXnUfyCSInffk3/RGml4EyBCKAYlMgwp3RiTrrWeCLr8PtHlKS0QIDxjKVIcS1zlYQ0ZoXUrIAbBbHUilrU2nR/qawUoBNdhvec3NUlfn0vsKHH1wDUpd592L1+p+s8khAns2qbFc9HBp1I9ndpAF2DdnIptDQbhePQ/Taz2CoHAGL6h7fvcmQVU+Wxz0/g9tnjVgxs9+0WeCwcPVs9gMnCeFeIhJtz1KFTEYSuicx7ThQ09VFtYJ2x6vXZf11X/S3auh8RtJoo2Tb7KUWjS51qabLEblh2arA3MlwVjVW1MTAxa9Pu3pGFVtlp75sTPOp09lMREr/uByjo2UJl6ZVYnfeMaZty1yb1VGxzDaEs9dCF2AF8oO3L0Wq+O2Ye4iJFCdHVoxG3BBstoBk+Dp93KWNOVujidsLctqEZcq546yQabmkkyspLS/DQSe65kqUxh+Sul+S4OCdfKlf0ZUjM4KSlaI7l7Hb2ROLdKBcwa1OP4d2gbnmwzCIBt4uRCpuRJplY8tAinp9Xa4DPEsU8oPFK/VDflPXucjW46dTcPIklOW6S97rIFuRg1CDVtY2VV3G5HjLZOksW/d+b/GIshQ9smjPOEUmu7bR4mIojGKP1d3QKdxe5i9TSAu8lzRxt3t6YpGgRRkm4llOyffcGtRzX7pgeVRG2m8kEZKfaC6MaqRBFZRbdTEu1tIFZOR6DaMupHOoBPjfsCpH0PkYgQAU8chd4qyjjxm425AgHPgEEJhDlBxTpViZ7S22rTIRwZeYknvr7uu8kWNrIkC0eAvaI9vBZMDaz+LSoKAoDenidfq6hquPgACrFFxbDnXz6pPcg0RpO3UXRVLlfE9sxvQWREd3ImXGqy6ff4p3q2hrD+AuIL/0ue/Gh1PFvXuKGyw9MEVWBt+1Y4qDaWJuzZAVeLvO51d5ueDxi6Qi/fjcSb3vAuJiun1b4vRn81HoQr1kLzUhRgXcYhXKKx4+3YtT1tRFoG+03ygk5VUdFaK/ztBhk8i80/yRQmEYOFkpHAOYBjoj+W9QzxkETSzkP/IWuY0EP5RMHWnEyUrpEqvVeRbUWdv463pK+aB47Kcgv3YNpzixC9jLj+CVidrA2KDxiqRXPe6ubH8ZZpglE8bgDyrv1wRjpCfz5kizWK0hd5ByqJTXI4lpRM3Ap4vFKqKWTEULk+V+qhxbxbaLR7qV0l5TFbR1fbkB1rV2/yXJJm3EB1kYCjhNSMauelFzPe2GEl2X38uub2NxMOkqCGIqvZHShcZrvV3kGMa7x9LGSCrQW31J1UkOIl1b7+akUuhRTXuS5hIyYlm7CkWlpcOoN5xE/VkY4KFZU8rcTuV1IuMr7A0eazkZ6cBDiySLPsnaMV3u7fT947y40P1ohpg/iDUDwK1Ovyn5xivEdZV/z5fqawG71j6kQt497dZCAPxsbjwV3ADJoh+/oVUmLi4pnXw9Y2F0NIfe6/WbNKvmQpuoCt6LtJOUg3lnSDSDia3VQlRa5GE3r9WIfOHt1+4vdJvg8lUeEVPMCziJLRYtRpD1VR768pXc0yAnViVE+H2pxoR6aibhldSv2TTUL9Xiq2s7OKPpI+mWyR8Vg0u38W7niStVuT2KnxI09bSqhc2uyE9nn+cfbk6X3jZMcccOra+UaSfIkM8E8f88eEGKQOHU5bPpxJKk6yVtRi8bTEshkqmQgjceOcSG0XwvE7TidB2mLtexmbbR5i6s5mFEZFyxKO8RMdy8/v5lesWwJERWs6MbsYVKksym01ADmXZtItkibknmvE4B2sxTHUBMqG9E8iuWeQe/Sdpm5rrry+8jWKaMuxNeRTVh9lJ3PgQ0lFPvGwpybu44iWVM2SPQC8DdnR+NJlaiUI9bayNvlTw6T3JguyZyyQ4nSy9vvJcfaLI0sWNLowMSL+4YoBdRhs/lrySuJZJX8P6Gt/RnOaeuw9rsx4ppgHqP+s35IRiMvb9tpXoAMMgev0nfVfsj6U4ykfFaZMs6N5GUYLZyRL28xst5BsBhBoKWSTyff5zaXnY5Q8QAqI9oaVz3j/SAaeZpyRYqjt2Q2PGqtP0rKIS4Y6FfvY9U9rsdWPhgqjldFNzbH466bV8NDbOwkq6i2E2br7//3Fwm3/fYaBGL5iDd7rjNYq38FZrCT8ShzE4oHWhmyavSyX/c1+2RcptS9Y8bFnKtJPQyqyAO2JMsnUqMsJxOICwGpQiHU/C6oYyXq1G9PMFUmraXRhBnPRFMNnSIM0UhpEj3Ln4uPw0Px+ulgPOakYWqzogYqEg+qYtCid/AJOj2a4mH/yCiQupS4ibKNOPEn63sPEEfkTwSiIX410yW9xrhsjbZhZg1okPaZAu0pJjwDbuXqLHc5pW1knupCtz03OveXtZPygKyEV/pcmLXnAoxIRtazlcjMiva2KNoJ6fkOh8uXNmD0dpV2OXHfBYyAOJ7D5ThIquOO64J0bdx9CS9NEixLcqlGlZphvrwqIAjDbVNGufuYKWJoYg4S//7/1eoItffeVWouE604amlSfMYmu9jfLNoe3YAO9RmduTuN+gn72jPrnWElcClIRDme5jx2+UjOJGSw2XHmy6cbgv33F4lkKSBFNuC3ZUEoeNY6zb8JXGmvLHfr3b02K0WGQlQdDQfrNLU4FDdzZg6Y7331tTLFUkt4DGYoCSGwD+7Wg6NxgNNIJkpwxRI4wERkG913dy5i0baQI2RwBDe7/rS1jx2Zpdtt44JBQmJugEWsIfQDq6MlnKxbOF4ZEoPmtdWNFvss4ap1v9tCHCNt4CW20gbz6+maeAxzCk/a1/c63lXHXOlHj9suudTqsK/ujah1OEvRsaFgoAHxBHj3zBLykz17YQMYuXG82MKxvuyjRgDukGxAjexEdEcIdJAzHc2fwLGCJ1NWfmq9FoflNNpPnb3vprqteLNhW8fpkqWIS9LIh7uX1zduGdpgoJJWVmaS/bnkoiL+fwr41u5XFzsGS6/tp0EX3gMeXT1pJ9dKznQG/HiOX/BTOd0tueAC5OZDWqXXrHDHVBDMWeaWkD8++NESMjMiXsr3cjCBfb0pQKsOMgsuNXT9ARFjUg72JqG+JLBRSqDoxaXn8OtPVBDmGe69DLzpbMic2rVLn6KznerDOEv68BMpRho29vgEvPv0svvx+oPcxT6rjMTYG9K5q7ZhQuHy8dd9k3a45cLas6BIPIHBG9Xk4JIOySiO5JyocUlx55pHrkKndZAYeT/SHw8DuM5GC45Fr+CzTaC/tdOHuuR9zbH0JTEBVMygvS60qGOj388475b1vXruCAA8fmiNQrTCSGntrT3vnnF9smQHchNscs9oh+wa/H8AGbM0XbDs2gxEbvJq28w1rgI2dIn1E4J9bumjt+AFyGWqZNxWREXECRITDQSjokm418xgXl5fd591fGvbkhzkMK3xL5PEQw6NZF7cc37cSnEetKwSI/ywbRMqpcJOygoCNpQrYv4Um+BnozQjDU61toqnx6PNai863PjNSvtjFgMmAlzaD++Wp8S4V5GPo02JX3BnBXIt207JeK7OQgmCvWyarHeR3C4sVhifKQyKVKHNWMTNhmCr4eW5zhKyY6KM9teanbSg1E25Rj6TZPz6kF5QZ7m/zwq2RxfJGgGarq99OsNedT8b9CMS8GnMpvehKdhWEP/6fYql4shRFSFxevlJuLr2ZOHQ9gLZqAacW6YdZVstU43s4zIJQpkWC7SH45AKDcCJJLHfqnPAjY6G59itqRnB6zgm5v6SiLGV6rNC/YLC6SK3l3JGVrruHlHkX/797l34ngiAe42+pQx/EIQNcD0DzTpHQXK0EOniqA1r+jLwy75J3qM9iy5KJzO0mwW0N2iwbqtUiwEsFQUCkTjddqEcMzuTu83hLuPVDdg4n9KPnuYPvSJmV/WSlMRTI6eaOCimLZzQibsdNhanCJ+jUJ7FQjPj/v1hs4jlKChMy/8j2UZMrqK6GSOIg5XHxaWpE5UV8YiMNp3uHqVFKxB/7OXbG5XPCdssbJcVP0eS87B7efmZSNDW1iH3lydSPS2lDO8m8WXaaRo3xXipQeybCwNlKeDz8oW/8cis5MbzPdK0ADsrlrIRcoa7qP5CP81Vs/YloSfYCu3TeAIwuYQJppTnAIDQSwRRM6IjwruQv6GyCbtpaqUnxCfX0+uFz3wQIFFhggYoNWf155qLSDPxh+OCun9maFZ2hrxKeU/hmz/87VWmJoqcx1EuvMwax8VwkYl711vUdBn10AYveVXJHBeQyrPEybekfu53b7+eDPrpNqWt3yw/JBsa36mjwT1IVxPhC9E8vYTwgpB+D7HpWzaYIP3Q1Co3uov9bwo8jT/tZdSIoSNIeMGDBQbVQOkZJi/wz1JdZDhWMuebDyVX/BLTWz4Rkkv7m4Qbn4XWl8KiGdpzegFoH5z1jzoAPnIrJj4OEDfF1KhYyG1XLUneUYayEx+7ykoLCS1PLpLFaezjVzUTbRiecrT7+TGgX3ZWmeHGrQ+lEe1xR7EA+vJeq2PArfN2lrXnqH58U7ab7REDL2f38sbON/1eVFMvJrXW+r9bOaKDFr1rUdto9qiAgUos17rx4ap5RPHi1nSLjUiffkKzVc7RzMrxvwfiNtnVUE1L1/ayLbJhR2/Ay1lQIYnbSbG5TV810cItxyajvAnZV8M8D4f0k4D3MXe1nTeff3z7Hm2bvTxPJTGqbDbM3ppNSpD7YzyW77/zlbgv6A0IAzudi9qv07RtIrC6vGjyi+ZJ7R90qz0bX+NIl1mDrDtrG++R40jPsmH1clijq+7+JX7kTapwCp5VRumBP6tZJsusyd9mlubi9CjcrRhvHs0YOccYptKOgiH/gLTssvscPchdmHbN9IcvP4168vWjmiDinMarMMvRknFJtek/TY/7iCqr9Sy8lIirWbuU5d6Zm7WSA/a4t2AVsyjiQGrdnWW7qsueHNhl/PDOdpgUwIqpiGcJh5Lkd3rly5g4ow2ge5F1xMvbS5RdOq6Vx1dIsp4lIDjYzEqc9/qD9nISHifeivaEAILeI3W+fBkd67iPt6p4ZtmYC2ahHQm42jm6nrF+k13iA9oTZRBKb2TrjhGbyCGd7EMXtWw8HD+kEXOe2dDJOOIzSsHt9JBsSY60dfdArow2KEoh6jNu722BSjVfNhvowoHag/mhcjiQYi9R2yzCTZReE+HoxlbbHWtQeBoTZm51SegHjPsu8kGsopu6RjEtFM82yOusCSP5mi9/MVFUOj1t/7vd0LebWu2Q7WsfEVJNwcbgh5mXQhrtAHxisbharjBUZ+g7pxGXKvgvZiU1BatMeyNiSF2kN1b2eww2Hv5c6tU/mA2kbQS89C9X3fi4mldS5UxMKhShmlR5qi1ThqJElWh5aZhEnayhTP9VgHMFVKzhLC2l90iAUmoxkAWImiRUVS2eonEF1OlOh8pgsUeO1/77tGiLl/QhjGt8PWNYJXOUappFukoeNUG2k/z5spsunl3rVj9/f/u5Gy+1JUTtxzy2kzkdpd9FCeQJ1UJBusgxtmy+6McL4Pr0C6IBFCTsX/+n/4Wdzc0CrZ3cmibPQU7j4VCEWZ0w3kJIQECwWuZ+M+p+nzt5J1lFpBetLhLZPKqTwMDA2jGzMKMiqvoczZKO10R2zBIJLKXKn0ktXoOTfPOAKXJABNNGQKuViHuzY72b5Jd9WknXH5ckq8vaUDOk9pLbPsCXljNWIpR6gu7gEDX3NV7jstznHKG8m2Oc5n0eyEN73sb2L1Gsqz8/I7E0QY2wKaTFvW0fiTqwVWR6rSA70hhqsUe5pJ/bA1ZrSD8ap1ozro9KOCp5BLQUrus4jJvOI8iEUQT3Tn4Wl2nbxlxAf1U5g2CeM8m4JT6spBfIjuVQdfAEkp+s4YoYw/E7n7/t6hTtjcLu7tVyRIP92pmi/vZDiqjX7SZOvGDGs6kAxXJPYZUWQjpr1irL7axGJurbradQlXS7levxgW/9g4ChwCZknE0PL9ogwNNMML1Au5C4l40/44lAwjS09UJQV5jSo8TZm5ohzFmLf1BH08NKJALsnot7Hz5UI4uhjCjCaZTjn6gZlKPj4C2J52vqgjhhuSGjHdJmSlHlr//5r3/717/7p/9Iwni3B5JSeLV7e4ojkzJe7YfasrO1wvuxeL0/qt6M0NQUIder9rIpsoySh83duQFq1qpmnVmDdSYaH+3q7rm5w/m8zg9dqHm2U0d8YBAxEQLsOtIOlVNPPNGhyJs94qXVYT8jJmwMdhvRnxriuYpchu+EDiBViyeJa+IvDKtZkny1R1O6/mAbryjJ3Z27NP9I2hImbxLXxDM50SqlwkL85y83U3g90vBdFWGnbLejnWVeeGHDOVh9Wag16SDksj6K15TN9sbUo6gIs3fI2Y4cG4F63pai+oJsK/x30eRpp1z+7l5/4UzAjvUuwk8nOIhWRw+l5wpG7nUUKAXVVdWIcRXL0fZ46sJLpFD1jX2KyV3SaFjHWpRjzXLj+5Zi+iUoji85zXVgjE+deVqjChgNjEIiUfqQi7yLQOdePKQui6Zwh03d5io7Ldbnu8tcZLOa1Rcc3fFDo6EUV7jQybAOay9SLXwvu3KeZDn57n4qHomGZacyvMPtMCdoppgRDsQA4PSlnExxZrvXtB3tM3IFMq2tb64eZjweWpf4TJ/s+KRd2CHtWSTWbEmLlJlhiZHP8Nrutyam7qONPeub8WE1hRfdXqDB91WsDet9DwctYKLChVdaTCSPY84MbD/yQCfTaTlILBvnUWSDGzHnvYBKhYWi+v10gtgw4wD0WQqrnam3JLtxBS8vv2ibsxXorHx4SiKpdEBvmFQdE4C+dndNsCLqtq6ui/sLucL2K7ohp/WT8co7AyQYvkubPJVBzfFU3muDLYFW3VR7Sz70KsLr+ABxwnv3fwo7pQQd8eGWifpsI3ugXX4Tp26V24c/vRZ96RXBPbC6dwO26ftLpJxrqSTj0WDyOAknUXBrOo0qZ7xanM2GU8mXeOu5oDvOs5s7a6FNLI0QRwOByMJuMicHFHSDx+gmubJBVAm+2lpvxurSCtDr7BKzu9MxkEevhV0RZJ00Q42POiZWUq3oyI41k4NdB9GNtPQTtNJbO28myouWJPgNrya+okin0ZIzedTxV2lSSimqHm0/TPQ8rGLcHMdxE+ljIq/CRmrnq7zg4GzBg/byYGYC8ePliVt5VYiQ8kMzek461JiTRku1t96NAGF7XV64HEuGgUtrzuEk8dcZxk5W9gLToAItcBxHtNVjUL0XufXURgDvsYq0Saqlp7uO2Ex+ECGd2cVG+WwPHuVEpZGC0HezL6E+yiTSclkRp8/RLr7KCTL+dw3GbuxAAUaNG2EJ8pXEGUE1U8vBuztSYPAQFPjcFMapuam2fx+8/K5TSh6F7vhOL99erFGnzuSysoNOTSQSRLf2s5v0OFyvz8Cw4tBUsqx7GLu//JDwjVYOK5Lt7VY2M6+pNB4TIp5rJvg2FLGc9N7j8qz71FUY5Ub0T3+RmDduK1VmATJY0+7bPBspNN2bDXFBboZHpsKoE1CEgD1sQ9zUDZQCvMD3qvb5q29vG4fDEjWqgzFoaMcHdrtapalt/eSkVH/+wUb2AEF2rEYIJ5uPxGIT5YlwEFk3nrR6KVMnlxW2CBrg3WnjfVFb7jTRjUbb3m8H7Ecj6V4aY4GnES+MMRr8l5/Pj1Bh28f4IefIsOUQj9GWKc2h1TKmHda4Qu8A6CzMWv9emKBzmVMNBrGG2J8Mm/1czyVPSckF/jYpPnll9I9/KQz6LpdRyhHtbqlkCqVVLC4hF3vBCYi07MSOkxqR3BQ1drFBH8kW/tjDMFYB4YOcVRMLJHMq6HGECgaYUEOixWDBxpTWwKJaEMlFXgWF+Ngq/0hJk0I/So1oeV/R3I/7JBC65nq93BfLJutfXKLzliqQhknZV8MlZscD4EnJ3mFhX+iCU9ZwfcxlUBS3vDGkeEFLe61xLY4aP0XGORfBf4DpzSqY22n8YyUm3ggeOVKNBNwMYF+rmnlgRFZQCD32TV4ro2zMR6mQ91BqkCj+rlcXjeQwP+n1B0OXCDG8wL3WjqQDJras2eOpYmrohF7Yg+/N0Uj8F7nnrHnRXVPVuTauK+dcqRVd852Kpzz9ipF0Yrzqz/gF8XZWYeP0rONtbZyIGQaXOTSbhoOu8voub6evTuv2u6XJiK52HOpVJH0pH00nRD007l032khXt5LfJWoRy6XVorKP2sZIBchrUqNsVsWVGpDvXM6rar3oj3frFRLQ0qZ1GBhrYlBE9K3yro22WSf05SsofbPnHpJbON9XKfmOF69o5AXfRhndjIhPAe+RmTi4HSO0GO3L9mfEJGEWSqx26z/KkwNEpb6je/2yNX5I7cI9Zo5LxPiheQhqm1FrCKhBiIKUB1ZNzXmkcZVa0qWWSZ+b5FsRnfp9XK3tke1GtymOLp8ykZHHMC8K7A/3GEoVX6lLB3n7SUtrmfFafDalm35tvX0aDPVXv9QUOy3Y8VUvUG6YjOLBSm4kK0rE6Bq1CTloP36rJQlOIRtdBPvr+CW1eLX9aG7qUp8Bf0X5k0YjKV6+yV2coiCiH12/hO7A9av3/f+Zes9mSc4yDfN7/Ytd1tvju3v9/1iblZlVlafSlNJUdZ01gbolIQk/gx3cgKCBmUEIgUDCRszsbgRMhJBiQyMx82VAtOZv7HPd95un9eG8COmcqjSvecxtqkSPkKR4s7Og0m6qd1VCdprlAdth7Cw2zb+J78snpo2LzXXKUuppq4BfFjvLaRhTtJ2EUivh2MyVd3cZs0gR48WAFY0mL4A9x52je2U7SKIjAYoLeDPUqzLbeGvRSAMoG6c5e8gkJai4UhbBXWTKPhNg3ukRr0Xip/U64OFebSv1h2E7i79XF4Pw8n2hEJlQETUAlJ6JnvoqNelKSUyWtm68loahCqwbPn7dYRO6KLcf8omJh6IannEuxwwJlkQ1TYRUJU2cGsq5Btyxle49heB/nIxJhrmXjw1RXW5TLVAL2d5d/F6tub66kbt4rW4WYJTyVgAfAeAuebTKiczCd8L9TW2bCOsHOT5N46xaUyq1JUYtC7uzGG++ii1cfL4I/NdAYeTfFI8V8GPvrp46cz0JRD35/N0e+/XxRrNJsWeKQnxcAZ2r8MwGVR/xW1NW1xXYN0gvuDsknaFy1ipdqPWVqvczkBAgYL4WJZmqSJfyRFHJU9AVe6K9sRdbpB4G4pj4C9sFo5/Ikq7u0+vSkZoy3G4v+Az5t8yEicwzGqdA6vSCqMOPmdCGebIGihNJ/SWmSTooobqU1Gd4mI4e1xWy5TDXF5JQHMv7pkjlt1V1EXbQEd4aDUS7QvN/j/oEAWGsz9Fl2WG2sjm7PEeh9miwXW9mcIn68uK6uylXasAyWZLs9V4c5mOmXqR0h5+UOqQ+2EnpXuUjzhNbpEWEGLGcYrKUjUJ0Y5vfeXme3jk/oeuiss1TQqsfByN1d8odejgkBwlORqYbB4eFVUDAW8H9sOls/FS1sx86sL3eFnUXkaY2nW4d/daIWeggFYREcUfNqUlBnKz37XplygUX7KAwSa/Wi7PzO7IM2M2oir7DRCoOtGKuFFug7uginwk0gCCK0sepjOSA/yb/cEAk6pp2q7FT8QPaEmrHy+mIQsdyStUntU7K2Uh8Jv2z0YooGkd+8h03edBNCUKJUlmkgvAjspKV8u14R5HkHBNQXc6MiCSBexLK18qrvYTP1HAnN8lle4oDTewf2JnFSRJHAK2OveORQkX9HKU+wriGQrrUFal1dU8cVUc3/fjYa0tlbCOOnVBPktIYC6odEiMolUmFuxosBCdxaD3zfSUBaLrzkTz6RLqDWRBUQMDpGG65Nz6mLkpTtXatz8vMpAmd+LMrSy6J8PgaB8bluPA2X8yIi+TYym7ckl8D2x2TJpcgzNmUZ0qAAJ+0pe0wU/96J9UYAboSCrlW4bfL82mXDqw6a5ZFZJHHZY/EUiMIVrM7d1+sjJz5TkyZeiXO1iyJTc9oMWthSaB1WQJPUnu2KWl26v7bLinFj66QCFDLzZEVYXFUOriWskphzKNYsLc6mYNpIfP2DPq7xKZIKV+hwme+SKTruL6YY/cTAzUSTWXeu+TsDm4uWaRcy89zvzjL7I9UPKFG1reJOBDoHj/LJB9o0fZE6u06o9QLxJt2mTgEIgbt3bTUUx9v4aRdOjUHa6waLEAMdA24vCIwSfkdigh2W7XgNr1iZXcWhRSi7h8/E8esEq7Y03s8dQYlKTPpuFwDD2bbBr4JX1waH4ktxkc2Zj1vOnVND+WmB7g0qlVmTcLu2pkgtbeDyzapGi+JiTiH469LIeDwclYEHs+0HgBKsCnyMa05VegswB+K13+0a8OomomxPPE2MlPNVoa1qR4Wew5q1J2cq6d+iuAahXRiGYCcvV12l7I/ut3j4inEC1dVA/sYMrllZAko6LdPEs1qV3fCNoG4ERDpEgO/2ew5fuX06uIC6Z1MgYj3rIw+iGRRoEiIiuWCx1uvv/1pbEAE8abxNgw8uT2C4JrggxRRXNgRHs8qMhTbmG6GfveRtMZwnAZp0ZAOyKhvlAr+IRYg//ocne8WsaFWtox6trTNTdtQ+zhmyywhXY+CxyoCq7oxWaFJknJydbwUtizSPMv2dr2acHjxVsvYcG+kMFQSJalBHtH5iFv20cqHOWhIU2zEYO0LCqjyB0kyLVTBL+PItfoKBiIxS1C9r0V0iVixVzUGpp0qcZHrxKw1FWI40vU7Pz1dLIdcBYK9FehOqVDiPu2iM3bosbYRWBqz64inFdbF87DMWqlkQS/2NuGMl98OyamlTyRwecrLx7SROr9w2BKjXdUSM2m6OsFKoOsdLFdNulTeemIkgJitlmqrgyS1Wcq2bay0aZHc8IQGnxu/5T6Z72JrtpizIam3OWvwMbvHE10STgN7zZrlmjQPeZXrSZ2abgfKDOUG+lyIr2IL+gTvabaHyNMwVkEl3+IskvLCCpUrS7+KQhIPb2rjbKlSDaCUCL8s5HMnDcSCcaHLyu0zFbzbkvazy4y2/lViMVK1JlBBY0FSDMC+VMNY0fcZ5HJ5dn6ldKJTLMzBL06KtZ+wup4QWKlmy1I4UORDSADGJN2S7yGKLllNz6dysA1IRIPU4NU0dKal8+UqJiryfUyeEuQOKMOrmGrxySjDSMpWjpUJioMU1zaJh6pakyW2l8Ehk1wefMrHYbcim8MhZiXfIlgWkz3WCJ0qBb+um28neTxlAJzuCbrqUH4bu33mfuPFqYoMlp5uM4DbFDHlAuIoUq3R0eKJ2nDZp594pUnzayeCRmOV+KxW5WKzMfVVawf6JTTarNb2jdBerMVkEJCDC1Z5BZL1Di4pjgJ4OuBAMouMSGhMIs9xbBo/Ncyu5pKgTWiFbDamjy/w68r7MulKscVHGp2ImhDeErImQgAVcOQRpDOkpuGmmLKe1re0KFh8kcVnhpUJaW1UzCZLKqd/eEZar66yjlaQwCIrvg9dSt1NzPb12rYqH0Yr5MyGgsC57+5Tq9pE9ruLw8W6ADJIbKa2u1lss2OkFxtX+s5iO2+qWs1r08g6jjG1pOE4ykRjfyuFte9qCEu62FVlyd9SRaJ9ki2TohHFg21MsiZLZZchN9YAqQj/QbrsLBJJNg8ZwqTAd9YuXm6UL9ieotY+2an8aAmQW0uyYzzRy7sntNvjA5uGqlfkZi7VRghm8M8GPWXk6eip1dYMgi8ml4UmVxUzQe4rywGjxBOPl5YOm0D8ytEiuK4MjxHjLm5i403845r2HqV+lmgytY68q3GxUS3bbmZ1cXESXiQTqfcGrCxV4KYoYSVVcIuxc24zATzLvZ4bVfcs7ycgoW9/QloKkyK5vVv/kFJG+iHgnOPVb7qlBFBuiAXgGubO40FCE1OC7ZIgK3eJWxkNScHzsGErdE7JtC15oQigsqvUgdwceaKCIObyH4tPjs3rAJ3TRwjaPJwGe+zQYVzdF9WK/WLKqeGen52REa0XbQMCfNPF3ypZWVM9zAqLlaXcmeex6+ApXJzr0NxmNKlz21HiE/Yh8ZsU+CZRl6oUv1FJ+eL84pL4O+ZO61646TgxN0jK5Q2IAZYYmShrEkeW9VqtsK3AL4M1lfepGCIVClYzHOouYooRTL5FomeAY4LvjF7WsSr2bhXlJkfxFC0vqElQyVsEezWjvYYxOaaDOzpX2Cw8Vp6tJD1AFbHeV3sropsrvJGf9tTbAhl88QxmeIKJB5Zkft1RjjQR5Rr6MPn711NalMKU5RZRaeJLiJfs32BlDLMRaa9KigNaXoI8Wynx7Apw3hPNoK6z+2REDMW1qr7ZLgkVVNJOkp1qRGindyIyPs8WGWUH2VDZrJLMGGr97CiitIKWtHDtTZa2kjzBTXag4at2PiYV/QiTBYemVHbU6uaY9Cg6LrYoCwJirNQvqG8W5ycXi+Vhb/guDcZ0wMXZgAIXmoxHA2U58crS0gpNtkHv8yguZj85DEBQQWCjm1LHasaUafK1dQAnyDzaA20ijZ9ZEqTr7YV4EEtbxhFFfUw2LjS/Cp1kEnwjbjl2NkS1eONaRyVobtXP92mmcJguhAzVS++c9h5nzUlB42GETCZf7CjhUvMWoENc8ltfmHSs4G9PY7IyjVOXYOHlOmUhq+q+mjt1DVYhUr+nhFxUeTAbJIXBrbABJTtjPvfuyZni2NQ4slAwGLM1Ffl+bExkj8irJ7sue5v0uDY2OgkZHFYMWPgYD2AKp0R7XSyK01WlzQjDKQUvt354rPG3fg7cJ+/ux8FWCqThekYx7V3AXpVJn8A8G25QyD9bL4taVvazrecmMurZ9ME5AeSJmb2T3RoDSZn8RtW2csuqN7kM1Y2rOPm0+T/hqJkHacWF3Wyrlwxgk6PoMjsCCBPtJ++NXLt11Bmk3dxrp0WycdZbXhDjZcRlsaAQzJq51sb7Sc9LdZ1KnS5mdrKZpsYzuKYAbXquwiO8b3p3tyi3dJZS+asdMmMLynXaOV0oEFsV3Y34wy0CC1W50hoVsFIzb9aQK9PiVJv09GqBgEND6098VIBdLtzETkHKqCJv7F1mrrlsnAoiFyeXdOMJhkdx12YGxNLW3+DUuqemStdJMzJ1EDYZmrGZhEDkRewMfJZ+lZ1jPrP+plFEh2ELbZW2yJBV687SFd6CEQ3HA4O0pc08W/R2Z87taMoi1VH1JAZrIxun4Ki1KlZsn7snokbTkGLk1p6+N9M2ns1Tk/oucTQjUYVdW7nzcbUSmiYe2BbabMygDA9yL8FhYQDc0q2WqWGHUtezFzxoMyFopFRXTBYVfjLJ4ZyfnUYch56UJTMyOXRCtFhGym0zhWpuoGiTH4DuVDY6sThChHmuCS86meiJUhrnOs9TMxAwjstwGRVzcsNycXp1BcaV1T2CC55k67FCtTTBJdzKiO0FyBQiptmcUKJSE2kBPbkeaS/5KSbgatkKn6E8I5eXC8dl61T19OriDCBFaVyJQPf7hH3Mdu5FxfJdU3lT3NKDfcwslc37VG5Sbv1OkDGMla6XL7thRHABSRmM09qtfZD83WB0Tab6Sb6VdX2Boqkn1OnV3bup5cV8cbGOrQdyoazELi+VsksacW3vER3lcf7VksXqUl1862o1YJrJtYYb383JqUSHlfC15pi0Jf1tiySo+TW1T5o9f/ryDxR4VXNvWLpuSel23BCx6DQqXPbIKIbjvveUdP+zAj2spSw+tui0LGub0y7jTRsqPww+vOppuFUSyLTigNlcAwlQAXxR9k7Y0Kcqk+zbsLg4v4zco1qrmtSUt7bZqcEGBYX+QSnq1aD/vZb2hxzBEt5iZ9vu2dYrsnEp+w1dcrrDX7NLLCYRPdaRx0Iaj8dR0yokBjtYINVzyo4QN4SXS8pZ2jRxF0umzGayxCJfTe2WlIXSjHccGwu5c4x7cBw/kPuSyEXVqKSN+XZduZuxqeT9CrM+3vN1t2ndhEA7vWw/5A9iwKA4MTKXHuClrr19a0omoZW4abugCXgAU/VogClIgbwqpKup9qEq3TEdjdTsHG32uDzVmZYyG5SO7lIsezdED4pVsJJr22pJmxR6Uex7zF/UVVcCY7vIrboFJUxhf8zsgi+gvCkB02baQpeShHZxXTaLM4q4naStliBbxDtulsYqJUERyeFbqXumt8nGNilzoSk+unCmugHVHqJBL30oPu5w2Bhv15X4ZkQOt9b2WlqzVqHWsk9vgMZ2Dcq4hQR0yA80rgRNFtjBqohrsse2A7DCbiL7rXRUIK6mzHOfuVcktvVT1rTCoNR8SGXsJtbHg3Lvx5UTc/LUGJ6rL2d3ziK+vru4OEXgORMN2yECWPbMWpQWWMYXkN38SA1zA8JpsjhrgkdXqsssNzItj7VLkENhj843mhRbNCk6EuW6XI1KKrPRNWx6q5n8OhQM4R5Z12JzlXojTWZKpmoLt+KaFHhlNEh01yRDSNmKumSDmg3PCTbU2YkAFii9bJOjmMGDSDoo1aiypKLl/TzbtILaIlIXU8aePqJbquQyzZp7oqEtRDGvbFyTy6eBTGswl6RXQ9v4Ost1Oay1x6ibCSssqK2QHY9er1cV3DHOX9UkdLR24OXlUKZ2FUSoxlqHs+smbUuv9mUnF4CYDupXQRNM7nY0j2TjE+uYR32jPGRXzdd2oH22igShd2xStQbWZslzsEspNO71kTFETOxAQDubK3zUDji9h11KdDdK+/Tunug65oAKezc9Y2dEGsM8vMGwVAoLkrdYKRkaMxo38RHTIGizium3zLg4fFeSh7VhTydzByax4/A6QS92mc2Yy1GQdk9aBGtcfAPXEgGMOk5NThZo+jZhXRwj7U3CGxwbQ2EjSJcEMMgmeLjM91oSLkLVF13VJmc75QZj5SOvkS99/OqkA33YmPY4kQREzNpZHKcwef+gq1T9FlqOIU171QBnwiPUx6FKZGyxvxRWGIVdJNMjNRTdcpDKtYs1wOFLqhVZnOhCZMf0yjcH0P8of0KwkCWyYRU5q2jJ/gHe+Q41ZEgEdbfMbpkfQ9WUqvmb8AYZRt23D1nPGEykk7NhgcRJA4RoalV6Ku9nwy7F7RESNVMEpAf1jR35OJUtjU0g3BQdlB2lEpOGgzKpmOI9uTecmlQlguMIAaxVjPiGZxrgkVR3y33Wq7ax8jyXHOLZ5d349EFPIbKrPtLBa8vJNQktiOmmtVlxf1pc4qEDETGW2LV4wTLD8cTvE0G2rhIE0OhlarU4l6+Toj6yhKonrNXE5wzrKCJCFRDGJrIzCdCgpSuE33iwgUsq3UkiT3azNzGt111sy+cRNkVgknBIKyhD53cvcUlKWxruB+x0/H+S1N3OjRehUmpV5dgo08uMWHW1EjOgKpDkkMlYVTjAOr1zebo4i0AfWcuYkjeZ8PH2wKKZd3HXIeLaOhOzhLR5WfaE5D+JpTVI+6Rbwk8opYy60/QQaoC3pPw9cRPZr9QxRzZCJyCpjbwH2hmQf91J9McWFe4tRTYsMIX1SzGAEpyU1kLjR1a1wtPJiBXUytJ9cbbiYRnHjzQRM5zNp+RObYY+V7SSZIINo4hM6vjffbUVsJjumQuEwtRXdidw27biBW5o00awN7gKIW/DW7gdYHSReStef+wFmYUdVSFF8do+uvIW4fZwMUlrtVVoU2Mb0O2Qsau0+fC8pcGwyZay64zwoFlDcmJfY6ZzvC7VHb0G+Uf1W0V6l/4GaRTL2jQearxpuQLmZSGLEBjMwIC2pOjSy3C3snJVdrWSLi68LxEGlWjt5TZKqG5n8eRIhmWhHFgbAotM4o8N5ifxnXcoUsy11lbSVKLVHVjqnhfWhQG5sRjFi2UHqHaUMiEVj5k8jLIpjp3hOEPgzfxHCgbovFIoOAKyHnelcad2EOZGjkU22aSKJ4aFsbuoWAuhQcgXbpGMXOfPjnXuZmBeqqCYS92KhZzsKFuvQUI+c9CzBJ3cbSzHipWQUJwRpBm7dn5yhyDEOy6VChWDZTskNmeDCg9aijh5HsEToipXZM4Xz2Kd8teVD4gGQbs+1dDmFHDjqV/YJ9TNnA1qTf1a/Z99Z2svHbTxaiVYuLQWr52f4x30aNqqKYXlRyQb07hRnU/JD/PauxrBTrVxqoUSnU06CcSKZmbHFSrD0BORgLA7k6QSGbUX9Eig+Oemnp/d4xTO2FH3CjmW5dblAJ6/zFvYaZIBXCEFQY4ocC+V+b20jgnm1VDuy7mWm3TNEPyKU3dg4lomrFKzsjIUsaikHgIsQmKYkPd26HSufe67nzvoJJXkdLLgo9yi1TGNYrSeUpc8P7mKAAkzrp0T6r7TJZA3U02rLREvY0gKYnl/TD3Y8klgJWRebI3dYqyknrWnXEeoU8iUYHFxGYdTU2EHmHeIiSaONw2o++7sPoUalUuOyItMUH1LYvRUFb1RqMh5x13euTpZ+LhRsK/3HsttdjSD+lN3rbVQCrLrSkfetotf0AG6QXVHj5yteVLKzFk/SibUaFGZ0qFp1mTrNilDlxv7gk3qBCKfgRjq+kNm9iu5My2UEVdZqh3uus4pw1xWZkEqry8yUxs4+iNEryxzHZN+cX7vMrm7DeJyK44moOVuWPYZFYdMuNw1B1tcFGIzhPalWdXshOwiB7oDWruSvY4wEtqkAwWMtYDqAiRYl53gTYjMytqRLdxd2mwVid+lYY3M5XY91SthJmUiMlkV2qcYVQdlmuLD7uAkWgBMJF4HoA4Rl8CfIgasenF3OJQbduN7bK/SGY3wZVIRHwaCUwPO+bM7d2dUR2WHVxte7+XSdgMdJS5ADfzKYlJZve5oOje2uxvGpY44i6LVty03Xoas/mLmySzb4l8gyZBpWqrKFBmPSIZD3e1u+bU3EmduyuT4Q1iFFcmkVE6GU2AV5jatRQiQnMqscpu8w/JaXhkSptjBStDMj+joTEjDOPMwAupbITAPoOigwUT0197Ws8bEGksfSTVVeh5DdkA+RVY1dkyjrJNK6BveM7J3Nv5weqBYdQnHbvao2GXNbiPV+KEUgUc2LO74RIgz3ccTLcloR6Cj0Hqn2CBO8UE9wWoQx0ZXNhpqMxevT6/uneDMSYlQznqNu2I+NmLrSZSl1DFOuzfiU5mSf7/SSlyHnkowPT6aXONcs+oi0kMRivQcFLoDsqSUkKOJovV34JwFcIGkPZL8s5jXTpTteO8RAGVFN0t7jurNb7PRacCeLSTh05qE7LzujvANSLUtBuUeupgOrOO8nEbjgmLLX0OGQ5QN3cPIJqFP7GkUulJ1lCJetzUXyQitNpuLlMqQh91COH8IrBXWpHuJhES8DXqXPo9tswfpuXBr19Umw/QpH61baRWF7NhNyDfasEsaNim9HOvjHKTmbhfUQF7iT9/8mS13O3sKEp4lZxG5tKsqPBAq/ssnktrELP2lKETaD3968KAj0AGuJZ6vJYvjOi9OLvzoUitlIq70oQ+F4O5dJh7k6vw2VN+Di+5roZM/VFSQwzXsy9oHUJ+EvnBRU49Jgqkf0rXLj2rvAACx3XkvIr3slJ+4RvBkM/lN0iPaV4roVT2nApwUwSFVd/bdI1glKbCy76xGjqXdzAG1sllru2ubu6ABqTxeNXw5uYBsyLdHq+vEZrDSrIv/514/QFlbTOh0XiyP0nb1TqampvwMvTUnWyuULDsr/G0tRbCPyHW7115oggdqDkm5XSp0EXt3xmkko5NcyRUHP/3JiHPXVgttBAkG5pa+OKF2SqFGRM/eLS7vnMS2gn6Q8U3JvIt0YU5OzNnr8RMoLNopNZhmGnJjU5aO255UTlOhhsgoQcaLfi659TLmXXaSyN5O3lt4xLxwSOZA1JdHW5QvK4h+V3HXAzTHAjlxzC8Xx0n1fpRzyfuTl3JzNB3Sa0Ybu/puZnNQgMiK62T5hiyZ3EiEByoTWzpBt9txQwPkFrQyhxaSG8zu2210SA/CK4w8O55zmYN4mmiE1KQrg+SCaWshZ954wmH0wg6hzM7dQKB1rTXQ95XLlvGvhFhe1AaIN240ULkSIjNCmeX1DvjqiJBF4x46Oc2BlSG4rNNkixs0zjmoPCqIATLY75RpdaNZJFXySYdzuDPeps/+4RteA7EDY0uSmcopeQkeZCP4KVEovQP5U5ADlnJ7G2thasqdRFhvNWXTo1SIgsvHqodwJcWZqXABgkxLJlRrwGCqFcWRr4IhGm7W9ZP73PKJHGCvbYdgTZxKFJztIL6EYnOQTc7EMXiOCXYuuE6WcBsTOPVrT+Vee8vsx5ygmzNFHwpyOW6O9Qx2K4+iLFrLuCxmAXuEijTzrlVdHnVqguEh5NYOqaCrTTDMD1lU41JvsAunsQt0mUrIQ60STCS2EuwRqIw8CHncCB60iJboBINrjaPV5Rs6faO6WbEnLLq0PItb5CTNQmKgSEyxLGjzVNRTULCRFABG8mgDo8DH9DFas7vJhC+sVkezU/GUW8PYX5JVW+S9i1sQTrKHd2KlcJn7YUyXJaklWWUDd0Jr+x77lZIFuSc7hqEyFxdL9KC/ifTqMu5r6YNvfWxgm8exPuuHN6mG1k0ShaqLpLsso7o1mhRye1dpq0xag53kg3AsQAITBY3Yk69Zq9DUTT8fE18sHo2QXzaGG/Oj9F4E5bX+41Y8zKWh4fnkMHBl1TZ3NCupKAGbinUh8aH4gNi95KIxHMoZZdF2y6QIJHwFuKpU2FB3cRGTGhUypt68FGa7jNjPjYvoF3dIEq854SMq2XUJ2TjzBCh2Wyye0GVH6bbPricHBaNVlXXQxElMXtXGFnB255SZG08ySRLXrIXbIMCtqNjvzy5PToBJ1FueT+zwe8rMZetpyFs9u3Mlg1RqnYTfMFrY8Fq8JoC1o1y4kGVkKUd3we7kNq/QMhG4s8TfhlRdpn7fYAjGURtw7Uq45kE32UdHiOKI5EFhba08zFQtNAVQc1Z7PzbJvRsrRaZ+4JCtuCLXiBUoJjs3i0C2FrmxKJpU/8Yk0odF2F01hFHnHZKahvxQd3jz6F7GaZkMFuuI+Yn3JU9QHkuh9wd7gFtsHVNxtZlsA2mAgNyFqbn0VZK8jAsYUDUQBrJfHCJMFzmxU7fv7AqcvxVl+4TqnOxeNhhkxFapJ0ejVMbtVhC0Cr8IX+zwWWU1CC37QYleIV4GsMUqLsFM82otYVOwoYX6fRPLvVR0QIGPot8yttkkU5egDXN6D4/mMnKZMpnXSuKQr5J8nKNStaXPLu8ZIpQIf3EzYr3ckoeLxb27J4unYmfuIX2NMcdXvWOl5Ckix/R4G2I5gRLSqS8Tio0SdHXDZ8tknR+6pfj9uME2Zrty2k7QcLxneINSv3IsA3ElQ4WxZxPN8PQhYMS/p6/WM+dxLCXx6Ws4YpuzEege9oGTLyzG+njCqhiAG6qPza7KbIxso1jVbuR9XBmlEUlwanvE50Y8aBWUbidtYXTu4i1as7dVWndwqTZ1dSPvGDIJjtdT+aF68CAwe0pJTu+cXthsTD0BNThprQ8bIW9uxgiZzq7OPyQ/YDwIHdgqYqlkkcmbmBC0k5HiSiFzqbaxOmoze34Xgdvi/OwuuMpt2pVmK8SxLw+tzyu0v/rympZgGadob5Fsy0zUtDJphXAu0wjiLTfE0lm9zGxWed3FYbDoaajx4iiHaO/T284myVepTnkfmZGIUiKGLYRjXUY6BSRLwYXFFakMnd65OH0CmELZIUkbjH0yG/TUzwDnszXewBgC/bWQ7YXyzbnqc5NV2tKKWD77yuU4YItrooOpF2nIzmGJLF/peJ6k31w13d4HSCX1zW6hKomdpZsJvhALl8Iicr40uQ69Svlk2QUWnw0KLnGxY+X6wig5l1g6GyI9N92AzPUy0R0ysXBYBIOVhFJDtDMnO56uiMMLsrrkVamIaiaSurQ4Y6W6HYiY2DKfkoDMsLDMnqRmD8fWjs6ADPxigfmDjUBzXvWt2mcgE4Asl97OaMl/C1/TG9555ZpARmWlLBI5hkIzcj2LuGNDwIDvSlmUPWfM7SkTF76RNRQL/jCXNchk9ZliXTsmRFkG9Kn+9/SONKmW2YBmb2RHMqI6JuCrIe2s+GFaRg7N9lpkJsBuqyJpdA6mnU/GABfWb91VyhCs6iKJUqkDa8vaCdhX0Upti8Y9vLzcgt1ce1/mWDi7cx5/CG7A6AjmCF0f2lKJZVcnZ7FOGJadUmbSUDb9zGAEne1DUyogiScuka6i3KgAttVRN5iJxoxtnQkMdD8Nd5QvNL6jTRO7wLnoyPY9rKtF3qg4V9FLlPhjB4BLgrhwrbq4pcasLbBISG2OcgpNcPWe4LSSX1fZJF1dqQ9W4uW2sc0Le8WBKaCVahg5aQ3WDk9F0Fnv5HBUyeYsKZ+CMYmjXXb0vY/ZVivQQgGq641yCKEbaeUYEnhQLZyMiymT9lxlQJmyBKjcVWxWsekPx3yTojFtgUc+dDiYPYyVCwJjMDPFdDtY8HWuBixsGW0RBTb1UgedgUjLODBm/2GyNBsHDwBOByMzKrMbuwTh3wgGvTWefcgo51GhGdXtgQw7o+NcJxTMBOePupDxmCBfiPmVsbC2XijMTe9hCY06JPcAySaM7ofIl8GtU2DBdAkbwH6FOZwSkrHZ+F7OVwhGwX5YLyNpnLaxFdtPHg5aD3q7Hlw+knY4EvTUkjdy1Rw2ShoLM1otftM04m1WiSUqOLsaPxuq23SS7EEhvtOQNAMQIe0nHf9MQPdXYT+NqaBMZKK9j5PVbWyq7vOmaHZe/MPZ1Z1FuetyUHJtWvxrg263EWQYzc5WkJS+ubCyFzcvsctUnZlNH0isi9QWQATGylFx9Wd3z+PQzWWooXeSeLXdlPT2kw+h6RTbcSFt1spuJrvYrerRLtaEOYbAuoOifEcKHnkpwggZIP7GxmxD8c3jOJblE69GhUkFA8uNwslVUrO1q1XcAAyKZQO/vvIOxIGiv3jr1Q+5D+iZN5LMp82aFIF146dXF+eLqzsnt7sV0iKJRFytP0xcVrTjInqBtlycy7nOytF4BhmsNkdpmQOY7xvLuxSKOeHWHltR51XO2kPApURsQ5rkBeNJp75LKy/ode0DJcKc3jOxoaulxZpPTbKZjudpnkbP485NWNsI6wXfaitKeCEF0VEWiYnUjtbcIAMiyJYoPIBG7NadpYT56Pe+a6W0QnXU7IhsPQCa0cnI2Z07kX9Ifjem0/K2/i/gsXZ01al5PoOuHbiUOzFgMFEsqeJDVKc2Z5vgtjTGmqS5o8xwY6tnNQg7A/qA8yAMVVJf91fGDReiHxMzt+VhtIurCkdYuC9AkW6w7Gk6Eat6LHYp69Ppi187OQFUM7uvwjJLfjYK1VdsCrWtZmX8u8k2JA+yYDnuqLy5GLSRr7yVD+5csJaWlZqa5arSqQog2gX0NSW4TfK1uTy7JBul9OaO+IASqoP2mKcn54SCSCVSF6K8XsojHJRAKybe/Vmc3vWRAmV9sjp1YoqkxVYn2RNK17HT1Uk1Om3YEfLe9wYh3u7aNTXQkPgcWkvn+MThWovZktkJJU+9uhC2ZwUErYenX5uUcdMR9lzanaEZ7No8yPl3mHa3JlWasQJHDsknu0ySGTJ2ti7/Rz5yTxjiCHF1V/LJEQl7Qq5PZBR2vPF2Q2iUP/VxklJ8yehOb4/VnvS7FwKWAzPmeScFsw11+25qZyoT0eoc16hkSx2NxF6IIMCjnhErK3m1yPUf4ZtEZnB2cnYq7W+idKsQ9MKLNuB70PDU1txIBfWot5DyndEMhPm8QZxM6jsy51ok9v/OLf84VRNeD1y8mjXVQmGEZEHH2UceIQsA37HxxVVRumCWnsGgXYucpvd7aw3htbxe2aQ0EZHmJV70au5tBFpDn/lmyZZPrkIqhbXrIGE0+11GAr/ZJViKq7Dx2kkafAjPNjOSgZLkkwsWe2Up6Sn1dGYuePmFO3xg7AjId9Osd9fstpWnpECLjerf5Q19XhA0ImCJGWOZmnhnQyN9Z2FJcrfVtpAghfdOGbCUjJGSpuK2LiVGfX8R6U62pnh6dgctkcuzxcW5rFfzrYoDq651IR2gQbL3GISOOsAn5059DsHTa4HJRHR+qCoakI3iEqakQrL1bgJNwOohWLfvRJUsAZjDK1kUypULfaFUdBxIaHeSk1ymldglh65hI1cpt9Rzw2M085azDEmvdycJGnYu2OCEoWWi1vOgeA3iCO2rBAHIu1qcnd7tGpNA1pDVwWqlNx+HiJCd05DAOp2S9Qj/910yPbjmUKXGXM7kH8iwOctXVVy64lUCKrrgSrpyC8K7pX8q1klaEnEHZ/fOxPKQAsx733vvu+/9MBbD6QliZvfAfRjfx2xkL9rKkzG2BbjZg+PSQVmyTJ8tpIbVU+Lb5Cq8HG00UfMUjPu3NVhPrSodi9p6a/4vsJjMFqzLrJzFshODYqocEZQJwTBL8gjI2CJbIgaJm+/Us6YcGgby4yJOoCXVATnUixXOsZgkIyDlFV1uWzYLHMaTYoHF7yMqlSi5bKPkIudKm7q0xdFa+KRHsRYkn9QhhBlZ/TQY6GTN6cjRl0cb17OBxGZDFQkhWJN7kl0u7EoZBsVynuTZ4/IcpS2UXMjHZWFqNTZpa4w7oFVOXYWIo0W6lkKJoBWSE09SrMnhPWF+lXZvS8e3nCsSUnA3UcJInJ0JYKsXca1Ai6mx7RYXp2dsnWYnoANP/7ZqZ/tz0b07AZCtYubpi8zjOgIxTmfFlLSP+JWIx5aqf2WYDo639BYm1PYYSxHf4Q2AbXe9lUn3yDsMXcQdmdMafEoWhphIuxIsHZ8ay+caj6PRq9NE6Xv37qmTLqXsLvLUbaxpmrCJ/B758i3lLk4E1xYz9qz7VWtnds4kWo5lY4mMm2yL6sKNzuPTq6szm/voINvLubFGLREdxanhhJCJqyeAZPDYUZwrZGY/Acwxx/AJNpqmcHJyZ0uGUkWY4neTLBdVq95BsNK5c++eqvelzOuenGl7znLIqaMyxoRfRnFlGRt1Ntk/QhvQUp6Ay8hBI/Cl3MD51QlFKlsHezMbLZpJGrjqEHtZqd7UJMYPEGsWOEysQZIasUJqe1+yuMo1mm/qXiVQ6qiiLkac4kyOyaO6vK9C9UhCVawTxiePlSr+n3SLK0nF+lh5wlhTjzAVe4ZuSUB3dXJyYqyuGCjyfZzGIrEE7lfOKiZL78emF7GO6Kb1nJFpwsEHTxfIDrmSsN04szanA4erfQXmYnZrvcuE+ylc1wX0Ze/aTSl3qeRLtjmCxpOFO9vrphvx6lKQDuvPnYTllGOqqsibgyLFcrLxkhfztN7AkNxni/2E9Ev8xyviCDWK0jExbpJ8D652KB5V21KmkLh3uXM1WG2Pytoa+Tm8dlQASmqoFnTPzcc/SrwfnJzs0iIHjONQ/6mgKIpcMOb0+7kpLUVEKV0loI/+2QJ3cR5dwijbHAuA1TMcguKLRPakcz3M/WBCQjVnAD9eo19O/yrvqMAfqnrVz5gKRc9Y7FjhU8EEW6AUgyXMwSbAG5N15q7MUv1TCKCKyoqaS2boFFSbIYLHEooQ+f402LlIiovdQc6eWza5RB0X+VEy6PRYNpnl1CpVGqUjwsa9Vbm1HRIHz+CJPua5kanjxsATs85zlIFp7CflrEwdztM7kdzFJFPEju5MvE7uIQ79S2WlPoVGZDpw6zOndXQjbhlzD8EZQXTjdkWArG36Lt+cSBGBqy1VAJOjsVrFkXFhPRz7C+VuRcO7Wd5dwqE2FbsES6aaqArjC4pJItffulbqqs2/zzcymgCjBP/iQPCNM4VsWTalJEencSGB6DKDfBYZZQ6qU8dGaYM4160AlNSTqz6YGhrSLwEuhUh0ziNEL31KdVOPYV+y1yIol+8wCiECW8kENot0xoivYs25oN6avCU3UrMrZR5echKiqUAxzVk/RZ+pacxlzdzwduY2e3SyvyDAn7BjBIyauge3jJ8Y90RwWXg3aW1YWJtsPkxL2w44vlRLzHirUjzxEvRfJHlr+/DAREle9kwZbFw4ftVqRVo5t8YLYskiO+4QdEqqNAp5p9a49CMdp1hTcbG5hNLmfX7UllreR2Ik9TwsBNvLb9XQtdr0/1IQktRLSiiwGWoV2xvfBjlcrvaFUkn0SuJtZjmFwq6wDGiSU8YEQ4i3bZb0BSbqIxGr+OyhJ5nERLIhMSYyWQbLw1B+T2atDwYGN12RsEA2xkzvbuUeIIXefPHUUhZbsyMezrFWyWdziIDY3q+kTmqCQqIZjCPS+ThOPF5cJAsytXUmURKJ+VqO9rCpklMfKbDewXX89VxWuLrk8IMmvNurqtovJSPQZqi0rMWZtJ0tkCOlJV0hyImlbIjlOfXiUE9hsxjJtlDCOT7yqwUHltr/xRFdS/BOWD6g0k4PYnOLreMIAAMSW8s2QYI40jp5wUTStqjtEjcs6unmQwUS6YnG7nKtHNfhkXDc1wWLjXa+Vfl7wRFn1QcXby7uuVe3yPdaaFK3N16ZRE3Lfjouzi/vCLXc2rx6VB5hDca4/42E9Kd6FOtokzTYk/+ogFSDE40ZtmMZWzLh9SQw4m4256Srkxx8JXF5enl5QjW3SwodTdkZW9W06TysxptdNqZiU2fWOaFLkRS5+sqop1PVdCmcD8lx2g72llC5wNKFmvGKfjn/DhB/X+ICU8rRozXK+uxyUT2VyKKzSN8AdvbMOvDgpawTfqsMrIrZ+eWl3GSplw43o/RtEqVaPUbWng/VHMgSuoAcd+gZx36AXDLTbbIHj1rfESpD584MbZZ8Gl6n/Zg8ylXGQF5fVsPCjs+iWEmcSycUFZAE5TxsY/a5VY7nVCVdO4m4xeOukw5VJ/KSAeSZ3EjWMM7EE8MRFdRuLTZ0nLSDSCax/m9lXKbMBhhrRe40ZxzgYkoV//sPX8RYhipgTVxWVHKBcCl/crCrVj35e9sKvaopebokuIFDOti4TDthnExrwTFx9fBGSTFgMIA/wfwz1AurnbqjN1mSElI3Yk6sVTXJu4TXK+VYLFKM2JSybNNplDgPJHKF0E1yS+At79X420ZsmBlEkvSU7Xe70grH67PubmFelfHsowTzQdLcsPNS6IVWtZ01++Xtna0Hm08kFgOLIXYzpR7iEWYJHkLHITZQxGCrutBHV4MWtFiAIJEjdXIuarmLgchoiMlQis/Oa6tsYhjb4dwjpJOJmw/dFDKh42K/ORXkt4qXJzbbUs0He2IVgjClSMasoF7ovKTF7NScLbsk9NWe3C/LXGWhpVEak4mq8d2iE7XFKAHbOD55pqrhGupC3R/ybvy/URxuumuyVSunCFoieq5m9gebvIBwyW9sVaOVBgkCD5hC0t+TsQXU8MYEPjbexkssTo4+3xyfMLZQwEwe7nGw7kYkfuKALR30o1Y6dzgpUs96NWYzTr0EvsYpsbsqPYscXc/FxUVkKsm0PWaOzzvtBDoiRoo1ajxK/0nBW53aoSxyeQWjxDQuadUNJjEvK5WPu32X4Find84uFhcRlVE2d/ghTXQOSgrX6+laQhSwmHIDiHpP2Ilo3Du23YqxuCaTKFmiwvi5z3iQbbjitVYsXbV3uS3kCgFnaYJBh1PpB5UuDPciKr5xHfR3v6igUctCPtt1IHhiigyi3XadmEHsDRxyiLtFMG+P0pLizEZuE2sLWar9XZnl2atKGxnvjpk7sGKIsFVZSKgYtlBeMJDGYZcZwZqDaY1NZuw6YcmypHWxrgxeZvV3buI2O7cOPOOXnMmShJLq0HGBKJZj4TKpYMSTK5Mk7TDlllLbz6gqMZH6QjtX8m5KKZ9dSwkLCE8KEApHWfit2RloUKokXVqdC+rFVCxpm+xM2u+MMK8iMENgtTau1nQdtq6bIskW6ozYlHJuwFg9afZGCnR+eg+D7Hwzzm7XTSnbhsgGUMfo10fxd/vdUMHbKxQ94U6Nt3UfOTghn0SwC3iGmdFFA2mvxe0yaZPTD5Em5CT8TG2laBIsh/gRmG29aAWgppZLTiD9Gw7RyvoUnaiZ64zFpZPCrf6kBG0MR5bMAmnxFB0CiUKUSRa26vcuWu1p2MTGtI6XPkMAZxNuyxHN9LDrKa5zS18vYrJWVgxqepapEAHYPKMejixu/MJBsIcB37NIMrXoQKEop0vyVF6Pk8r5rQ+SCNZvABeIjaT2QwHgN6LUcSBboM5ys1HtRr0ju/2VlujO1lliNCtPYteXWwVpHOnJRr5caNbcJCMTq0jAxBBLVaY3k1jgGMooa28rPttCEgLv7Tr3dcgJN0a1Lt1wxWwnGTkdbIu4nekoUhOSGsxY7qj6RroJNzzSllIJGwCK2feq30soI6IWo04iFz4qGQQt5z19zG6NCQYHWxZcp10xpK6FWm5TK4TFzuKPiZzsTJp6qEVwp5tMWl7grHTOE/DIsnyiHL0GRrEGwd1Bpjjapwd9znW8pATJ0YEgYqytlkVS7rRFJSQpjWc4DfFWYWQuthbDWSYI3zi7DtO5qWYMbOyUGVADKX91+qR9dSPFDwK0OADORS7ILI+pObk3JpZHLb0EgYj5dGQ1drLAjklNTnd+emeRFzmFImpi8bLWXXEjmG6TxQl5Ky9uw0+JB2R9srFz/fXe1YmoJHNVb9LWjVx4rFo23MJMkDyxkzuVw+vKiea15HPKnfccjKOZfMkcUChlPskiELF4pwSgT4bliTT0xPTcAk9JiqlOiiKVfedgHxiLMg2dCCQubfX10E8bskWZejZHTAGFyFCAYuf4yYJgu2y9KTH0vYsqet3w5mJ/ztqbar24pQKO8T4sQTbLmNhpRCEe0twKv1elHOfRZqDzpnl8oMwyxRm5jVN5S4pAJJeiOBW9xIR80r6iApAlEdq4Nk0oNY9Z1UXKW484YcVMOVssu2QSjEayPSXRHR3lP7OzYuNUpxkZq3B7hOs0VNuNZrlimAMvctlNSG4BjoOAbj84kZWS+rFq2Oky5HKEc9uWpWmWZaxtSiRFiT7CjR1MpSehErlmaDk30JIXa1NarpBCBYBXysWq9lM+KzhvtDxmM8ts9o1ly0oVKFVbLwxE4OS6v0vSqJnPE9o6EowtExC2pAkScYDC5o4qlVrtYKSlBzoVumLMfveG4WUyWbozZ5u35DWJpFgvUp23YwPhfUjsImkPxc0JPsCDYzNp5AOyjgsFzhMTfCLnOChQicjhkGHuVNW6tiEJmMZ8qVdesH6e6iHvJ8BQCqMkR1+WxF69eGYHE9Gtd6ukSIGnYn7OD1ztHLtIgazu1DpUmVAdxmxGz0nEKZfgok0EcfQepdMr9Im6x6YqgUOmwntmuj6FSZUAoSTixIqsCHkAZWf5VF/TrabmBK9S+08rUe06QSR2rr7RooOl+5vfP5vUXmnyjCVVOXtsp12qEQM/242J6Uqin5SdOUBVuJrmfhkIXySUMre/+qS5gi3BohyPTXJI0SzlF+OAdsdNy8HWNPf9RYV8RGDC9dlR6c5tSvn3L52eaJtCZVPzYnS0j3AnKn0jjKtycXZyegJ7Q9X0+If7YLXqKm5R9kW95Dtg4AqRgzGy9KSYc8mi1np9gLNvJfyXVH90VmMFClFxa7zrXhT9s7tauBtK3BuJEeOapv08ArUK8SfYBXfvnlgejOhI+54NHoaEXpRQIe2Zg3CFy/6Y4oPO2EMTJGRM7T2IrWkXW2HkakfevoQkU5wQcb+gXHYEJV4dN6l9q3hEss3yF40ZO1sHCyC4i81p8UTSaagkjq5p0GTHTYRIxyZiuKGdvNI4iAYyQRi/o0Q8WxnTLs7uXohB2RiDUpdctDzCCHUHlSbjNJp5cYV5nWU9+0NyvfRt43+PnURIjlYm2FS9TsZjiWBwf5wBkPhNiB4/N0vZBsGgsE0himodtllXWHs8gJAligEAmFj/q2TyRzNUNKfWnZM4HC/PWuu2E4ROO2f6yaE0R/dDDD7S3mqzEtw+jk2w30Bs9m6Cqjoap1thB4a5J3Jrf5hEziGfxmzVq2lWkS72vbvI0rY8UrG2JFGREDfELAq9zP2nabZLjvK61fEAZrDL7me8vN2OC951NDkSu6+vDFVa6yDO4zGSUUXuHP98I8ZYe6upKFHDeCF3TmJWIfKkGty6VgR63bXtEd9a1CUplyrcSiT70jBSqWf1RvxhZOFabcPMtCyH54vErOLCt4mhU6RW2ZBkFX1a0xQ/x6Zm1sepDEOhmWOgGftTHBDKqiLuw4cCRl+eU61bKyiXesrs4XV5dqqH0XfzlxxmpfZ1Z4/2HglODsM1h2K27EXS6NeVPEEOMz9HhBUHvcdbsjaMzISCOSrSuLzy8ZagoLHgyo1ocnMGr01BaQaVCJYy6o/ijtHGtDDhUXlExuNzx5wUtJhBX6pQrlZwtJdHnEXV/UAiQKeZgdduBOy6JMlzeuf07pO+tHxU4R9P26mLzK0bxLAf5HiCu1a8mXZu/RZkCufx5+t2ingyAyArW0fgKWp2cDeXF9awgFGNtU+3stemK8vec5ed37eQHHFF51Y2nSlC61YbNYehRCEjU1uUtVS8BYuVOk5vdYzbrgMWbLOY3ZMmO7TbVL9Uq+22jgzfZjJVKLlCAV2NzYg+YnoAQxLll6XOanWk3H5KwBoLctu6LdRM25h416U2dOk/RIrHydFSN6DnGBlzrXBjaLrOTR8gSGyFODnGVpKt9BglGmP1Cp9bvXYlNphG2qLwQ1ApuKctgGC/UdF+V25v5WJcnM9Hq4IANSXilrwd87+V7ds+jrTaRIOZzbZRjD4VTt0EDVzXQBnVd6gU1azQVKIb0NtlRb4cGYzOk8HuOVUSuRlsTBATV8QFSkO678k5nkpF8oPxNM/JPXNT+yOK0r8Rn0OWs7q+ONroQLQbKs5sLuZFIW5BOCyTStTpGNFcz1pnpU6JBIyNPdp8kJg+mWus15FTi+9nAV96ulQR6VAmtSTLLyiDGywVl9jVfTYVU21HC8kWU44YMotFOAZKjMdxyMC8ZfVxNwooatlnx1ZeniMTp8juI4vUEajzomPHuU87r2t9r5OWRrLDUnQZR2ap3aKEEq7OIYhXifqU90UW2vWZ4EaC+MmhsStS2a/i1EKIuSApUu9e8ie3nTOO1q3U2qTipk/tOdxLuVT2JgrkRtG4dUsZ2i3KmUOO/rA252yHopY8SQ6loToRkCVa19TIHp1CRY822DAma0ZVD2ZVIwhvXUrPkfVIsAvVj5JxWuzr5YYKK0H7MYIccfZE5UThq12kla3ddikK9XFKpH/NfKGmgAXMpXuxx1g+19MMwsHlKKIQ0bcMA9RyXW/i2EJvXYpOPvVSpASyT0bRovD2i25MsxKJOjrLksUAIbZdCsQhXG5MgthXJVEiAYCM01V9pL6f1onzAzQnV6HaXyWZj1Tane1ppK/Zwn2E5zwSSNKAvJSXGftsh5PCIhX3+KZyXbonRFHi7N7VouWEWZByZy47CiDpxcn7XORAcrnxFYViEusINEVw7Ja3HslSD+mtoUK1sqKn1sgQpbfefhwDOwMrYlaPdLh5veSPxtMiPJuNDb7x7qNUtTDnQ0kLbDDju6UtgB5d79g/wty52DZtEqE6KfiLdrYtqRvR01U3JxLac0qb17JGph29K3eL8zOOtnJl6UgV1th7d0Mllbxx1t7ked2VdLQKQQnmvO66FbX93kEoXdgnNiFCmuLmIQF4UH6FDMLxVIgLLRRzgvUR8bJzJF8kx9t4PvEuz+Y1OUjA5L52EeJV4jKi9zgnxZ0r7++6NlFeLNAN9g4XhyVmyGyAzTJn1wYB1zfGcy6T2Yswx3MxH44kGWVl73WxfEnHsuRYngOkvC4LHlCbCiYAquWyhBxxrsNb+rlN5OSe2DtBwwTcGefwKkIP/EWr2n48dqto2moJvmSOSK/V4DPiyjjopO325GCiHWaRVSLqjacEhnfU+9ABOX6ozK2aYlKmM1IAxrCSfOJ92kQbdNE2olDTtkUBL7b9JP2Gn15kHuJAY0srAxakkCI7gSsUKeZKezWgCrV/2ShrdJiSDxJ9JjbiCNEjo1Y7W8rqLh9JnbFTWrEk7K7LuMBCxOIs6R52i2Jialsy/kaOpKN9GGKK+aUU8lGRSwfNZ51hkqoaklxW1i/qOJti+5OaHoYmhj3LDhwFnXKXq+UM0xMnXp2YFWKiAmhLgRt5PBk3n945UQhaZhb6G6vUW5i5oA6KIy8ZEsx2SBjItWr2SM/uTYiSSpQCl70g8V3CECdlstiTD2YCQuOkER1LMNJB7GqVW6ZYU3Jd0lVK8akBwxG+rso0K9boNjG7b6Z6crtkmLty5u0AHaXf1qUgtOhG95HU9cBPJraVCw6eJcyuDxUjYDsf5QnlcvNOewlVUhRFaNHvLBYiQY2+gkPSjq7v9DjBwRC2rpeAyYUaRDVVCcQw+r2sgUwz20gbaKnZKwjfuisyi4eY0EiGO5NqJFvSpSrKn55+5k8PnuECS/mKlsSG3TgbmvecZYgOs4EgUR1rQeW4VryPzvxiswgjLaLlqTK1swP8I9IBCIZPmvYuoJfKsdU6P726uorcrq9tPW1Zq35QdUYOUuYY1pTqTC3Gwu3q7rm2m96AkcpC/kgwdcvOvCzFt0Nk+7YUW8ZU51pFOLHOB0CoSpLaWUEz5vTq/HLhiKFz1Re9WE2xsU4KxVrBb77x5o8WFydXoECkbXpNf14nV5OrvgAvWm68sXTMRZP1D69ZbRBBG90kJ6KdcqV3xKiykIl8aznVkUdRipRvAdRhGkg5cDVnhXkEQmy/qByqELybyqUqhONcIczl7Sl/MdsME6ixdQ0lm0hbw6S6lZRSANUI1KTu9eKmay3Ilm+KaVtao6mdl2Fnk/jZvje268iBOu+pKL9yMonVOM3rdtjewuhZpykf7oAxiQy5ILmqAJnmt12xTBVkOs/Yx1r1inOaTnxcTuqNJkuzJH9lsdfYuaa1tq3Ivsp0eDVq6G2q+KqDYr34okbsqtGMe9H3Du3gcGY54WslxOnOpeYl+6TQzzFd0Akp1V3A9ctcZ1Ni+eyze3ck2FRbRphbcnK+VF3zDko/xyQtkqlSqMd9fnmFzpJdYbQNSb495m6CBMSU08kSM88rpO70sC5OTyl2IOhLS8zap6vECafUJ1JVntlhjxz9zkyfpSO3Ed0u8tYlsGioPklA7iMfuXuZ4Nj14vz8lJ619B3iapBB2kh86/TygtJvRDXDIokyL4/Jvmno7Oa5LHXMIKKQq1ue2vlSDsKsgThDSka1Dg+3cFeaPRSu07af2RCnay1ZJxlbehoqrBwiNxqX4h11UuaAJF4B4qN+lASR4/mSWLVy9Z5dk1X7WmY1pUNHBLLiKVR9joysOyA8D7yeUvxIIU0x0a6Kg6RNSkXO+LFbTYgJJ1AiUHYu1HIz240sv2KzmG0fyHpdObNTBf8zZam4stPG4INL7682k8zJapxBZ4SAdeemZjEl2zMBjW7ougpFu1cSiNT8WsdaTRF2Wa4ROYmd8SDiqDT+vO9h9sUeRX9kBUxJrWbqcamhOmROgIau73qrXPazOphU6biJmDRbyhyLMRnrVcZFoDqeQoTcCUpbHlYpEjKJDMSTJFfw0SyRB6ayv4vAPrWhlh0i5nDRZD1ByTc+RkfcxNpIzRv25FKSzLsM5ygJaA6J4Xerw3vNhUUQMsWsiDTzkHgkBVVzrDzitK19bOHE1hdKdyhOCtY1pZxQIL+92BhxYmWVYX505SLS0SNqUFr3S0+enbPslndbYNDmEVB9l5X91Z3ZoRqs/Dqi+DjCVm7oWOvF2yKTkk4g9IouMckpoEEvWM1BQO89lVTNfB5TI/eilhjuJNGExd07rPtd5PjZrnOtQ8yJRi5Sde7c+lDSCB3QNalSwlXmtzq3Ig3JDKOpZCEspEYZWz62pHm3M7KhW896QvH7urz4nIiZehO+4wlccqyTGSkObePIL+yTHJMgXkif/IqrcYUSM6XQJHC6XGoJXdttg7njZpySin94ndj17HSh6kVlV2JwicLUCcM1JBhK4uVHrKQzXGd6iol83dm8lcblLRdryU9GxIM0P9FLLdu9uOzbmWUdhXjulEwjs52D4UKIYzCvcbcgwmmrnViKQpwMW3U1lmuUoWlrC6fe/Kq8EpwfG7FWUWR26n4hnfulIH80TaWAG6sJLeZCbO4nxtA61E8d39nEdFfdhz0qVI+l5wUXi9QA6AaQkh0MXlHpZYoB1I9nJ253ppB/pMrSL+6rs4gehKkiS1tD7hF5gR8THyeZjwMqmQdXJvCzW9yLOYN5Oa0QPEbV74mQjS70hEGQEW790XrevT1CI1zXTtikLvPGdA6ZAY14cg6SoWXnseCN45Ud50B1y4qiR6CPgQ8JGSdrNUnihNK22MoBQGkNOu+x1dx362lTs98d1hK0UjAQ2dIFv0ejEAm3FiYuaj3dZDLVUo26xIrF7WdU2No9kUgR+0+y83FX1zEf+slxuExHOLTi80FSPklJithuRnWsOolx8ijiN7YKxagZXNyVYF4lN3GAgrdzWudtpQqkRNbkuCSjeUdFsb3rzII0KD2pvRHnMmitfKsAuhc69eOSkj3xsk/8YwjWGQxIxRutcvIhnQ/7qjzMJtTtkMiByMoCLYTXeijRLFWf9Pzi3KgFdbiEpfj7l9jFLlW9IYCExqJuj4St4h1uhxkRmnQLW3jX/bQ0faG6rtQoQXyonwTUU8BDi4f0KpP8WZzr+0qaAitS7max76Vjyz6WV7a2BX5Rw5lx11T/S6M4liEyHZlrVzHdbywWM2h/iF0vjg3a/1KGzrVgktSPswrF/CjKLYnjUbduSihoqVqr7Ss1altsMDZ0l+uF9fL6pFJjyZ0dB2s/GcQFSrQlD2rR4ehl5zRKqUY2gMhILZEUXNrOrRyT326fTKNli5SpCOzQFmvfZNiEP4w9YldIBbY6JeMN8XhjkRj7oZI7J4gWr3K9qRRTrhCPhW6bOPvFjN/Qgt/t4qA+jyRqN+GZRuKnRHmdjDXO7iWlA80AJksduwrwvaFEsgAAbiTgTWyQmwWbjDL4Fq0nTHWeqM1ks2hKHDXFhzq9nUUgEE7mmlX8oB/thk5mLuxWOvyj1/nRXOrRWJ1lUs63cvffv2EgkZVZqCgCuiIAiGj8bkyWPcWnxmbhjXxz12vLjNukqqttiCbBU/yX4jaaDjHdmFurmTXmi1jbCtUm4zcb4VG21CLvLbZ4U69Ih1px5QjHOJRbsL9xj5LtRedt1jqGPT23Vm8llilfZZuI0o4TdmSc/ySv7c55165U8gi9Un20paYWFWYZKcrnytmAMqQ/Pf8Xp/RHlT71ixt1JIl1lzHRd0N6JzOBH2N5IDM8BZl/H5OV561lVeKex4O94lmtBfmSboE0ZxKs1tT3aRkb29rCXKV9qekFRSTElhKHgFED46FaG99pj7D8RrNha/TxCFKbA1yl2aPXY+abo6aVzAWoEjliifilie9VQlujalJnNgqIOM6Fo0YW3L0alVNj3OAyWSyBgF4ilhIzOl/YR1OZbS7AVFtGUrNOclfujCwurkbbYyT75sa+1cntS+wNnpwipZOTXSNSeSkEfyJxNrScTYibdtRJbWuaXH8KY+FLA1yokHWLO+cntH9GO6ITVc5cjop4LWZ9FrvzYMXYUeyreJwERISg7dI02nq7uLg4lRuV9N27684EYxGCXaA1lqhizwbTsgTpYmOHQb7itkzJZjYb1HZxN7Wk69UTlzRXDGEAcLYiJq0+Uvah7WKoRpVbiiNa7jlfUyWjp0ywCDuvWMzN9u10IiwmkRXeAOGfzr7BEmGZikobzlIRcGEZxdtDH0kZ8DUTvJ+Omz7GKwW0lm9b1UB4h9lOcHRrhjdsdRKzSpLk5axNKIxBVpnZODqtvRWpHpJbAeU5NLiT7Kc2thuR9zupAkGFUPySJLyMK1B9wQrb1XKB0QjRGVM4V35GlT1bqwmnYIkGUGXzuWGcdpX09fZd7XKfrEvVxCq3knvZunKgL5hc5lkpqbcXQwM8oEmluUa2Hnrmm9oyXs6wrMOJYP2xsw19ZfLA6T3gbOAQCOBqK4OzxwtCN0wzGE3da83prr6RRPeIiS3tn2XlDnKycitTLyZPjsJdpd0a2uJERj00RyFAI+6n0hU7LbXgHeWS1rGINJw8T60ZV8Bq1zytnuL4j1NPuEd1l/AtbyprrCf5wcIOMEezSZTkzmL3tnHrp2JxV/otCPOP2sR2MlnLV5mJTbFX4/0g2pf0qnIsQ3rforNu0H57d3i2ENnjeD5b9E8tzu5Jn60pFbJHRKsbGhL8eZegv7JZoijcqL2YTAlEu4jHsllsp3Ywsnc26xP3OjbBquPNK2RVbJ0k3NZZ7AJiEjapH9+OOymZskld3ou7pfJu9XOL8m8QOrYA2NrSAWr+d4uLy1OqbPcWatqQRQ0jzcKt0uEdbRWEFSMmUvmXohtgZD5Bnto+OCWfUWADo25un0h7MePjoEdkpauPJKz+1z063/RcWz4aroSOB+tPqVwFD4+v+PuXzl1znsmArW6Yaq8yVUqGDqRpe8YVnp9d6b/S7ymym5vEBIxNTm2QK6xqMIUxzX1P8HR6cvcqnmYEFzq1y5Q2Asmyq4GVFqtCoognl7EznfPIrggsVQLqE4+a2I25ZGXQ7caaLTQqD1WaCu7/1fqj2eM2EnQO49Or89jxsO0qpnqKlROBB7+YWD8JE0LUVhp3M8zOe4kX7N5NRhvsRi4SJq4mkECkOBs+JdK++440qjZLrnEuv6IlE39OSjI/bbG8tH0sy2p8oqKSNCJlbpqMRmj00zXk8tJT76k5Li4oIseeUkRmGvnbnUupW1ZyNBJMpsrnbdvW8YDOBE6J4OXW1cX8L9sKbXwaDxXhijqn9jZBonK3M+9JjsAJfiKwJG0RTtmkiSrXNfJIa2FpBt3VdjVa8xxFldQRotqSkNIJpnBgCzrYXsVHzEo7ibBiS0h6MtfQPoXalewH6wrBroEAA9hxmWDVNFpPL++emILMFi0NLOUIPsMaa9z0t8QXe6z4nFP4htRKasvcgx3WFrPzT67CfqeWviYcpao4JlBPWciUT8+SZmRvp63Kdd25KCapBecQcQqjerUZ7RcstwQl53YpR+R4yWocgcvnUlSOaAV/j3Gx7eoUXkTCJBtmy5hi08lGv+m6RMe+vGPrKG1RtkJAe2uNWcVuUUSK31fICaPdfFwc4+mgnSACyyK7UaCKHmACmA5IUEofW/bQ4pMP08D1YxNI3Ye+pWnzPUrkQymQttIauGG69RnuMrjwyP+cnZzc4ugF8ItA+2hJ4Lw0o2ifQbACqDrMVUKWv52Xi06gtyaPQEttBSx9GhFIrgh1XaUj95kFWOoFduCqXPep9xfLW0e2VCmwihL0MAL3pYDExUJCn3gCVwgDATZNoFkm+bkiz/uw3XiWgAFLpqvoxJHgDH2cNJWq2XmJw1pCsNYCq8c2GPcGj3hCGykdyinOisO6Yykwz7P2kPX2HPHJ0qv7z0VbATHXEWBgR065v0VycTSJ5gBOrAAmEHvIiGBMseJmle+S6dExlOAUgS3UNRC2g7A3lHPGRBoricKpWUuXpDdA0QAhl7fXdmuj6KlUPAKzRRJjvxXu0GtNCp9kjaW8hQav640lzGIRHTiTxaYzHc3+BpkuPtZ+eo6TBT9wgryNhWlDUbfqpbl0cEn3OlO7llzMWt9IxKovaOR5JWh1u1LlKm5huzlKPDSy8F261OoaSNGmGVJZAf2DDaWQXTnbtI2uy6yq/fIWbD8LyOYJzzvVavOWQ9LbonCk0jLs0coontj/gJ8QNZbq7cQVFcdkjNYQPV1eSadQiMyF+YHeyZnmFJPjVy5xBk/WUR8SuFH6JcR7vPWuV1Mxq+5HminG6cFAP83P81PKMH0pMsi0G5ML9Nk9dTxpkLU81qHr5TAuEyQZ7baRC8QBf7pQ3mumkxtPK20GPWasfMMp4KeeOnhD+xXYHjrta9FINnISI/JnZy6Owyrh+G637jSb4mA9P7tDlJfHXqr03qFxXqXW2ohI2HlEavtKJ7cs7Zb23m4yFdq7+8KybqrNlCG6wr6U5+imm5bfSzW5byvlPlcX2kFRfKkzVYQhOrIHnJ9L0N62bbRV0NBNneYa95CYIfYgPCaJmoULd2xs6whepiUUmdF1Ckh8YuIsbrASzwlyLqRSDVYWXZO7YHjZLGhE5htvT0k/Fj3l+J2DMXoqNxaU6uqskjaQSviIIBOi57mPhHi6jj+W3bgoXZeL6RWHF8CdTZfdd/tERD9IFqqNuJFf5TLWlKyK80xzPecid9OtqMaPWbk9dFZRq3GfiHzgghAnKZNKM0/Zx41Yr0Mmm1YhYkHIxLFDQ4je7r4SgF0UEJw7suWS/A0JFNgmqC0xRTfSeE4yPkQzTkYm9SPUmfKi5p/HmSktdFmvRmY/GW2lkMb25QNASe8lXcK2sUOMi253i07oy+P2OsM0nOQQ2P1YzeZTsXX7HNxS+s5vpNm320h1H37PVPli5AoxYwcW+S7XJki7Egc0bbX5rHCMIgomiVLg5PnG8bpWghEXc911yclwf1vJkLRIwvJO3ohmp8UEL4n3W9htdbGly36Ecd+v7QHVJ+bH0FE7luvmh2iuFP8LUz0rgMJc7WhZAXUYTI2wnrnkDMsCW2PRUVYzvT2ZYL/187deWficR5a6WdwRhSvyodwIWBlNSmlwlgftkW9QpyZx1IHJYgaAI12yi+RvBivd0x1PXRoBWndZoe13m6m1s4+LUzUiVeKayq5KtezNdiCoSK1lCCoGw+nVvbPFJbF7EpQxCKyLL9xm7CFnd2UZVLBy40Vjng7APhb8EZMuXZQue6aRcMigm8P5647jk8SO4jHK7I4HxrkOjRANwrZI3PiUIeOXSRrHsBxD1plULDA/lOUJlkyJF94XTwpbzaznj+4wR+MSBqqVw/jCp6aOV37IvG2jxqHjGz1OseX8RmWOrRJp3ZlFY5/kQlB+iOwRaFtdf6nOQiyC5axkIzKd1VdyrG7HiKfVEIuAptrt4tnu2I1lElXSYmk5pLMVdpYOquIXU+tT5R7mQCs0VAS3/ROPoEaIH5zjHRiInATNGSUqVzSlHSYbisr27SALspZm/nGxrMRCFwrHHoiCrxMqmzel+XFHveq9yH7ITy/BZRyqHi/UlaS4R+esxgnEyZFBGiJQ6aUFJohWxJ815x7rdBAJmDJDbUhdpmn61N5M8zgH6HScnkTyHTmoQGeCV1Q6n+3rsFegdr9OQnj825PLk9s+4a2JTiH+YDkobbp3z7O3WOTj3roJaz3LYRJp2pJuUsKI3fo6yzscjtmP1PqzjInqdwIRD/b3LAz/VC3R3R8FRLi92xm6UrWL68bjrZzhKBKjt46o9LWSoHVPClPWcv0SpLB1jSW2k/Km3IIryRUMDDIoFAyTGp+OFnFb8EYYKETdyE4MyLqazdY+A/SYiRl9cwPp6OQCycZIDuIEkE7cldQO0/w7dlvJiJZ2R6enGEtyKQY2ubaYskmSMF6rUdjYUS3h93RSEWyEB0+SE3xlBF1khCSJUpLwhL7mmRy1Y4PSUV/QznYRCCCVUcauSY4xG/wpVOG0qRbxfDqrLjfKyk+vLq7i6Yyj6xcZogUN/QuDN+k9qflhvLL9+Kx0PMrjzRU3QYjheSjwkyHNbpHl/tBEC9BRshxFeo1FpGilxDqDDmVJWHbd1ZJUN8o2syhtpqnOORcpa7YqJZYvH2OrttpU3t55ieLZy0+aaI0vZHtty4RIsOoUyHQ4UEhD5Z5xu2ptu/KnVG6c2NGvkiqdsqnksA6jUmWM0kZ8hn6lXaZKXKV2qTNV1fXeDeEkUrZs2QiS6a6lwdhO1plgYq1KMqV4JkSfnJ9S/UnFEomQoPcDzLEHbq8tp08sl/K+MQOyuKV6HI+r9W4cUVWX8HTC96IgTVJZoGJZtjqmq6Eb0VGq8WRXZtGrFyC/v2VvVH8uEDvdBXfejqAqL8/I0A/SxxYBdGX4QyE/BnDjJUgoJVvwGPqY4MSxMrcbtlUCNwFb6Bd375zE3clIC5AKjGqxLXNxkuSk68cX336NbnXlMGI71d4iyrUVbdE66WKiDCKD1eBusy3XSM9mvD0I0djaC11DMfcUf2SbnpVzUtuOtr0XUzqCzrbUUZjYdY6PtZPQUb8fKwE/objXvfPoDVI2k7wzUv9/RusUqyXwgcKllH1kKDq7VYuuJBhUjjdwWeIE2lqmEpsg6Z6wfHBrsQodWbWLoGCWOitVcTicx7uJeCH2xGXXSdmBGnUnTew1Xow61grBzeaen2Rwhqaa3eJi1fRTvA9b2EiVfAMMMaKavcACNyVVezu1OmbqVSoF3gKC1FilyAMLTrxNVzfzAToDHvAKBd4f6wAkwUoNYAKzbbdEmGFTpfmBnBHWfWCVGySLI4qUXU9tw/rEB4oTN6mAN7LSVIS7XKl8t7g4IamjktFJQxBRDWbxXTLhOKvUDEYaX5ylalD9MM4JRQrXDiBTZu3u/I3pw0ICXZ7gzkKMpupXVVEaurdIWHkRVdgg2MzyJAL5RBjVnsxjskywiZfO7125FLFXutOuhAGpivubEWCucDrDH+i82TFxVc+aZMnxFpR7xGXElDrDRQsdnzRFExNCdR419Ai7BepZae84P78Xp3UmC+eIpzjD5UcYj2oaM2WtlexY0L+KNb4yfXdSRbGYnVsQ2lpWJn6n+nWj0m/rE7ca7ICuelqeIOIkDq+89atZpKEV2SmCh52MokXxdd/E2AiJY6kdeBNHc2ROlL3suaN0etRX9Lk8ErfV6G1RTl/7CEHiiiPFqktiziFTk4IaCy+F4PMwu34lth5lhPPF9TWnOwDlmM33FZ/bak4TLVmVDhtEctSa5vv06NMpFIng2PW3bMW6S145GGQRD9wVh0y4nmawS6ycjyPWiRUAd0hOdjprBgSzJZ44SKff0hrZ0q1b+ozG8tq8lZDDabTx+YjkSTYs24tKmSTY62o5JUcLbtqa5FZhRlLnSOkBjvewmTFlnNWDq6gr9CLjYIXVt7eP9kBzqr+x6L9BmS5BevGdU6yH6BJTI8Iue8mPw3ZxJ7bp9UahiVsYcY7ybGrl/etePAgxBg+kF9uuFb9Odntks4vLSwUq67Zi6Z8iYJMdIuxexJ5GFhhZETSTXcwYrUC88A4pOVpOdWoGNIo+I/Mijoxpgu/45ZUMgZ2IN92tGG93v0q2wXrMBzCJWSYXETmHEAKyuSCkIE2BcxWQd5JldjWYjs+tGQAQ3WyCk5Z201vvejtTJp/wfPbEa+MMETMJ64tslLZxWSfJCVGMHFp3cqWKf3j747fCOizbHU6dG5cmDvGAqQ4LuzkkU6FJ0lkQUfKNMMraikXFSEZFG5UotlB31tLSJAyXmmydSY4nc8Ho3c8Zmr/uHCZ1fcpXMZWUnzZYP1Mis95w7ikthjaBiPsbxXqxN1i+cV24eBih3yjh33uXqKJHAkE8pX9ynUzQ2Er6kM3O23rknkvjeOXrFc/o2nLvRGyxNpXeaPeRsyMT9HDESnONsKXmp8gchJ5v/uz3DyQq42JLGckfCX3Eq4mek1EbsxEK3NDJIcGy7+ypmk9z93eV5e6jeo+R0GiBmMBe8dpIjTor1Ns6zuz6RIpD3oc6cl+lAz/L+s1k8FXclbaE6xzVLVE36QzrOGOSNlmRVH/NEcpQEkwKAlvz6PvqfkRSVydsWWfEKZMFaiAWpW4ooPHBYP2Y08NSdhkcpzTKbKxQ7e0qGnErW0VEujo8JeefWZFgRxO/BuYqSLLebbI2uNVIRcMciuUgguOQPDGmtlfDeIYDrvVw9wRCipMQsZV6Ck6AoOa6tJnf3FRJScOmUZMgI4s6ty+LCnzl7EVfxk7K+0Sao6TiSdWSA4abjkCSa8IYyJr0Eua8yXLWEDFIxATVSpt58kqk7JbJzY8ACOWlvRDTR9NgExWgWQ4zmDqSB7cdEjw4mXDlUmZsLS7H1pEZHCObjsZnpCE31CGwhUa7FJu4SYXzTAlwteoEFgV/PjlNG10gvEEF+WyhXXjBDcUBTmUzolNoUpXk5T3zyDxma5Ntt7v2DaTQ2hARkhu8E2SeIYcC7Zf9E45wvAIZPB2AGUW0N1o4Dhp33E8e8bjNAG9uVFzod3RGwJBenJ1hM3FkoyQry2S8NRbKuUGnTMyLiCeGpDD5kY/89itEqwhrYdpZ+liXKLeUpOieJrMtwh93wNQ2jJwuZu2MO4tnt7UxO1WxTVV3SU+vPhztRCS09kBrC7i8cu4PGSKLhLWy65tzSAGn5KbFe3uqVvuQ/lMcBYLca+8SSmqlBPEidsAV+rsqNXc24LIoxCyUOE5raZH1YpGIryLMZRyZ5wvDwPrGaZIApjMcPMV745TbtzgeYkmIFtcnzSHX/cRqyw3V6kvhfrsVwjAJBA3QOFa9Jpuo2RFKX0YEegYTcp00CRE3l2WlwLYcKjs7OQ+b2dCBGWo7KESpzu+emnHJA+omEfDEAKlY7K2cy3X8zBg6VZUyG2AnNEurl3Mpigc+0guMndAkzJI3xpHy9o1bqBQeFQ/b87hMlJzk380D04k4HBvxgq0bDRpHXKSdd/k6ztR75xH0VNbR2kFFSubrq6mmB2wPxlLEc5hj60y7V1xR8k6bUuYMO0HTKensjFVh2+W+Qcz3qSkrtKFHQJlL/F+eVSr0jPQsRxUrJBBONlJKEcCaaqmFzYaDDFJE0CjXkD1UrpJI2kmWcmtgDlPt7j0HIsL6OlwP5eL84iLWOs1DgWGT+LJPoeHowwMFsuQwTfBDKzb+5QFVp34TZwWUCsl2zifKOtXqllW8COpjClEWtvB0WbY2MZmmzcXZqZjpLtW1mAGnaEBaXl51gBkiSoqbrNrR0ofFZIkWnJ/SJtodp5tbTQ3iUa2TwqVdq7yQmapfDP7ImZqwfjf5jSUlVAca5OLuVZ829rFzgBAHaStqZVvt1EKBHaXbvvbm3BIfEReo80Stj61HMNTdQrmoNAyGowBKVbJGi5zrF8xDcu61cl5okytZR06pTzTtRmPUZsm1XUzDUr7TMvuuE2gjeWptutoQ8VzI1VbKq7G1y3xw7QSww6qChrewkjLK7vrGpwKxJlhXi1GjjDnzQDpsjGWsK9VdPaDd5HO10Gle0bfJsMBCdT22kW3Vb2NR2XqL3Vi2XnGRU2wWpkub2Tcg8JyhoSJNhqWUp7suJao7WgB3zxaE6KnXtfZcGioRf2lLlSxdCthMijgISdtaNoVqxhi5onhrjVveSKCXChBHSLZY4jy7T9UrtxtzGdHLZtEYJyY1tCrUisB+xP492S7LGKH4vq3kRvvlZAgPsq8RpapDsZkItbSPTm0KOufwnvpWRB8dQNPjjJZITLqIW5Igr/Q9pEtWI0Mtr6ik+lqoxzIoqN/dnpOrevb4u058cKQXRP3XMRA5p1eFcC3dAJoWrQxkmPqIgEboBJwSdvwolTOKWQxgYkDoZNoJv85nw1whxpvBkxQtNkpwqMHxxi60rS+NS+7tMqTE/RIYxppgqU2dJ2XUVQppq1vD0/EmrYudkTO99Ju6fFL3h3x2isgvXvdqUvAoVxudi/u4Ioyh+CDmAwktPtJLoBdds1CJQt65sbOLbdLfzgWJ/WNGqL3l/Jx+RSt7ZRBvpCPxgCxYKmzoPUm85yml29FeUwMi3u0larUrrJySSVE8znqlwNqUbsMCd9nu6PSrnkvfg7KRsTuKTmhO8Uy1pVZWSx7XSmhy+cFuZKQeTLMShHlm3GElo6+YagiLzXNN4PGsvc5ElhMqkTsW9mE3WWSOA2br+I/vz6ANQ6guM+dXm2NtcFvvyr5sC/Seskov9BD7TSGlG/HcZQtrZ/JZ91hhaTyu3pRqxDpgz3PmFYB6x82xNyBfifiYNvt/J37+3fj5SPz8e/Hz78fPfxA//2H8/Efx8x/Hz38SP/9p/Pxn8fOfx89/ET//Zfz8V/HzX8fPfxM//238/Hfx89/Hz/8QP/9j/PxP8fM/x8//Ej//a/z8b/Hzv8fP/xE//2f8/F/Qkr7J8C2Glxi+zfAdhkcMWHj//fcYvs/wNwx/y/B3DC8z/IjhJwyvMfyU4WcMP2f4BcMvGX7N8BvYunzyP7zCwO/9A//h//4sA9/2/3yc4S9j+H//gtD6Mwz819/q/36O4fMMX2bg6n/Lhf+Wi/wt1/dbru+3XN9vf8jwKgPX99s3GPi2332U4WmGBwwPGV5geJGBK/jdJxg+xcAV/I4r+B1X8Duu4Hdc/e/45N/9mIH7+N3rcphg4H5/py/ifv/xeQau9B95zv/I5f4jz/lNPuBNPuBNru9Nnt+bPL83+ag3eX5v8nlv8nlv/lpywjH8nqv/PVf/ey78988wPMvwHMPHGPjK33NHb/F63uI73uI73uLj3+Jy3+JD3+Lz3uaj3uaj3uaj3uaj3uaj3uaj3uaj3uaj3ubhvP1JBp7L2zyNt3kab3+B4UsMvJS3/4rhKzH8f5+O4R3u/B3u/B3u/B3u/B1m2DtMqXd4W+/wtt7hbb3Dg32HK32Hp/EOl/sOT+MdnsY7v2LgQbzDhf8TD+KfeIP/xIX/E//hXd7Wu7ytd7m+d5lI7zJf3uUi3/0iA1f6Llf6Llf6Llf67lcZvsbwdYZvMPw1A1f/Llf/Llf/Llf/Llf/LrP4XWbsu0y9d7mZd5l/7zFz3vumHIIZ9O+4y/e4y/d+wMDCeY9bfY8p8B6v5z1u+j1u+j1u+j3e0Xvc+XtM2/e4/T9wv3/gbf2Bm/4Dr+wPvJ4/8Hr+wO/9gWfwz7y8f+aC/pln+s/87T/zH/6Fv/0Xnsu/fvtZjc9pfEHjpzV+XuMXNH5R419p/KrGb2j8psaXNH5b43c0PtL4XY3f0/g3Gv9O4w80vqzxhxpf0fiqxtc0/lTjzzS+rvENjb/WyEv/1+98VOPHNerbv6Nvf/RAo+7rke7r0cc06u4e6e4e/aVG3eMj3eMj3eMj3eOjr2jUnT7SnT7SnT7SnT7Sdz3yd+lOH+lOH+lOH+lOH+lOH+lOH+lOH+lOH+lOH+lOH+keH+keH+keH+keH+keH+kev6t7/K6u/2Vd7cu6wpd1VS/rSl7W9778fY369pf1jS/rG1/WN76sb3z5xxr1hF/Wt7ysb/nh0xr1LT9kHv3rq/rMV/W3r+o3f6rv/enPNf5CI4vwX3+mK/yZnurr+pzX9Tmv62pf11N9/csav65RT/L1b2nU83xdT/J1PcPXdf2v67m9rmt+Q5//S73lX7Ln/Ouv9H5/9YzGz2rU2/zV5zTqbf7qSxr/WqO+61f6rl/xvv74Ua7njw8/o/GzGv9C419q/JzGz2v8osYvafRf/ZXGr2j8qsavafxrjd/U+C2NfOMfn/moxgcaH2p8VuNzGj+m8QWNL2r8uMZPaPyUxk9r1NU+o6t9Rlf7rL7rWX3Xs9/RqLt79rsav6/xbzT+QOPLGn+o8VWNP9b4E43Mij8+9z2Nf6tRv/nczzS+rpGj4o8/+TuN+rSfvKJRf/sT5sYfX9P9vqY7fU1399rzGnWPr31So+7oNd3Ra7qX176gUU/7NT3t1/T0Xvu2Rt3dT/W0f8pz/tNHP6Pxsxr/QuNfavycxs9r/ILGL2n8ssa/0vhVjV/T+HWN/sxvavyWxkcaX9H4qsYfa/y5xt9YbE2jfufpH2n8icbXNP5U4880vq7xDY2/0KhPePCsxuc0fkzj8xpf0Piixk9q/JRG3fUD3fUD3fUD3fUD3e8D3e+DL2rUXT/Q/T74ikbd9YNva/y+xr/TqCt/oGt7Rp/2jD7nGT2fZ/Q0ntW/f1bP9jldw3O6hud0Dc/pvz7n/6rn9jE9mY99QqN+5/kHGnW/z+t+n9f9Pq/7fV7X/Lyu+Xld8/N6L89/V+P3NOqan2c+/+kF/dULel8v6I5eYIb86UV9y4v6/Bf1TF7UJ39c3/u5j2rU73xBb/wL+rQvMhv/9CX9zpf0t1/S8/+yfufLL2nU539Zd/dl1sWfvqGr+oau6kesiz/9XP/8c/3zr/j99z/6tMYHGp/X+ILGFzV+XOMnNH5S46c0floj7+v9p/W3mmnvP/2cRn3O0/qEp/UJT+tvn9ZfPf1ZjX+p8fMav6jxyxq/ovFrGr+h8ZsaX9L4bY2PNH5P499o/FuNf6fxBxpf1vhDja9qfE3j6xp/ofHXGpnn7z/4qEY9jQe6owe6I8389zXn39ecf19z/v0Huq8HejKa/+9rtr+v2f7+A13zg29p1JVrVr//QFf+4Lsadf0PdP0PdP0PdOUPdM2a8+8/+LFGXfmDn2l8Q6Ou/4Gu/KGu+eFDjbrmh7rmh7rmh7rah7rah3p3D/UWdJq8rxPkfZ0d7+u8eP/h1zXqyeu8eF/nxfs6L97XefH+Q82ch7qLh9/XqLt4qLt4qLfwUPfyUPfyUHfxUNf8kLn359c/qvEFjS9q/LjGT2r8gsYfaOSv/vzGsxr1O29wbX/+uf7555/Q+DmNn9f4dxp/rlF/+4unNer3f/GSRubGn3+p7/0la/nPv2LH+POv9e2/+ZpG7vrx09zp42cfanxB499q5FseP8dVPf4Y3/VYO8bjF/iExy/qN1/8ikae4eOP85mPP/FFjfr9Tz6tUZ/8Sf37T3Iljz/F3T3+9Esav63xVY3M28efeV6jPv8zn9Cob/wL/fNX9Dlf0fd+hcjn8Vc/rlGf+VVOgcdfY24//gYz4fFf65//mhPh8Uu6L8XVjxVRP1Zs/Pjb39f4Nxr1O9/RNXyHd/r4B5/RyKx+/PJHNX5Mo67wZV2PosHHL+uOFPU9fvmnGpm9j3+op/GK/uoVffsr+v0fMf8fv6q38GP9/k90zT/Tk/zZ1zXqE17Xv3lD1/OG7uUNPas39F9/+SWNrKDHv9Lv/FrP6tf65F+zph7/Rm/hN89o1DX/hrf2wTM8yQ+e/4zGz2p8pJHP/+CFj2vk0z74HN/1wRc+pvEVjazTD77I/PngS5/S+A2N/jfM7Q++zL1/8JVXNeozv/q8xhc0fk3j9zQy3z74mj7na7qSr/1IIzvYB1/nmj94iWf7wXeY1R98T9/+fV3hD3SFP/iWxpc06i5+yKr5QM/8g1f0ma/8RONrGn+mUVf1I135q/qEV3+skZX1wY9ZcR+8pt98nbXwwS/5nX/7KFf7b9qT/03n4L+9qH/zKa7n3z73DY2v/P8dl0kOwjAMRfecGgRSmRFIDAXKPBeBBEug17G96hXQf5unqEkc69txY6i9NlEtMtSwVHlr8waUnrZ4QHliyxrEwlqe2IFd9Fx2VFYY3ZPRoRi9iZ0598rKnHG+gVLJ3rDoQ2W7847y1hNq1ttS2ztwwPehYuRT3VDfdqGi4Edlgp90il/krd/klaOnvzIonf3Thrq/XijDg39iUKWDqhv1C5QmwVslEmYTxSuashPjBMp+TKoQO7MMyp9I3xA7C2kb2QgqXrHjlL1UjVMKFa/IdXeCqhiF9C/vNai6UX4Zf5uwBbuwB/twAOdQ9svfqvIHCUYI41SIAwA=",
    "tokenizer_config.json": "H4sIAL0Nq2kC/6tWSsmPz8kvTy2KT04sTlWyUigpKk3VUVDKzU9JzYnPTayIz0nNSy/JAMqYGhrVAgB7eP+3MAAAAA==",
}

for filename, payload in embedded_assets.items():
    path = os.path.join(local_dir, filename)
    if not os.path.exists(path):
        with open(path, "wb") as f:
            f.write(gzip.decompress(base64.b64decode(payload)))

tokenizer = BertTokenizer.from_pretrained(local_dir, local_files_only=True)
config = BertConfig.from_pretrained(local_dir, local_files_only=True)
model = BertModel(config)

print("transformers version:", transformers.__version__)
print("Loaded architecture for:", model_name)
print("Using local official config/vocab assets for reproducibility.")

transformers version: 5.0.0
Loaded architecture for: bert-base-uncased
Using local official config/vocab assets for reproducibility.

## 1. Load & inspect `bert-base-uncased`

In [2]:
config_table = pd.DataFrame(
    [
        ("hidden_size", config.hidden_size),
        ("num_hidden_layers", config.num_hidden_layers),
        ("num_attention_heads", config.num_attention_heads),
        ("intermediate_size", config.intermediate_size),
        ("vocab_size", config.vocab_size),
        ("max_position_embeddings", config.max_position_embeddings),
    ],
    columns=["Configuration item", "Value"],
)

display(config_table)

head_dim = config.hidden_size / config.num_attention_heads
print(f"head_dim = {config.hidden_size} / {config.num_attention_heads} = {head_dim}")

        Configuration item  Value
0              hidden_size    768
1        num_hidden_layers     12
2      num_attention_heads     12
3        intermediate_size   3072
4               vocab_size  30522
5  max_position_embeddings    512

head_dim = 768 / 12 = 64.0

In [3]:
layer0 = model.encoder.layer[0]

layer0_table = pd.DataFrame(
    [
        ("layer0.attention.self.num_attention_heads", layer0.attention.self.num_attention_heads),
        ("layer0.attention.self.query.in_features", layer0.attention.self.query.in_features),
        ("layer0.attention.self.query.out_features", layer0.attention.self.query.out_features),
        ("layer0.intermediate.dense.in_features", layer0.intermediate.dense.in_features),
        ("layer0.intermediate.dense.out_features", layer0.intermediate.dense.out_features),
    ],
    columns=["Layer 0 parameter", "Value"],
)

display(layer0_table)

                           Layer 0 parameter  Value
0  layer0.attention.self.num_attention_heads     12
1    layer0.attention.self.query.in_features    768
2   layer0.attention.self.query.out_features    768
3      layer0.intermediate.dense.in_features    768
4     layer0.intermediate.dense.out_features   3072

## 2. Single forward pass

In [4]:
text = "I love using transformers!"
inputs = tokenizer(text, return_tensors="pt")

with torch.no_grad():
    outputs = model(**inputs)

tokens = tokenizer.convert_ids_to_tokens(inputs["input_ids"][0])

print("Tokens:", tokens)
print("last_hidden_state.shape =", outputs.last_hidden_state.shape)

Tokens: ['[CLS]', 'i', 'love', 'using', 'transformers', '!', '[SEP]']
last_hidden_state.shape = torch.Size([1, 7, 768])